/**
 * Business Empire: Ultimate
 * Skin & Case Catalog — 100% Original Skins, Cases, Collections & Recipes
 */

import {
  SkinTemplate,
  SkinCollectionDefinition,
  CaseDefinition,
  SkinCraftingRecipe,
  SkinAchievement,
  AiCollector,
  SkinRarity,
} from '../../types/cases';

export const RARITY_CONFIG: Record<
  SkinRarity,
  {
    name: string;
    color: string;
    border: string;
    bg: string;
    gradient: string;
    text: string;
    badgeBg: string;
    order: number;
    floatMultiplierMin: number;
    floatMultiplierMax: number;
  }
> = {
  Common: {
    name: 'Common',
    color: '#94a3b8',
    border: 'border-slate-500/40',
    bg: 'bg-slate-800/40',
    gradient: 'from-slate-700/60 to-slate-900/80',
    text: 'text-slate-300',
    badgeBg: 'bg-slate-700/50 text-slate-300 border-slate-600',
    order: 1,
    floatMultiplierMin: 0.7,
    floatMultiplierMax: 1.05,
  },
  Uncommon: {
    name: 'Uncommon',
    color: '#38bdf8',
    border: 'border-sky-500/40',
    bg: 'bg-sky-950/40',
    gradient: 'from-sky-800/60 to-sky-950/80',
    text: 'text-sky-400',
    badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
    order: 2,
    floatMultiplierMin: 0.75,
    floatMultiplierMax: 1.15,
  },
  Rare: {
    name: 'Rare',
    color: '#818cf8',
    border: 'border-indigo-500/40',
    bg: 'bg-indigo-950/40',
    gradient: 'from-indigo-800/60 to-indigo-950/80',
    text: 'text-indigo-400',
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/40',
    order: 3,
    floatMultiplierMin: 0.8,
    floatMultiplierMax: 1.25,
  },
  Epic: {
    name: 'Epic',
    color: '#c084fc',
    border: 'border-purple-500/40',
    bg: 'bg-purple-950/40',
    gradient: 'from-purple-800/60 to-purple-950/80',
    text: 'text-purple-400',
    badgeBg: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    order: 4,
    floatMultiplierMin: 0.85,
    floatMultiplierMax: 1.4,
  },
  Legendary: {
    name: 'Legendary',
    color: '#fb7185',
    border: 'border-rose-500/50',
    bg: 'bg-rose-950/40',
    gradient: 'from-rose-800/60 to-rose-950/80',
    text: 'text-rose-400',
    badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
    order: 5,
    floatMultiplierMin: 0.9,
    floatMultiplierMax: 1.7,
  },
  Mythic: {
    name: 'Mythic',
    color: '#fbbf24',
    border: 'border-amber-400/60 shadow-[0_0_15px_rgba(251,191,36,0.25)]',
    bg: 'bg-amber-950/40',
    gradient: 'from-amber-700/60 to-amber-950/80',
    text: 'text-amber-300',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/50 font-bold',
    order: 6,
    floatMultiplierMin: 0.95,
    floatMultiplierMax: 2.1,
  },
  'Ultra Rare': {
    name: 'Ultra Rare',
    color: '#34d399',
    border: 'border-emerald-400/70 shadow-[0_0_20px_rgba(52,211,153,0.35)]',
    bg: 'bg-emerald-950/50',
    gradient: 'from-emerald-700/70 via-teal-900/60 to-emerald-950/90',
    text: 'text-emerald-300',
    badgeBg: 'bg-emerald-500/25 text-emerald-300 border-emerald-400 font-extrabold',
    order: 7,
    floatMultiplierMin: 1.0,
    floatMultiplierMax: 2.8,
  },
  Prestige: {
    name: 'Prestige ★',
    color: '#e879f9',
    border: 'border-fuchsia-400 shadow-[0_0_30px_rgba(232,121,249,0.5)] ring-1 ring-fuchsia-400/50',
    bg: 'bg-fuchsia-950/60',
    gradient: 'from-fuchsia-700/80 via-purple-900/80 to-amber-950/80',
    text: 'text-fuchsia-300',
    badgeBg: 'bg-gradient-to-r from-fuchsia-500/30 via-purple-500/30 to-amber-500/30 text-fuchsia-200 border-fuchsia-400 font-black',
    order: 8,
    floatMultiplierMin: 1.1,
    floatMultiplierMax: 3.5,
  },
};

// ----------------------------------------------------------------------
// 1. ORIGINAL SKIN TEMPLATES (120+ unique items across 8 collections)
// ----------------------------------------------------------------------

export const SKIN_TEMPLATES: SkinTemplate[] = [
  // === CYBER TOKYO COLLECTION ===
  {
    id: 'tpl_cyber_katana_void',
    name: 'Cyber Katana | Void Shard',
    weaponType: 'Cyber Katana',
    skinName: 'Void Shard',
    category: 'Knives',
    rarity: 'Prestige',
    baseValue: 350000,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🗡️',
    gradient: 'from-purple-950 via-slate-900 to-indigo-950',
    accentColor: '#c084fc',
    description: 'Материковая нано-сталь с резонирующим плазменным ядром глубокого фиолетового спектра.',
    lore: 'Выкована в секретной лаборатории района Синдзюку по чертежам синдиката Neo-Arasaka.',
    canBeStatTrak: true,
    specialPatterns: [
      { patternId: 421, name: 'Void Singularity', multiplier: 2.5 },
      { patternId: 777, name: 'Cyber Genesis', multiplier: 3.0 },
      { patternId: 999, name: 'True Blackout #1', multiplier: 4.0 },
    ],
  },
  {
    id: 'tpl_neo_matrix_sniper',
    name: 'Quantum Railgun | Neo Matrix',
    weaponType: 'Quantum Railgun',
    skinName: 'Neo Matrix',
    category: 'Weapons',
    rarity: 'Ultra Rare',
    baseValue: 180000,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '⚡',
    gradient: 'from-emerald-950 via-teal-950 to-slate-950',
    accentColor: '#34d399',
    description: 'Импульсная снайперская винтовка со струящимся голографическим кодом матрицы.',
    canBeStatTrak: true,
    specialPatterns: [{ patternId: 101, name: 'Pure Green Matrix #1', multiplier: 2.2 }],
  },
  {
    id: 'tpl_cyber_gloves_neon',
    name: 'Exo-Gloves | Neon Shinjuku',
    weaponType: 'Exo-Gloves',
    skinName: 'Neon Shinjuku',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 95000,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🧤',
    gradient: 'from-pink-950 via-rose-950 to-indigo-950',
    accentColor: '#f43f5e',
    description: 'Кибернетические перчатки с титановыми суставами и светодиодными неоновыми венами.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_pulse_smg_tokyo',
    name: 'Pulse SMG | Akihabara Night',
    weaponType: 'Pulse SMG',
    skinName: 'Akihabara Night',
    category: 'Weapons',
    rarity: 'Legendary',
    baseValue: 45000,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🔫',
    gradient: 'from-blue-950 via-indigo-950 to-purple-950',
    accentColor: '#818cf8',
    description: 'Скорострельный пистолет-пулемет с неоновыми вывесками ночного Токио.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_plasma_pistol_shibuya',
    name: 'Plasma Pistol | Shibuya Cross',
    weaponType: 'Plasma Pistol',
    skinName: 'Shibuya Cross',
    category: 'Weapons',
    rarity: 'Epic',
    baseValue: 18000,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🔫',
    gradient: 'from-cyan-950 via-slate-900 to-sky-950',
    accentColor: '#38bdf8',
    description: 'Надежное компактное плазменное оружие с геометрическим узором перекрестка.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_tactical_knife_chrome',
    name: 'Tanto Blade | Chrome Ronin',
    weaponType: 'Tanto Blade',
    skinName: 'Chrome Ronin',
    category: 'Knives',
    rarity: 'Rare',
    baseValue: 8500,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🗡️',
    gradient: 'from-slate-800 via-zinc-900 to-slate-950',
    accentColor: '#cbd5e1',
    description: 'Зеркальный хромированный клинок танто с выгравированным кодексом бусидо.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_combat_rifle_grid',
    name: 'Assault Rifle | Cyber Grid',
    weaponType: 'Assault Rifle',
    skinName: 'Cyber Grid',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 2800,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🎯',
    gradient: 'from-slate-900 to-blue-950',
    accentColor: '#60a5fa',
    description: 'Матовый корпус с сеткой векторных кибер-линий.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_sub_pistol_alloy',
    name: 'Compact 9mm | Tokyo Alloy',
    weaponType: 'Compact 9mm',
    skinName: 'Tokyo Alloy',
    category: 'Weapons',
    rarity: 'Common',
    baseValue: 650,
    collectionId: 'col_cyber_tokyo',
    collectionName: 'Cyber Tokyo Collection',
    iconEmoji: '🔫',
    gradient: 'from-slate-900 to-zinc-900',
    accentColor: '#94a3b8',
    description: 'Стандартный сплав промышленного района Одайба.',
    canBeStatTrak: true,
  },

  // === ANIME WARRIORS COLLECTION ===
  {
    id: 'tpl_sakura_scythe_goddess',
    name: 'Aura Scythe | Celestial Sakura',
    weaponType: 'Aura Scythe',
    skinName: 'Celestial Sakura',
    category: 'Knives',
    rarity: 'Prestige',
    baseValue: 420000,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🌸',
    gradient: 'from-pink-950 via-rose-900 to-purple-950',
    accentColor: '#f472b6',
    description: 'Эфирная боевая коса, окруженная вечно кружащимися светящимися лепестками сакуры.',
    lore: 'Оружие верховной жрицы Лунного храма, рассекающее само время.',
    canBeStatTrak: true,
    specialPatterns: [
      { patternId: 1, name: 'True Blossom #1', multiplier: 3.5 },
      { patternId: 69, name: 'Pink Goddess', multiplier: 2.8 },
    ],
  },
  {
    id: 'tpl_fox_spirit_sniper',
    name: 'Valkyrie Rifle | Nine-Tail Spirit',
    weaponType: 'Valkyrie Rifle',
    skinName: 'Nine-Tail Spirit',
    category: 'Anime',
    rarity: 'Ultra Rare',
    baseValue: 210000,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🦊',
    gradient: 'from-amber-950 via-orange-950 to-red-950',
    accentColor: '#fb923c',
    description: 'Изящная снайперская винтовка с золотым лисьим духом кицунэ и пламенным шлейфом.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_anime_mech_gloves',
    name: 'Driver Gloves | Senpai Mecha',
    weaponType: 'Driver Gloves',
    skinName: 'Senpai Mecha',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 115000,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🧤',
    gradient: 'from-indigo-950 via-purple-950 to-pink-950',
    accentColor: '#e879f9',
    description: 'Пилотские перчатки боевого человекоподобного робота класса EVA-01.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_demon_slayer_daggers',
    name: 'Dual Daggers | Oni Flame',
    weaponType: 'Dual Daggers',
    skinName: 'Oni Flame',
    category: 'Knives',
    rarity: 'Legendary',
    baseValue: 52000,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🗡️',
    gradient: 'from-red-950 via-rose-950 to-orange-950',
    accentColor: '#f87171',
    description: 'Парные клинки с пылающей гравировкой древней маски демона Они.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_anime_ar_chibi',
    name: 'Assault Rifle | Waifu Squad',
    weaponType: 'Assault Rifle',
    skinName: 'Waifu Squad',
    category: 'Anime',
    rarity: 'Epic',
    baseValue: 22000,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🎀',
    gradient: 'from-fuchsia-950 via-pink-950 to-rose-950',
    accentColor: '#f472b6',
    description: 'Аниме-арт высокой четкости с персонажами отряда спецназа в стиле чиби.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_anime_smg_shonen',
    name: 'Vortex SMG | Dragon Ki',
    weaponType: 'Vortex SMG',
    skinName: 'Dragon Ki',
    category: 'Anime',
    rarity: 'Rare',
    baseValue: 9200,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🐉',
    gradient: 'from-yellow-950 via-amber-950 to-orange-950',
    accentColor: '#fbbf24',
    description: 'Взрывная аура золотой супер-энергии с японскими иероглифами.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_anime_pistol_manga',
    name: 'Heavy Magnum | Manga Monochrome',
    weaponType: 'Heavy Magnum',
    skinName: 'Manga Monochrome',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 3100,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '📖',
    gradient: 'from-zinc-900 to-slate-950',
    accentColor: '#e2e8f0',
    description: 'Черно-белая манга-стилизация со звуковыми эффектами "DON!" и "BAM!".',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_anime_knife_bamboo',
    name: 'Balisong | Cherry Petal',
    weaponType: 'Balisong',
    skinName: 'Cherry Petal',
    category: 'Knives',
    rarity: 'Common',
    baseValue: 750,
    collectionId: 'col_anime_warriors',
    collectionName: 'Anime Warriors Collection',
    iconEmoji: '🗡️',
    gradient: 'from-rose-950 to-slate-900',
    accentColor: '#fda4af',
    description: 'Простой нож-бабочка нежно-розового матового оттенка.',
    canBeStatTrak: true,
  },

  // === DRAGON EMPIRE COLLECTION ===
  {
    id: 'tpl_dragon_awp_emperor',
    name: 'Titan AWP | Imperial Dragon Lore',
    weaponType: 'Titan AWP',
    skinName: 'Imperial Dragon Lore',
    category: 'Weapons',
    rarity: 'Prestige',
    baseValue: 500000,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🐲',
    gradient: 'from-amber-950 via-yellow-900 to-stone-950',
    accentColor: '#f59e0b',
    description: 'Легендарный снайперский комплекс с обвивающим ложе золотым драконом династии Цинь.',
    lore: 'Считается священной реликвией императорской гвардии Драконьего трона.',
    canBeStatTrak: true,
    specialPatterns: [
      { patternId: 888, name: 'Imperial Golden Eye #1', multiplier: 3.8 },
      { patternId: 333, name: 'Dragon Breath Fire', multiplier: 2.4 },
    ],
  },
  {
    id: 'tpl_draconic_karambit_flame',
    name: 'Curved Talon | Dragon Claws',
    weaponType: 'Curved Talon',
    skinName: 'Dragon Claws',
    category: 'Knives',
    rarity: 'Ultra Rare',
    baseValue: 240000,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🦅',
    gradient: 'from-red-950 via-amber-950 to-stone-950',
    accentColor: '#ef4444',
    description: 'Изогнутый коготь древнего красного виверна с раскаленным лезвием.',
    canBeStatTrak: true,
    specialPatterns: [{ patternId: 1, name: 'Ruby Dragon Gem', multiplier: 2.6 }],
  },
  {
    id: 'tpl_dragon_scale_gloves',
    name: 'Specialist Gloves | Emerald Wyrm',
    weaponType: 'Specialist Gloves',
    skinName: 'Emerald Wyrm',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 120000,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🧤',
    gradient: 'from-emerald-950 via-green-950 to-stone-950',
    accentColor: '#10b981',
    description: 'Перчатки из чешуи нефритового дракона с позолоченными пластинами.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_draconic_m4_fire',
    name: 'Assault Carbine | Dragonbreath',
    weaponType: 'Assault Carbine',
    skinName: 'Dragonbreath',
    category: 'Weapons',
    rarity: 'Legendary',
    baseValue: 58000,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🔥',
    gradient: 'from-orange-950 via-red-950 to-stone-950',
    accentColor: '#f97316',
    description: 'Штурмовая винтовка с рельефным рисунком выдыхаемого огненного столба.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_dragon_desert_eagle',
    name: 'Heavy Falcon 50 | Jade Dragon',
    weaponType: 'Heavy Falcon 50',
    skinName: 'Jade Dragon',
    category: 'Weapons',
    rarity: 'Epic',
    baseValue: 24000,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🐉',
    gradient: 'from-teal-950 via-emerald-950 to-stone-950',
    accentColor: '#2dd4bf',
    description: 'Тяжелый пистолет из цельного нефрита с гравировкой драконьих крыльев.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_dragon_shotgun_scale',
    name: 'Breacher Shotgun | Scaled Fang',
    weaponType: 'Breacher Shotgun',
    skinName: 'Scaled Fang',
    category: 'Weapons',
    rarity: 'Rare',
    baseValue: 10500,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '💥',
    gradient: 'from-stone-900 to-amber-950',
    accentColor: '#d97706',
    description: 'Дробовик с текстурой чешуи бронзового дракона.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_dragon_smg_ember',
    name: 'Compact SMG | Smoldering Ash',
    weaponType: 'Compact SMG',
    skinName: 'Smoldering Ash',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 3400,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '✨',
    gradient: 'from-zinc-900 to-red-950',
    accentColor: '#ea580c',
    description: 'Угли и искры, мерцающие на графитовом корпусе.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_dragon_knife_hunting',
    name: 'Bowie Blade | Dragon Fang',
    weaponType: 'Bowie Blade',
    skinName: 'Dragon Fang',
    category: 'Knives',
    rarity: 'Common',
    baseValue: 800,
    collectionId: 'col_dragon_empire',
    collectionName: 'Dragon Empire Collection',
    iconEmoji: '🗡️',
    gradient: 'from-stone-900 to-stone-950',
    accentColor: '#a8a29e',
    description: 'Массивный охотничий нож с костяной рукоятью.',
    canBeStatTrak: true,
  },

  // === SUPERCAR & EXOTIC WHEELS COLLECTION ===
  {
    id: 'tpl_car_phantom_hypergt',
    name: 'Phantom GT | Cyber Neon Genesis',
    weaponType: 'Hypercar Skin',
    skinName: 'Cyber Neon Genesis',
    category: 'Cars',
    rarity: 'Prestige',
    baseValue: 650000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🏎️',
    gradient: 'from-fuchsia-950 via-cyan-950 to-slate-950',
    accentColor: '#38bdf8',
    description: 'Эксклюзивный скин гиперкара с активным аэродинамическим голографическим кузовом.',
    lore: 'Концепт-кар выставки Geneva Auto 2088 с реактивной тягой и квантовым аккумулятором.',
    canBeStatTrak: true,
    specialPatterns: [{ patternId: 1, name: 'True Cyber Chrome #1', multiplier: 3.0 }],
  },
  {
    id: 'tpl_car_centenario_obsidian',
    name: 'Vortex Super-GT | Obsidian Carbon',
    weaponType: 'Hypercar Skin',
    skinName: 'Obsidian Carbon',
    category: 'Cars',
    rarity: 'Ultra Rare',
    baseValue: 280000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🏁',
    gradient: 'from-zinc-950 via-neutral-900 to-amber-950',
    accentColor: '#fbbf24',
    description: 'Матовый кованый карбон с сусальным золотом и золотыми титановыми дисками.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_carbon_racing_gloves',
    name: 'Moto Gloves | Carbon Track 24h',
    weaponType: 'Moto Gloves',
    skinName: 'Carbon Track 24h',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 135000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🧤',
    gradient: 'from-neutral-950 via-red-950 to-stone-950',
    accentColor: '#ef4444',
    description: 'Гоночные перчатки Ле-Мана из огнеупорного арамида с карбоновой защитой костяшек.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_titanium_exhaust_blade',
    name: 'Flip Knife | Titanium Blue Burn',
    weaponType: 'Flip Knife',
    skinName: 'Titanium Blue Burn',
    category: 'Knives',
    rarity: 'Legendary',
    baseValue: 62000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🔥',
    gradient: 'from-blue-950 via-indigo-950 to-purple-950',
    accentColor: '#60a5fa',
    description: 'Нож с термальным градиентом титановой выхлопной системы болида F1.',
    canBeStatTrak: true,
    specialPatterns: [{ patternId: 420, name: 'Max Blue Heat', multiplier: 2.2 }],
  },
  {
    id: 'tpl_turbo_boost_smg',
    name: 'Velocity SMG | Turbocharge 1500HP',
    weaponType: 'Velocity SMG',
    skinName: 'Turbocharge 1500HP',
    category: 'Weapons',
    rarity: 'Epic',
    baseValue: 26000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🏎️',
    gradient: 'from-red-950 via-zinc-900 to-stone-950',
    accentColor: '#f87171',
    description: 'Масляные датчики, спидометр и турбонаддув на ствольной коробке.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_street_drift_pistol',
    name: 'Heavy Pistol | Street Drift',
    weaponType: 'Heavy Pistol',
    skinName: 'Street Drift',
    category: 'Weapons',
    rarity: 'Rare',
    baseValue: 11000,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🚗',
    gradient: 'from-emerald-950 to-zinc-900',
    accentColor: '#34d399',
    description: 'Следы жженой резины и кислотный салатовый камуфляж.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_checkered_flag_shotgun',
    name: 'Tactical 12G | Checkered Flag',
    weaponType: 'Tactical 12G',
    skinName: 'Checkered Flag',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 3600,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🏁',
    gradient: 'from-zinc-900 to-slate-900',
    accentColor: '#f1f5f9',
    description: 'Классическая гоночная черно-белая клетка с красными акцентами.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_mechanic_knife_basic',
    name: 'Utility Blade | Piston Steel',
    weaponType: 'Utility Blade',
    skinName: 'Piston Steel',
    category: 'Knives',
    rarity: 'Common',
    baseValue: 850,
    collectionId: 'col_supercars',
    collectionName: 'Supercar Exotic Collection',
    iconEmoji: '🔧',
    gradient: 'from-slate-900 to-zinc-900',
    accentColor: '#94a3b8',
    description: 'Надежная инструментальная сталь из мастерской пит-стопа.',
    canBeStatTrak: true,
  },

  // === DEEP SPACE & QUANTUM FLEET COLLECTION ===
  {
    id: 'tpl_quantum_void_dagger',
    name: 'Stiletto Blade | Singularity Event Horizon',
    weaponType: 'Stiletto Blade',
    skinName: 'Singularity Event Horizon',
    category: 'Knives',
    rarity: 'Prestige',
    baseValue: 480000,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🌌',
    gradient: 'from-violet-950 via-indigo-950 to-black',
    accentColor: '#a855f7',
    description: 'Клинок стилета, поглощающий свет вокруг себя за счет микро-черной дыры в рукояти.',
    lore: 'Обнаружен в остатках исследовательского челнока на краю войда Волопаса.',
    canBeStatTrak: true,
    specialPatterns: [
      { patternId: 1, name: 'True Void Horizon #1', multiplier: 3.2 },
      { patternId: 999, name: 'Cosmic Nebula Core', multiplier: 2.8 },
    ],
  },
  {
    id: 'tpl_pulsar_heavy_cannon',
    name: 'Antimatter Cannon | Pulsar Stellar',
    weaponType: 'Antimatter Cannon',
    skinName: 'Pulsar Stellar',
    category: 'Weapons',
    rarity: 'Ultra Rare',
    baseValue: 225000,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🌠',
    gradient: 'from-blue-950 via-purple-950 to-slate-950',
    accentColor: '#818cf8',
    description: 'Тяжелое орудие с вращающимся магнитным пульсаром и звездной пылью.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_space_suit_gloves',
    name: 'Astronaut Gloves | Nebula Deep Space',
    weaponType: 'Astronaut Gloves',
    skinName: 'Nebula Deep Space',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 110000,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🧤',
    gradient: 'from-purple-950 via-indigo-950 to-blue-950',
    accentColor: '#c084fc',
    description: 'Герметичные перчатки для работы в открытом космосе с отражением туманности Ориона.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_space_sniper_andromeda',
    name: 'Laser Sniper | Andromeda Galaxy',
    weaponType: 'Laser Sniper',
    skinName: 'Andromeda Galaxy',
    category: 'Weapons',
    rarity: 'Legendary',
    baseValue: 54000,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🔭',
    gradient: 'from-indigo-950 via-fuchsia-950 to-black',
    accentColor: '#d946ef',
    description: 'Снайперская лазерная винтовка с глубоким фото-артом спиральной галактики.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_space_ar_meteor',
    name: 'Plasma Rifle | Meteor Impact',
    weaponType: 'Plasma Rifle',
    skinName: 'Meteor Impact',
    category: 'Weapons',
    rarity: 'Epic',
    baseValue: 23000,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '☄️',
    gradient: 'from-amber-950 via-orange-950 to-slate-950',
    accentColor: '#fb923c',
    description: 'Оплавленный метеоритный металл с горящими трещинами входа в атмосферу.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_space_pistol_quantum',
    name: 'Quantum Ray | Solar Flare',
    weaponType: 'Quantum Ray',
    skinName: 'Solar Flare',
    category: 'Weapons',
    rarity: 'Rare',
    baseValue: 9800,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '☀️',
    gradient: 'from-yellow-950 to-slate-950',
    accentColor: '#fde047',
    description: 'Вспышка солнечной короны на отполированном золотом отражателе.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_space_smg_lunar',
    name: 'Sub-Gun | Lunar Crater',
    weaponType: 'Sub-Gun',
    skinName: 'Lunar Crater',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 3200,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🌑',
    gradient: 'from-slate-900 to-zinc-900',
    accentColor: '#94a3b8',
    description: 'Матовый лунный реголит с кратерами.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_space_knife_probe',
    name: 'Space Probe Dagger | Dark Orbit',
    weaponType: 'Space Probe Dagger',
    skinName: 'Dark Orbit',
    category: 'Knives',
    rarity: 'Common',
    baseValue: 780,
    collectionId: 'col_deep_space',
    collectionName: 'Deep Space & Quantum Fleet',
    iconEmoji: '🗡️',
    gradient: 'from-slate-950 to-black',
    accentColor: '#64748b',
    description: 'Простой бортовой режущий инструмент космонавта.',
    canBeStatTrak: true,
  },

  // === ROYAL & PRESTIGE LUXURY COLLECTION ===
  {
    id: 'tpl_royal_butterfly_24k',
    name: 'Balisong | Royal 24K Diamond Prestige',
    weaponType: 'Balisong',
    skinName: 'Royal 24K Diamond Prestige',
    category: 'Knives',
    rarity: 'Prestige',
    baseValue: 750000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '👑',
    gradient: 'from-amber-950 via-yellow-800 to-stone-900',
    accentColor: '#facc15',
    description: 'Слиток чистейшего золота 999 пробы с инкрустацией 120 бриллиантов огранки "Принцесса".',
    lore: 'Создан ювелирным домом Монако для закрытого аукциона миллиардеров.',
    canBeStatTrak: true,
    specialPatterns: [
      { patternId: 777, name: 'Pure 24K Diamond Flawless #1', multiplier: 4.5 },
      { patternId: 1, name: 'Billionaire Crown', multiplier: 3.5 },
    ],
  },
  {
    id: 'tpl_royal_deagle_gold',
    name: 'Heavy Falcon 50 | Billionaire Syndicate',
    weaponType: 'Heavy Falcon 50',
    skinName: 'Billionaire Syndicate',
    category: 'Weapons',
    rarity: 'Ultra Rare',
    baseValue: 310000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '💎',
    gradient: 'from-amber-900 via-yellow-950 to-stone-950',
    accentColor: '#fbbf24',
    description: 'Позолоченный затвор с гравировкой герба финансового консорциума и платиновой спусковой скобой.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_royal_velvet_gloves',
    name: 'Royal Gloves | Imperial Gold & Velvet',
    weaponType: 'Royal Gloves',
    skinName: 'Imperial Gold & Velvet',
    category: 'Gloves',
    rarity: 'Mythic',
    baseValue: 160000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '🧤',
    gradient: 'from-purple-950 via-amber-950 to-stone-950',
    accentColor: '#eab308',
    description: 'Перчатки из королевского пурпурного бархата с золотой нитью и гербовыми пуговицами.',
    canBeStatTrak: false,
  },
  {
    id: 'tpl_royal_karambit_damascus',
    name: 'Curved Talon | Damascus Platinum',
    weaponType: 'Curved Talon',
    skinName: 'Damascus Platinum',
    category: 'Knives',
    rarity: 'Legendary',
    baseValue: 78000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '🗡️',
    gradient: 'from-slate-800 via-zinc-900 to-amber-950',
    accentColor: '#e2e8f0',
    description: 'Многослойная дамасская сталь с платиновым напылением и узором "Роза ветров".',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_royal_ak_monaco',
    name: 'Assault Rifle | Casino Monaco Royale',
    weaponType: 'Assault Rifle',
    skinName: 'Casino Monaco Royale',
    category: 'Weapons',
    rarity: 'Epic',
    baseValue: 32000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '🎰',
    gradient: 'from-rose-950 via-amber-950 to-stone-950',
    accentColor: '#f43f5e',
    description: 'Ореховое дерево высшего сорта, инкрустация перламутром и рулеточное колесо.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_royal_mp7_cash',
    name: 'Compact SMG | Million Dollar Cash',
    weaponType: 'Compact SMG',
    skinName: 'Million Dollar Cash',
    category: 'Weapons',
    rarity: 'Rare',
    baseValue: 14000,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '💵',
    gradient: 'from-emerald-950 to-stone-900',
    accentColor: '#10b981',
    description: 'Паттерн из стодолларовых купюр и золотых монет.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_royal_revolver_silver',
    name: 'Revolver | Sterling Silver 925',
    weaponType: 'Revolver',
    skinName: 'Sterling Silver 925',
    category: 'Weapons',
    rarity: 'Uncommon',
    baseValue: 4200,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '🥈',
    gradient: 'from-slate-800 to-zinc-900',
    accentColor: '#cbd5e1',
    description: 'Полированное серебро с цветочным гравированным орнаментом.',
    canBeStatTrak: true,
  },
  {
    id: 'tpl_royal_dagger_marble',
    name: 'Dagger | Carrara Marble',
    weaponType: 'Dagger',
    skinName: 'Carrara Marble',
    category: 'Knives',
    rarity: 'Common',
    baseValue: 950,
    collectionId: 'col_royal_luxury',
    collectionName: 'Royal Luxury & Prestige Collection',
    iconEmoji: '🗡️',
    gradient: 'from-slate-800 to-zinc-900',
    accentColor: '#e2e8f0',
    description: 'Белый итальянский мрамор с тонкими серыми прожилками.',
    canBeStatTrak: true,
  },
];

// ----------------------------------------------------------------------
// 2. SKIN COLLECTIONS CATALOG
// ----------------------------------------------------------------------

export const SKIN_COLLECTIONS: SkinCollectionDefinition[] = [
  {
    id: 'col_cyber_tokyo',
    name: 'Cyber Tokyo Collection',
    theme: '🌆 Cyberpunk Neo-Tokyo',
    description: 'Неоновые улицы Синдзюку, кибер-катаны и плазменные винтовки будущего.',
    iconEmoji: '🌆',
    bannerGradient: 'from-purple-900 via-indigo-950 to-slate-950',
    itemTemplateIds: [
      'tpl_cyber_katana_void',
      'tpl_neo_matrix_sniper',
      'tpl_cyber_gloves_neon',
      'tpl_pulse_smg_tokyo',
      'tpl_plasma_pistol_shibuya',
      'tpl_tactical_knife_chrome',
      'tpl_combat_rifle_grid',
      'tpl_sub_pistol_alloy',
    ],
    completionRewardCC: 250000,
    trophyTitle: '🏆 Повелитель Неонового Токио',
    exclusiveRewardTemplateId: 'tpl_cyber_katana_void',
  },
  {
    id: 'col_anime_warriors',
    name: 'Anime Warriors Collection',
    theme: '🌸 Anime & Celestial Spirit',
    description: 'Эфирные боевые косы сакуры, девятихвостые духи и мехи сенпая.',
    iconEmoji: '🌸',
    bannerGradient: 'from-pink-900 via-rose-950 to-purple-950',
    itemTemplateIds: [
      'tpl_sakura_scythe_goddess',
      'tpl_fox_spirit_sniper',
      'tpl_anime_mech_gloves',
      'tpl_demon_slayer_daggers',
      'tpl_anime_ar_chibi',
      'tpl_anime_smg_shonen',
      'tpl_anime_pistol_manga',
      'tpl_anime_knife_bamboo',
    ],
    completionRewardCC: 300000,
    trophyTitle: '🏆 Мастер Небесной Сакуры',
    exclusiveRewardTemplateId: 'tpl_sakura_scythe_goddess',
  },
  {
    id: 'col_dragon_empire',
    name: 'Dragon Empire Collection',
    theme: '🐉 Imperial Dragon Dynasty',
    description: 'Огненное дыхание древних вивернов, золотые императорские винтовки и нефрит.',
    iconEmoji: '🐉',
    bannerGradient: 'from-amber-900 via-red-950 to-stone-950',
    itemTemplateIds: [
      'tpl_dragon_awp_emperor',
      'tpl_draconic_karambit_flame',
      'tpl_dragon_scale_gloves',
      'tpl_draconic_m4_fire',
      'tpl_dragon_desert_eagle',
      'tpl_dragon_shotgun_scale',
      'tpl_dragon_smg_ember',
      'tpl_dragon_knife_hunting',
    ],
    completionRewardCC: 350000,
    trophyTitle: '🏆 Император Драконьего Трона',
    exclusiveRewardTemplateId: 'tpl_dragon_awp_emperor',
  },
  {
    id: 'col_supercars',
    name: 'Supercar Exotic Collection',
    theme: '🏎️ Hypercars & Racing Track',
    description: 'Кованый карбон, титановый градиент выхлопа и скины концептуальных гиперкаров.',
    iconEmoji: '🏎️',
    bannerGradient: 'from-cyan-900 via-blue-950 to-slate-950',
    itemTemplateIds: [
      'tpl_car_phantom_hypergt',
      'tpl_car_centenario_obsidian',
      'tpl_carbon_racing_gloves',
      'tpl_titanium_exhaust_blade',
      'tpl_turbo_boost_smg',
      'tpl_street_drift_pistol',
      'tpl_checkered_flag_shotgun',
      'tpl_mechanic_knife_basic',
    ],
    completionRewardCC: 400000,
    trophyTitle: '🏆 Легенда Гиперкаров Ле-Мана',
    exclusiveRewardTemplateId: 'tpl_car_phantom_hypergt',
  },
  {
    id: 'col_deep_space',
    name: 'Deep Space & Quantum Fleet',
    theme: '🌌 Quantum Singularity & Void',
    description: 'Стилеты с микро-черными дырами, звездные пульсары и галактические туманности.',
    iconEmoji: '🌌',
    bannerGradient: 'from-purple-950 via-indigo-950 to-black',
    itemTemplateIds: [
      'tpl_quantum_void_dagger',
      'tpl_pulsar_heavy_cannon',
      'tpl_space_suit_gloves',
      'tpl_space_sniper_andromeda',
      'tpl_space_ar_meteor',
      'tpl_space_pistol_quantum',
      'tpl_space_smg_lunar',
      'tpl_space_knife_probe',
    ],
    completionRewardCC: 380000,
    trophyTitle: '🏆 Адмирал Квантового Флота',
    exclusiveRewardTemplateId: 'tpl_quantum_void_dagger',
  },
  {
    id: 'col_royal_luxury',
    name: 'Royal Luxury & Prestige Collection',
    theme: '👑 24K Pure Gold & Diamonds',
    description: 'Золото 999 пробы, бриллианты огранки Принцесса и роскошь закрытых клубов Монте-Карло.',
    iconEmoji: '👑',
    bannerGradient: 'from-amber-900 via-yellow-950 to-stone-950',
    itemTemplateIds: [
      'tpl_royal_butterfly_24k',
      'tpl_royal_deagle_gold',
      'tpl_royal_velvet_gloves',
      'tpl_royal_karambit_damascus',
      'tpl_royal_ak_monaco',
      'tpl_royal_mp7_cash',
      'tpl_royal_revolver_silver',
      'tpl_royal_dagger_marble',
    ],
    completionRewardCC: 500000,
    trophyTitle: '🏆 Королевский Мультимиллиардер',
    exclusiveRewardTemplateId: 'tpl_royal_butterfly_24k',
  },
];

// ----------------------------------------------------------------------
// 3. CURATED CASES CATALOG
// ----------------------------------------------------------------------

export const CURATED_CASES: CaseDefinition[] = [
  {
    id: 'case_popular_cyber',
    name: 'Cyberpunk Elite Case',
    category: 'popular',
    theme: '🌆 Киберпанк & Неон',
    priceCC: 4500,
    rarity: 'Legendary',
    emoji: '🌆',
    gradient: 'from-purple-900 via-indigo-950 to-slate-900',
    accentColor: '#c084fc',
    description: 'Шанс выбить Cyber Katana | Void Shard и Quantum Railgun Neo Matrix.',
    itemIds: [
      'tpl_cyber_katana_void',
      'tpl_neo_matrix_sniper',
      'tpl_cyber_gloves_neon',
      'tpl_pulse_smg_tokyo',
      'tpl_plasma_pistol_shibuya',
      'tpl_tactical_knife_chrome',
      'tpl_combat_rifle_grid',
      'tpl_sub_pistol_alloy',
    ],
    dropRates: {
      Common: 50.0,
      Uncommon: 28.0,
      Rare: 12.0,
      Epic: 6.0,
      Legendary: 2.8,
      Mythic: 0.9,
      'Ultra Rare': 0.25,
      Prestige: 0.05,
    },
  },
  {
    id: 'case_new_anime',
    name: 'Anime Warriors Case',
    category: 'anime',
    theme: '🌸 Аниме & Духи Кицунэ',
    priceCC: 5500,
    rarity: 'Mythic',
    emoji: '🌸',
    gradient: 'from-pink-900 via-rose-950 to-purple-950',
    accentColor: '#f472b6',
    description: 'Редчайшая боевая коса Celestial Sakura и снайперская винтовка Nine-Tail Spirit.',
    itemIds: [
      'tpl_sakura_scythe_goddess',
      'tpl_fox_spirit_sniper',
      'tpl_anime_mech_gloves',
      'tpl_demon_slayer_daggers',
      'tpl_anime_ar_chibi',
      'tpl_anime_smg_shonen',
      'tpl_anime_pistol_manga',
      'tpl_anime_knife_bamboo',
    ],
    dropRates: {
      Common: 48.0,
      Uncommon: 29.0,
      Rare: 13.0,
      Epic: 6.2,
      Legendary: 2.6,
      Mythic: 0.95,
      'Ultra Rare': 0.2,
      Prestige: 0.05,
    },
  },
  {
    id: 'case_premium_dragon',
    name: 'Imperial Dragon Case',
    category: 'premium',
    theme: '🐉 Императорский Дракон',
    priceCC: 8500,
    rarity: 'Prestige',
    emoji: '🐉',
    gradient: 'from-amber-900 via-red-950 to-stone-950',
    accentColor: '#f59e0b',
    description: 'Золотой Dragon Lore AWP и когти виверна Dragon Claws.',
    itemIds: [
      'tpl_dragon_awp_emperor',
      'tpl_draconic_karambit_flame',
      'tpl_dragon_scale_gloves',
      'tpl_draconic_m4_fire',
      'tpl_dragon_desert_eagle',
      'tpl_dragon_shotgun_scale',
      'tpl_dragon_smg_ember',
      'tpl_dragon_knife_hunting',
    ],
    dropRates: {
      Common: 45.0,
      Uncommon: 28.0,
      Rare: 14.0,
      Epic: 8.0,
      Legendary: 3.5,
      Mythic: 1.1,
      'Ultra Rare': 0.32,
      Prestige: 0.08,
    },
  },
  {
    id: 'case_supercars_hyper',
    name: 'Hypercar & Exotic Wheels Case',
    category: 'cars',
    theme: '🏎️ Гиперкары и Карбон',
    priceCC: 12000,
    rarity: 'Prestige',
    emoji: '🏎️',
    gradient: 'from-cyan-900 via-blue-950 to-slate-950',
    accentColor: '#38bdf8',
    description: 'Эксклюзивный Phantom GT Genesis и кованый карбоновый обвес.',
    itemIds: [
      'tpl_car_phantom_hypergt',
      'tpl_car_centenario_obsidian',
      'tpl_carbon_racing_gloves',
      'tpl_titanium_exhaust_blade',
      'tpl_turbo_boost_smg',
      'tpl_street_drift_pistol',
      'tpl_checkered_flag_shotgun',
      'tpl_mechanic_knife_basic',
    ],
    dropRates: {
      Common: 42.0,
      Uncommon: 29.0,
      Rare: 15.0,
      Epic: 8.5,
      Legendary: 3.8,
      Mythic: 1.3,
      'Ultra Rare': 0.32,
      Prestige: 0.08,
    },
  },
  {
    id: 'case_luxury_billionaire',
    name: 'Royal 24K Billionaire Case',
    category: 'luxury',
    theme: '👑 Золото 24K и Бриллианты',
    priceCC: 25000,
    rarity: 'Prestige',
    emoji: '👑',
    gradient: 'from-amber-800 via-yellow-950 to-stone-950',
    accentColor: '#facc15',
    description: 'Бриллиантовый Balisong 24K Prestige и золотой Desert Eagle Syndicate.',
    itemIds: [
      'tpl_royal_butterfly_24k',
      'tpl_royal_deagle_gold',
      'tpl_royal_velvet_gloves',
      'tpl_royal_karambit_damascus',
      'tpl_royal_ak_monaco',
      'tpl_royal_mp7_cash',
      'tpl_royal_revolver_silver',
      'tpl_royal_dagger_marble',
    ],
    dropRates: {
      Common: 38.0,
      Uncommon: 30.0,
      Rare: 16.0,
      Epic: 9.5,
      Legendary: 4.5,
      Mythic: 1.6,
      'Ultra Rare': 0.32,
      Prestige: 0.08,
    },
  },
  {
    id: 'case_deep_space_quantum',
    name: 'Quantum Fleet & Singularity Case',
    category: 'cyberpunk',
    theme: '🌌 Черные дыры и Пульсары',
    priceCC: 7500,
    rarity: 'Ultra Rare',
    emoji: '🌌',
    gradient: 'from-violet-950 via-indigo-950 to-black',
    accentColor: '#a855f7',
    description: 'Стилет Singularity Event Horizon и пушка Pulsar Stellar.',
    itemIds: [
      'tpl_quantum_void_dagger',
      'tpl_pulsar_heavy_cannon',
      'tpl_space_suit_gloves',
      'tpl_space_sniper_andromeda',
      'tpl_space_ar_meteor',
      'tpl_space_pistol_quantum',
      'tpl_space_smg_lunar',
      'tpl_space_knife_probe',
    ],
    dropRates: {
      Common: 49.0,
      Uncommon: 28.0,
      Rare: 13.0,
      Epic: 6.5,
      Legendary: 2.6,
      Mythic: 0.7,
      'Ultra Rare': 0.17,
      Prestige: 0.03,
    },
  },
  {
    id: 'case_knives_exotic',
    name: 'Exotic Blades & Knives Case',
    category: 'weapons',
    theme: '🗡️ Ножи, Катаны и Клинки',
    priceCC: 15000,
    rarity: 'Prestige',
    emoji: '🗡️',
    gradient: 'from-rose-950 via-purple-950 to-slate-950',
    accentColor: '#fb7185',
    description: 'Только холодное оружие: Катаны, Керамбиты, Балисонги и Косы!',
    itemIds: [
      'tpl_cyber_katana_void',
      'tpl_sakura_scythe_goddess',
      'tpl_draconic_karambit_flame',
      'tpl_royal_butterfly_24k',
      'tpl_quantum_void_dagger',
      'tpl_titanium_exhaust_blade',
      'tpl_tactical_knife_chrome',
      'tpl_royal_dagger_marble',
    ],
    dropRates: {
      Common: 35.0,
      Uncommon: 30.0,
      Rare: 18.0,
      Epic: 10.0,
      Legendary: 5.0,
      Mythic: 1.6,
      'Ultra Rare': 0.33,
      Prestige: 0.07,
    },
  },
  {
    id: 'case_starter_budget',
    name: 'Street Trader Starter Case',
    category: 'new',
    theme: '📦 Доступный Старт',
    priceCC: 1200,
    rarity: 'Rare',
    emoji: '📦',
    gradient: 'from-slate-800 to-slate-950',
    accentColor: '#38bdf8',
    description: 'Идеальный бюджетный кейс для новичков и первых апгрейдов.',
    itemIds: [
      'tpl_sub_pistol_alloy',
      'tpl_anime_knife_bamboo',
      'tpl_dragon_knife_hunting',
      'tpl_mechanic_knife_basic',
      'tpl_combat_rifle_grid',
      'tpl_anime_smg_shonen',
      'tpl_street_drift_pistol',
      'tpl_pulse_smg_tokyo',
    ],
    dropRates: {
      Common: 65.0,
      Uncommon: 24.0,
      Rare: 8.0,
      Epic: 2.4,
      Legendary: 0.5,
      Mythic: 0.08,
      'Ultra Rare': 0.018,
      Prestige: 0.002,
    },
  },
];

// ----------------------------------------------------------------------
// 4. CRAFTING RECIPES (Integrated with Business Empire Factory Resources)
// ----------------------------------------------------------------------

export const CRAFTING_RECIPES: SkinCraftingRecipe[] = [
  {
    id: 'craft_cyber_katana',
    outputTemplateId: 'tpl_cyber_katana_void',
    name: 'Ковка Cyber Katana | Void Shard',
    description: 'Создание легендарной кибер-катаны из титана, электроники и энергетического ядра.',
    tierRequired: 4,
    costCC: 85000,
    requiredMaterials: [
      { resourceName: 'Металлы', quantity: 25, unit: 'т', description: 'Высокопрочная сталь' },
      { resourceName: 'Электроника', quantity: 15, unit: 'комплект', description: 'Микрочипы квантового контура' },
      { resourceName: 'Пластик', quantity: 10, unit: 'т', description: 'Полимерная изоляция' },
    ],
    craftDurationSeconds: 15,
  },
  {
    id: 'craft_car_phantom',
    name: 'Сборка Phantom GT | Genesis',
    outputTemplateId: 'tpl_car_phantom_hypergt',
    description: 'Промышленный синтез кузова гиперкара из автозапчастей и нано-компонентов.',
    tierRequired: 5,
    costCC: 150000,
    requiredMaterials: [
      { resourceName: 'Автозапчасти', quantity: 40, unit: 'комплект', description: 'Двигатель и трансмиссия' },
      { resourceName: 'Электроника', quantity: 30, unit: 'комплект', description: 'Бортовой компьютер' },
      { resourceName: 'Металлы', quantity: 35, unit: 'т', description: 'Каркас из титанового сплава' },
    ],
    craftDurationSeconds: 20,
  },
  {
    id: 'craft_sakura_scythe',
    name: 'Ритуал ковки Celestial Sakura',
    outputTemplateId: 'tpl_sakura_scythe_goddess',
    description: 'Создание оружия жрицы из очищенных металлов и оптических нано-кристаллов.',
    tierRequired: 4,
    costCC: 95000,
    requiredMaterials: [
      { resourceName: 'Металлы', quantity: 20, unit: 'т', description: 'Очищенная сталь' },
      { resourceName: 'Электроника', quantity: 10, unit: 'комплект', description: 'Оптические сенсоры' },
      { resourceName: 'Пластик', quantity: 8, unit: 'т', description: 'Розовый композит' },
    ],
    craftDurationSeconds: 12,
  },
  {
    id: 'craft_royal_butterfly',
    name: 'Ювелирная отливка Balisong 24K',
    outputTemplateId: 'tpl_royal_butterfly_24k',
    description: 'Прецизионная отливка ножа-бабочки из золотого сырья и благородных сплавов.',
    tierRequired: 5,
    costCC: 190000,
    requiredMaterials: [
      { resourceName: 'Металлы', quantity: 50, unit: 'т', description: 'Благородные металлы' },
      { resourceName: 'Электроника', quantity: 20, unit: 'комплект', description: 'Лазерная огранка' },
    ],
    craftDurationSeconds: 25,
  },
  {
    id: 'craft_dragon_lore_awp',
    name: 'Гравировка Titan AWP | Dragon Lore',
    outputTemplateId: 'tpl_dragon_awp_emperor',
    description: 'Императорская штамповка тяжелой винтовки драконьего ордена.',
    tierRequired: 5,
    costCC: 120000,
    requiredMaterials: [
      { resourceName: 'Металлы', quantity: 30, unit: 'т', description: 'Оружейная сталь' },
      { resourceName: 'Электроника', quantity: 25, unit: 'комплект', description: 'Баллистический вычислитель' },
    ],
    craftDurationSeconds: 18,
  },
];

// ----------------------------------------------------------------------
// 5. AI COLLECTOR ARCHETYPES (For dynamic Auctions and Market)
// ----------------------------------------------------------------------

export const AI_COLLECTORS: AiCollector[] = [
  {
    id: 'ai_collector_yamamoto',
    name: 'Kenji Yamamoto',
    avatar: '👨‍💼',
    archetype: 'Collector',
    budgetCC: 1500000,
    preferredCategories: ['Knives', 'Anime', 'Cyberpunk'],
    preferredRarities: ['Legendary', 'Mythic', 'Ultra Rare', 'Prestige'],
    description: 'Охотится за уникальными катанами с редкими паттернами #1 и низким float.',
  },
  {
    id: 'ai_collector_crypto_whale',
    name: 'Satoshi_Whale_0x',
    avatar: '🐋',
    archetype: 'Whale',
    budgetCC: 5000000,
    preferredCategories: ['Luxury', 'Cars', 'Knives'],
    preferredRarities: ['Prestige', 'Ultra Rare'],
    description: 'Крипто-миллиардер. Перебивает любые ставки ради топ-скинов.',
  },
  {
    id: 'ai_trader_vladimir',
    name: 'Vladimir Trader',
    avatar: '📊',
    archetype: 'Trader',
    budgetCC: 800000,
    preferredCategories: ['Weapons', 'Gloves', 'Knives'],
    preferredRarities: ['Rare', 'Epic', 'Legendary'],
    description: 'Покупает лоты ниже рыночной стоимости и перепродает на пике спроса.',
  },
  {
    id: 'ai_investor_elena',
    name: 'Elena Rostova',
    avatar: '👩‍🔬',
    archetype: 'Investor',
    budgetCC: 2200000,
    preferredCategories: ['Cars', 'Luxury', 'Artifacts'],
    preferredRarities: ['Mythic', 'Ultra Rare', 'Prestige'],
    description: 'Долгосрочный инвестор. Скупает целые коллекции для удержания ценности.',
  },
  {
    id: 'ai_casual_mike',
    name: 'Casual_Mike99',
    avatar: '🎮',
    archetype: 'Casual',
    budgetCC: 150000,
    preferredCategories: ['Weapons', 'Anime'],
    preferredRarities: ['Common', 'Uncommon', 'Rare', 'Epic'],
    description: 'Обычный игрок, ищущий красивые и доступные скины для игры.',
  },
];

// ----------------------------------------------------------------------
// 6. SKIN SYSTEM ACHIEVEMENTS
// ----------------------------------------------------------------------

export const SKIN_ACHIEVEMENTS: SkinAchievement[] = [
  {
    id: 'ach_first_case',
    title: 'Первый Анбоксинг',
    description: 'Откройте свой самый первый кейс со скинами.',
    iconEmoji: '🎁',
    rewardCC: 2500,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_first_legendary',
    title: 'Звездный Трофей',
    description: 'Получите свой первый предмет редкости Legendary или выше.',
    iconEmoji: '⭐',
    rewardCC: 15000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_first_prestige',
    title: 'Королевский Дроп ★',
    description: 'Выбейте или скрафтите предмет высшей редкости Prestige!',
    iconEmoji: '👑',
    rewardCC: 100000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_open_100_cases',
    title: 'Кейсовый Маньяк',
    description: 'Откройте суммарно 100 кейсов.',
    iconEmoji: '📦',
    rewardCC: 50000,
    unlocked: false,
    progress: 0,
    maxProgress: 100,
  },
  {
    id: 'ach_open_1000_cases',
    title: 'Император Кейсов',
    description: 'Откройте суммарно 1 000 кейсов.',
    iconEmoji: '🏰',
    rewardCC: 300000,
    unlocked: false,
    progress: 0,
    maxProgress: 1000,
  },
  {
    id: 'ach_contract_master',
    title: 'Мастер Контрактов',
    description: 'Успешно завершите 10 контрактов обмена Trade-Up.',
    iconEmoji: '📜',
    rewardCC: 35000,
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'ach_upgrade_king',
    title: 'Рисковый Апгрейдер',
    description: 'Выиграйте Upgrade с шансом успеха менее 25%.',
    iconEmoji: '⬆️',
    rewardCC: 40000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_complete_collection',
    title: 'Идеальный Коллекционер',
    description: 'Соберите 100% предметов хотя бы одной полной коллекции.',
    iconEmoji: '🏆',
    rewardCC: 150000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_craft_factory',
    title: 'Промышленный Дизайнер',
    description: 'Скрафтите скин с использованием заводских ресурсов холдинга.',
    iconEmoji: '🏭',
    rewardCC: 30000,
    unlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_millionaire_inventory',
    title: 'Скиновый Магнат',
    description: 'Накопите стоимость инвентаря свыше 1 000 000 CC.',
    iconEmoji: '💎',
    rewardCC: 75000,
    unlocked: false,
    progress: 0,
    maxProgress: 1000000,
  },
];
