/**
 * Business Empire: Ultimate
 * Retail Catalog: Store Types, Locations, Equipment Blueprints, Campaigns
 */

import {
  RetailStoreTypeTemplate,
  RetailLocationConfig,
  StoreEquipmentUpgrade,
  MarketingCampaign,
  RetailStoreType,
  LocationType,
} from '../../types/retail';

export const RETAIL_STORE_TEMPLATES: Record<RetailStoreType, RetailStoreTypeTemplate> = {
  kiosk: {
    type: 'kiosk',
    name: 'Торговый киоск / To-Go',
    shortName: 'Киоск',
    description: 'Компактная торговая точка быстрого обслуживания. Кофе, напитки, снэки, табак и пресса. Быстрый запуск, низкие издержки, высокий трафик.',
    icon: 'Store',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    initialSetupCost: 15000,
    baseAreaSqM: 18,
    baseShelvesVolume: 12,
    baseBackroomVolume: 8,
    minEmployees: 2,
    recommendedLocations: ['transit_hub', 'downtown', 'suburb'],
    supportedCategories: ['Продукты', 'Напитки'],
    baseTicketMultiplier: 0.25,
    baseMarginExpected: 65,
  },
  grocery: {
    type: 'grocery',
    name: 'Продуктовый магазин у дома',
    shortName: 'Продуктовый',
    description: 'Классический магазин шаговой доступности. Свежие продукты, напитки, бакалея, молочная и мясная продукция с постоянным спросом.',
    icon: 'Apple',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    initialSetupCost: 55000,
    baseAreaSqM: 95,
    baseShelvesVolume: 75,
    baseBackroomVolume: 45,
    minEmployees: 4,
    recommendedLocations: ['suburb', 'transit_hub', 'downtown'],
    supportedCategories: ['Продукты', 'Напитки'],
    baseTicketMultiplier: 0.6,
    baseMarginExpected: 35,
  },
  clothing: {
    type: 'clothing',
    name: 'Магазин одежды и обуви',
    shortName: 'Одежда и Обувь',
    description: 'Стильный бутик повседневной, деловой и спортивной одежды, обуви и аксессуаров. Высокая торговая наценка и сезонные коллекции.',
    icon: 'Shirt',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    initialSetupCost: 110000,
    baseAreaSqM: 160,
    baseShelvesVolume: 110,
    baseBackroomVolume: 70,
    minEmployees: 5,
    recommendedLocations: ['shopping_mall', 'downtown', 'luxury_quarter'],
    supportedCategories: ['Одежда', 'Обувь'],
    baseTicketMultiplier: 1.8,
    baseMarginExpected: 80,
  },
  electronics: {
    type: 'electronics',
    name: 'Магазин цифровой электроники',
    shortName: 'Электроника',
    description: 'Салон смартфонов, ноутбуков, комплектующих, аудиоустройств и гаджетов. Высокий средний чек и регулярный приток покупателей.',
    icon: 'Laptop',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    initialSetupCost: 220000,
    baseAreaSqM: 220,
    baseShelvesVolume: 140,
    baseBackroomVolume: 90,
    minEmployees: 6,
    recommendedLocations: ['shopping_mall', 'downtown', 'transit_hub'],
    supportedCategories: ['Электроника', 'Смартфоны', 'Компьютеры', 'Комплектующие', 'Бытовая техника'],
    baseTicketMultiplier: 3.5,
    baseMarginExpected: 28,
  },
  furniture: {
    type: 'furniture',
    name: 'Мебельный салон & Интерьер',
    shortName: 'Мебель',
    description: 'Просторный шоурум офисной, жилой и модульной мебели. Требует больших площадей, но генерирует очень крупные единичные чеки.',
    icon: 'Armchair',
    badgeColor: 'bg-amber-600/20 text-amber-300 border-amber-600/30',
    initialSetupCost: 350000,
    baseAreaSqM: 550,
    baseShelvesVolume: 350,
    baseBackroomVolume: 250,
    minEmployees: 7,
    recommendedLocations: ['highway_cluster', 'shopping_mall', 'suburb'],
    supportedCategories: ['Мебель'],
    baseTicketMultiplier: 6.0,
    baseMarginExpected: 50,
  },
  auto_parts: {
    type: 'auto_parts',
    name: 'Магазин автозапчастей & Масел',
    shortName: 'Автозапчасти',
    description: 'Специализированный магазин автокомпонентов, масел, шин, тормозных систем и аксессуаров. Прямая синергия со складами и автосервисом!',
    icon: 'Wrench',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    initialSetupCost: 140000,
    baseAreaSqM: 180,
    baseShelvesVolume: 130,
    baseBackroomVolume: 100,
    minEmployees: 4,
    recommendedLocations: ['highway_cluster', 'suburb', 'transit_hub'],
    supportedCategories: ['Автозапчасти', 'Шины', 'Масла', 'Инструменты'],
    baseTicketMultiplier: 1.6,
    baseMarginExpected: 45,
  },
  supermarket: {
    type: 'supermarket',
    name: 'Сетевой гипер/супермаркет',
    shortName: 'Супермаркет',
    description: 'Масштабный универсальный торговый центр. Мульти-категорийный ассортимент: продукты, напитки, одежда, бытовая техника и товары для дома.',
    icon: 'ShoppingCart',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    initialSetupCost: 650000,
    baseAreaSqM: 850,
    baseShelvesVolume: 600,
    baseBackroomVolume: 450,
    minEmployees: 16,
    recommendedLocations: ['shopping_mall', 'suburb', 'highway_cluster'],
    supportedCategories: ['Продукты', 'Напитки', 'Одежда', 'Бытовая техника', 'Инструменты'],
    baseTicketMultiplier: 1.4,
    baseMarginExpected: 30,
  },
  premium_store: {
    type: 'premium_store',
    name: 'Флагманский премиум-бутик',
    shortName: 'Премиум Бутик',
    description: 'Эксклюзивный флагманский бутик люксовых брендов, премиального вина, дизайнерской одежды, ювелирных изделий и топовых девайсов.',
    icon: 'Sparkles',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    initialSetupCost: 950000,
    baseAreaSqM: 280,
    baseShelvesVolume: 160,
    baseBackroomVolume: 90,
    minEmployees: 8,
    recommendedLocations: ['luxury_quarter', 'downtown'],
    supportedCategories: ['Продукты', 'Напитки', 'Одежда', 'Обувь', 'Смартфоны', 'Электроника'],
    baseTicketMultiplier: 8.5,
    baseMarginExpected: 120,
  },
};

export const RETAIL_LOCATIONS: Record<LocationType, RetailLocationConfig> = {
  suburb: {
    id: 'suburb',
    name: 'Спальный микрорайон',
    description: 'Густонаселенный спальный район с молодыми семьями. Высокий стабильный спрос на базовые продукты и услуги, низкая стоимость аренды.',
    baseFootTraffic: 2400,
    rentPerSqMeter: 1.2, // $1.20 per sq.m / day
    incomeLevel: 'medium',
    demographics: {
      budgetShare: 0.45,
      standardShare: 0.45,
      premiumShare: 0.09,
      luxuryShare: 0.01,
    },
    preferredCategories: ['Продукты', 'Напитки', 'Одежда', 'Автозапчасти'],
  },
  transit_hub: {
    id: 'transit_hub',
    name: 'Транспортный хаб / Метро',
    description: 'Оживленный пересадочный узел у станции метро и вокзала. Огромный поток спешащих пешеходов, идеален для киосков и формата Grab&Go.',
    baseFootTraffic: 7500,
    rentPerSqMeter: 2.8,
    incomeLevel: 'medium',
    demographics: {
      budgetShare: 0.40,
      standardShare: 0.50,
      premiumShare: 0.08,
      luxuryShare: 0.02,
    },
    preferredCategories: ['Продукты', 'Напитки', 'Смартфоны'],
  },
  downtown: {
    id: 'downtown',
    name: 'Деловой центр (Downtown)',
    description: 'Центральный деловой район небоскребов и бизнес-центров. Платежеспособные офисные сотрудники, высокий чек в обед и вечерние часы.',
    baseFootTraffic: 5200,
    rentPerSqMeter: 3.5,
    incomeLevel: 'high',
    demographics: {
      budgetShare: 0.15,
      standardShare: 0.45,
      premiumShare: 0.32,
      luxuryShare: 0.08,
    },
    preferredCategories: ['Одежда', 'Электроника', 'Смартфоны', 'Напитки', 'Продукты'],
  },
  shopping_mall: {
    id: 'shopping_mall',
    name: 'Крупный Торговый Центр',
    description: 'Популярный молл с фудкортом и кинотеатром. Посетители приходят с целевым намерением совершать покупки одежды, гаджетов и обуви.',
    baseFootTraffic: 6200,
    rentPerSqMeter: 4.2,
    incomeLevel: 'high',
    demographics: {
      budgetShare: 0.20,
      standardShare: 0.50,
      premiumShare: 0.25,
      luxuryShare: 0.05,
    },
    preferredCategories: ['Одежда', 'Обувь', 'Электроника', 'Смартфоны', 'Бытовая техника'],
  },
  luxury_quarter: {
    id: 'luxury_quarter',
    name: 'Премиум Квартал & Авеню',
    description: 'Историческая главная авеню с бутиками и элитными резиденциями. Состоятельные клиенты, нечувствительные к высоким ценам, но ценящие сервис.',
    baseFootTraffic: 1900,
    rentPerSqMeter: 6.8,
    incomeLevel: 'luxury',
    demographics: {
      budgetShare: 0.02,
      standardShare: 0.15,
      premiumShare: 0.48,
      luxuryShare: 0.35,
    },
    preferredCategories: ['Одежда', 'Обувь', 'Смартфоны', 'Напитки'],
  },
  highway_cluster: {
    id: 'highway_cluster',
    name: 'Пригородный ритейл-парк у шоссе',
    description: 'Торговый кластер вдоль крупной автострады с гигантской парковкой. Идеальное место для мебельных гипермаркетов, автозапчастей и стройматериалов.',
    baseFootTraffic: 3100,
    rentPerSqMeter: 1.0,
    incomeLevel: 'medium',
    demographics: {
      budgetShare: 0.35,
      standardShare: 0.50,
      premiumShare: 0.13,
      luxuryShare: 0.02,
    },
    preferredCategories: ['Мебель', 'Автозапчасти', 'Инструменты', 'Бытовая техника'],
  },
};

export const INITIAL_EQUIPMENT_BLUEPRINTS: StoreEquipmentUpgrade[] = [
  {
    id: 'equip_pos',
    name: 'Кассовые терминалы и самообслуживание',
    category: 'pos',
    level: 1,
    maxLevel: 5,
    currentLevel: 1,
    cost: 4500,
    dailyElectricityCost: 8,
    benefitsDescription: 'Ускоряет обслуживание на кассах, ликвидирует очереди и повышает удовлетворенность.',
    conversionBonus: 3,
    serviceSpeedBonus: 20,
    shrinkageReduction: 0,
    spoilageReduction: 0,
  },
  {
    id: 'equip_refrigeration',
    name: 'Климатические & Холодильные витрины',
    category: 'refrigeration',
    level: 1,
    maxLevel: 5,
    currentLevel: 1,
    cost: 8000,
    dailyElectricityCost: 18,
    benefitsDescription: 'Сохраняет свежесть продуктов и напитков, снижает списание товаров по браку и порче.',
    conversionBonus: 2,
    serviceSpeedBonus: 0,
    shrinkageReduction: 0,
    spoilageReduction: 30,
  },
  {
    id: 'equip_interior',
    name: 'Дизайнерский интерьер & Акцентное освещение',
    category: 'interior',
    level: 1,
    maxLevel: 5,
    currentLevel: 1,
    cost: 12000,
    dailyElectricityCost: 12,
    benefitsDescription: 'Создает премиальную атмосферу шопинга, повышает конверсию и лояльность клиентов.',
    conversionBonus: 6,
    serviceSpeedBonus: 0,
    shrinkageReduction: 0,
    spoilageReduction: 0,
  },
  {
    id: 'equip_security',
    name: 'Система видеонаблюдения & Антикражные рамки',
    category: 'security',
    level: 1,
    maxLevel: 5,
    currentLevel: 1,
    cost: 6500,
    dailyElectricityCost: 5,
    benefitsDescription: 'Защищает магазин от краж покупателей и недобросовестного персонала.',
    conversionBonus: 0,
    serviceSpeedBonus: 0,
    shrinkageReduction: 45,
    spoilageReduction: 0,
  },
  {
    id: 'equip_logistics',
    name: 'Smart-Склад & RFID сканеры полок',
    category: 'logistics',
    level: 1,
    maxLevel: 5,
    currentLevel: 1,
    cost: 10500,
    dailyElectricityCost: 10,
    benefitsDescription: 'Оптимизирует выкладку товаров и автоматизирует учет остатков на складе магазина.',
    conversionBonus: 4,
    serviceSpeedBonus: 15,
    shrinkageReduction: 15,
    spoilageReduction: 10,
  },
];

export const MARKETING_CAMPAIGNS_CATALOG: MarketingCampaign[] = [
  {
    id: 'camp_flyers',
    name: 'Раздача промо-листовок у метро и ТЦ',
    description: 'Локальные промоутеры привлекают ближайших прохожих скидочными купонами.',
    costDaily: 85,
    trafficBoostPercent: 15,
    reputationBoostDaily: 0.1,
    conversionBoostPercent: 2,
    active: false,
    minStoreLevel: 1,
  },
  {
    id: 'camp_social',
    name: 'Таргетированная реклама в соцсетях & Картах',
    description: 'Гео-таргетинг на жителей района в мобильных приложениях и навигаторах.',
    costDaily: 240,
    trafficBoostPercent: 35,
    reputationBoostDaily: 0.25,
    conversionBoostPercent: 5,
    active: false,
    minStoreLevel: 2,
  },
  {
    id: 'camp_billboards',
    name: 'Городские билборды & Медиафасады',
    description: 'Яркие рекламные щиты на ключевых перекрестках и магистралях города.',
    costDaily: 600,
    trafficBoostPercent: 65,
    reputationBoostDaily: 0.6,
    conversionBoostPercent: 8,
    active: false,
    minStoreLevel: 3,
  },
  {
    id: 'camp_influencers',
    name: 'Коллаборации с популярными блогерами',
    description: 'Обзоры магазина инфлюенсерами, распаковки покупок и вирусные сторис.',
    costDaily: 1400,
    trafficBoostPercent: 110,
    reputationBoostDaily: 1.2,
    conversionBoostPercent: 14,
    active: false,
    minStoreLevel: 4,
  },
  {
    id: 'camp_tv_radio',
    name: 'Федеральная реклама на ТВ и радио',
    description: 'Массированный охват многомиллионной аудитории, превращающий магазин в национальный бренд.',
    costDaily: 3500,
    trafficBoostPercent: 220,
    reputationBoostDaily: 2.5,
    conversionBoostPercent: 22,
    active: false,
    minStoreLevel: 5,
  },
];

export const FIRST_NAMES = [
  'Алексей', 'Дмитрий', 'Сергей', 'Максим', 'Иван', 'Артем', 'Михаил', 'Кирилл',
  'Анна', 'Елена', 'Ольга', 'Мария', 'Екатерина', 'София', 'Виктория', 'Полина',
  'Владимир', 'Павел', 'Денис', 'Тимофей', 'Алина', 'Дарья', 'Валерия', 'Ксения'
];

export const LAST_NAMES = [
  'Иванов', 'Смирнов', 'Кузнецов', 'Попов', 'Васильев', 'Петров', 'Соколов', 'Михайлов',
  'Новиков', 'Федоров', 'Морозов', 'Волков', 'Алексеев', 'Лебедев', 'Семенов', 'Егоров',
  'Павлов', 'Козлов', 'Степанов', 'Николаев', 'Орлов', 'Андреев', 'Макаров', 'Никитин'
];

export function generateRandomEmployeeName(): string {
  const first = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
  const last = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
  return `${first} ${last}`;
}
