/**
 * Business Empire: Ultimate
 * Real Estate Catalog & Upgrade Configuration
 */

import { RealEstateCatalogItem, RealEstateUpgradeTier, RealEstateType } from '../../types/realEstate';

export const REAL_ESTATE_TYPES_META: Record<
  RealEstateType,
  { title: string; iconEmoji: string; description: string; badgeBg: string }
> = {
  apartment: {
    title: 'Квартиры',
    iconEmoji: '🏢',
    description: 'Городское жилье с высокой ликвидностью и стабильным спросом арендаторов',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  },
  house: {
    title: 'Дома и Коттеджи',
    iconEmoji: '🏡',
    description: 'Загородная жилая недвижимость и премиальные резиденции',
    badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  },
  office: {
    title: 'Офисы и Бизнес-центры',
    iconEmoji: '🏛️',
    description: 'Корпоративные площади, представительские башни и коворкинги',
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
  },
  shop: {
    title: 'Магазины и Стрит-ритейл',
    iconEmoji: '🏪',
    description: 'Торговые помещения с максимальным пешеходным трафиком',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  },
  warehouse: {
    title: 'Склады и Хабы',
    iconEmoji: '📦',
    description: 'Промышленные логистические комплексы и распределительные центры',
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
  },
  mall: {
    title: 'Торговые Центры',
    iconEmoji: '🏬',
    description: 'Крупноформатные моллы с пулом сотен сетевых арендаторов',
    badgeBg: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  },
  factory: {
    title: 'Заводы и Промбазы',
    iconEmoji: '🏭',
    description: 'Индустриальные объекты с колоссальной капитальной стоимостью',
    badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
  },
};

export const REAL_ESTATE_CATALOG: RealEstateCatalogItem[] = [
  // 1. APARTMENTS (Квартиры)
  {
    id: 'prop_apt_studio',
    name: 'Студия в Спальном районе',
    type: 'apartment',
    location: 'Спальный Район «Северный»',
    districtId: 'residential_area',
    basePrice: 55000,
    baseRentDaily: 65,
    baseMaintenanceDaily: 12,
    baseOccupancy: 88,
    perks: ['Быстрый спрос', 'Рядом метро'],
    description: 'Компактная квартира-студия с чистовой отделкой. Идеальный выбор для стабильного арендного потока.',
    imageEmoji: '🏢',
  },
  {
    id: 'prop_apt_business',
    name: 'Бизнес-апартаменты в Сити',
    type: 'apartment',
    location: 'Деловой Центр «Moscow-City»',
    districtId: 'business_district',
    basePrice: 220000,
    baseRentDaily: 240,
    baseMaintenanceDaily: 42,
    baseOccupancy: 92,
    perks: ['Панорамный вид', 'Консьерж-сервис 24/7', 'Класс А'],
    description: 'Современные апартаменты в небоскребе. Высокий спрос среди топ-менеджеров и экспатов.',
    imageEmoji: '🌆',
  },
  {
    id: 'prop_apt_penthouse',
    name: 'Видовой Пентхаус на Набережной',
    type: 'apartment',
    location: 'Историческая Набережная',
    districtId: 'city_center',
    basePrice: 750000,
    baseRentDaily: 780,
    baseMaintenanceDaily: 120,
    baseOccupancy: 85,
    perks: ['Собственная терраса', 'Личный лифт', 'Премиум дизайн'],
    description: 'Двухуровневый пентхаус с авторским ремонтом и панорамным видом на всю акваторию города.',
    imageEmoji: '✨',
  },
  {
    id: 'prop_apt_luxury_club',
    name: 'Резиденция в Клубном доме',
    type: 'apartment',
    location: 'Золотая Миля',
    districtId: 'elite_suburb',
    basePrice: 1650000,
    baseRentDaily: 1650,
    baseMaintenanceDaily: 240,
    baseOccupancy: 95,
    perks: ['Закрытая территория', 'СПА-комплекс', 'Винный погреб'],
    description: 'Эксклюзивное жилье ультра-премиум класса для дипломатов и миллиардеров.',
    imageEmoji: '👑',
  },

  // 2. HOUSES (Дома и Коттеджи)
  {
    id: 'prop_house_townhouse',
    name: 'Таунхаус в Зеленом пригороде',
    type: 'house',
    location: 'Пригородный Поселок «Гринвуд»',
    districtId: 'residential_area',
    basePrice: 140000,
    baseRentDaily: 155,
    baseMaintenanceDaily: 28,
    baseOccupancy: 86,
    perks: ['Личный дворик', 'Гараж на 2 авто', 'Экологичный район'],
    description: 'Семейный таунхаус с автономным отоплением и собственным садом.',
    imageEmoji: '🏡',
  },
  {
    id: 'prop_house_cottage',
    name: 'Коттедж в Озерном поселке',
    type: 'house',
    location: 'Озерная Долина',
    districtId: 'elite_suburb',
    basePrice: 420000,
    baseRentDaily: 440,
    baseMaintenanceDaily: 70,
    baseOccupancy: 90,
    perks: ['Береговая линия', 'Баня и барбекю', 'Охрана'],
    description: 'Просторный кирпичный коттедж на берегу живописного озера.',
    imageEmoji: '🌳',
  },
  {
    id: 'prop_house_residence',
    name: 'Загородная Резиденция с бассейном',
    type: 'house',
    location: 'Рублевское Шоссе',
    districtId: 'elite_suburb',
    basePrice: 1450000,
    baseRentDaily: 1480,
    baseMaintenanceDaily: 210,
    baseOccupancy: 88,
    perks: ['Крытый бассейн', 'Вертолетная площадка', 'Гостевой дом'],
    description: 'Монументальная вилла с парковой зоной, ландшафтным дизайном и системой безопасности.',
    imageEmoji: '🏰',
  },
  {
    id: 'prop_house_riviera',
    name: 'Поместье «Морская Ривьера»',
    type: 'house',
    location: 'Лазурный Берег',
    districtId: 'elite_suburb',
    basePrice: 4200000,
    baseRentDaily: 4100,
    baseMaintenanceDaily: 550,
    baseOccupancy: 92,
    perks: ['Частный причал для яхты', 'Теннисный корт', 'Пляж'],
    description: 'Королевское поместье с частной береговой линией для глобальной элиты.',
    imageEmoji: '🏖️',
  },

  // 3. OFFICES (Офисы)
  {
    id: 'prop_office_openspace',
    name: 'Офис Open-Space в Технопарке',
    type: 'office',
    location: 'Технопарк «Инновация»',
    districtId: 'commercial_avenue',
    basePrice: 280000,
    baseRentDaily: 310,
    baseMaintenanceDaily: 50,
    baseOccupancy: 90,
    perks: ['Высокоскоростной интернет', 'Переговорные комнаты', 'Кафетерий'],
    description: 'Стильное рабочее пространство для IT-стартапов и digital-агентств.',
    imageEmoji: '💻',
  },
  {
    id: 'prop_office_floor',
    name: 'Представительский этаж в Сити',
    type: 'office',
    location: 'Деловой Центр «Башня Федерация»',
    districtId: 'business_district',
    basePrice: 1100000,
    baseRentDaily: 1200,
    baseMaintenanceDaily: 180,
    baseOccupancy: 94,
    perks: ['VIP-вход', 'Серверная комната', 'Сертификат BREEAM'],
    description: 'Целый этаж 850 кв.м с премиальной отделкой под штаб-квартиру корпорации.',
    imageEmoji: '🏛️',
  },
  {
    id: 'prop_office_center',
    name: 'Бизнес-центр «Crown Plaza» Класса А',
    type: 'office',
    location: 'Финансовый Квартал',
    districtId: 'business_district',
    basePrice: 3900000,
    baseRentDaily: 4100,
    baseMaintenanceDaily: 580,
    baseOccupancy: 92,
    perks: ['Подземный паркинг 200 мест', 'Ресторанный дворик', 'Служба клининга'],
    description: 'Десятиэтажный бизнес-центр с пулом якорных банковских арендаторов.',
    imageEmoji: '🏢',
  },
  {
    id: 'prop_office_district',
    name: 'Международный Деловой Квартал',
    type: 'office',
    location: 'Центральный Международный Район',
    districtId: 'city_center',
    basePrice: 13500000,
    baseRentDaily: 13800,
    baseMaintenanceDaily: 1900,
    baseOccupancy: 96,
    perks: ['Инфраструктурная монополия', 'Конференц-холл', 'Собственная ТЭЦ'],
    description: 'Масштабный комплекс из трех башен с транснациональными корпорациями в качестве арендаторов.',
    imageEmoji: '🌐',
  },

  // 4. SHOPS (Магазины)
  {
    id: 'prop_shop_street',
    name: 'Стрит-ритейл на Центральной улице',
    type: 'shop',
    location: 'Улица Арбат',
    districtId: 'city_center',
    basePrice: 160000,
    baseRentDaily: 185,
    baseMaintenanceDaily: 25,
    baseOccupancy: 94,
    perks: ['Плотный пешеходный трафик', 'Витринные окна', '1-я линия'],
    description: 'Помещение свободного назначения под кофейню, пекарню или брендовый бутик.',
    imageEmoji: '☕',
  },
  {
    id: 'prop_shop_boutique',
    name: 'Флагманский Бутик Люкс-одежды',
    type: 'shop',
    location: 'Торговый Проспект «Кузнецкий Мост»',
    districtId: 'commercial_avenue',
    basePrice: 520000,
    baseRentDaily: 580,
    baseMaintenanceDaily: 80,
    baseOccupancy: 91,
    perks: ['Престижная локация', 'Дизайнерский фасад', 'Высокие чеки'],
    description: 'Премиальный ритейл-объект в центре модной жизни столицы.',
    imageEmoji: '👗',
  },
  {
    id: 'prop_shop_supermarket',
    name: 'Торговое здание под Супермаркет',
    type: 'shop',
    location: 'Перекресток Магистрали',
    districtId: 'residential_area',
    basePrice: 1250000,
    baseRentDaily: 1320,
    baseMaintenanceDaily: 170,
    baseOccupancy: 98,
    perks: ['Долгосрочный договор 10 лет', 'Зона разгрузки фур', 'Парковка'],
    description: 'Капитальное здание с якорным федеральным продуктовым ритейлером.',
    imageEmoji: '🛒',
  },
  {
    id: 'prop_shop_gallery',
    name: 'Торговая Галерея на Проспекте',
    type: 'shop',
    location: 'Проспект Мира',
    districtId: 'commercial_avenue',
    basePrice: 2900000,
    baseRentDaily: 3050,
    baseMaintenanceDaily: 410,
    baseOccupancy: 93,
    perks: ['35 торговых секций', 'Фуд-корт', 'Высокая конверсия'],
    description: 'Двухэтажная торговая галерея с устойчивым потоком покупателей.',
    imageEmoji: '🛍️',
  },

  // 5. WAREHOUSES (Склады)
  {
    id: 'prop_wh_class_b',
    name: 'Логистический ангар Класса B',
    type: 'warehouse',
    location: 'Промзона «Южные Ворота»',
    districtId: 'logistics_hub',
    basePrice: 210000,
    baseRentDaily: 230,
    baseMaintenanceDaily: 35,
    baseOccupancy: 89,
    perks: ['Антипылевые полы', 'Удобный выезд на МКАД', 'Кран-балка'],
    description: 'Сухой отапливаемый склад 1500 кв.м с автомобильной рампой.',
    imageEmoji: '📦',
  },
  {
    id: 'prop_wh_class_a',
    name: 'Распределительный Терминал Класса A',
    type: 'warehouse',
    location: 'Трасса М-11',
    districtId: 'logistics_hub',
    basePrice: 850000,
    baseRentDaily: 920,
    baseMaintenanceDaily: 130,
    baseOccupancy: 95,
    perks: ['WMS автоматизация', 'Доки с доквеллерами', 'Высота потолков 14м'],
    description: 'Современный высокостеллажный хаб с климатическим контролем.',
    imageEmoji: '🚛',
  },
  {
    id: 'prop_wh_multimodal',
    name: 'Мультимодальный Складской Хаб',
    type: 'warehouse',
    location: 'Транспортный Узел «Северный Экспресс»',
    districtId: 'logistics_hub',
    basePrice: 3100000,
    baseRentDaily: 3300,
    baseMaintenanceDaily: 460,
    baseOccupancy: 96,
    perks: ['Ж/Д тупик на территории', 'Таможенный пост', 'Кросс-докинг'],
    description: 'Опорный логистический центр с прямым выходом на железнодорожные пути.',
    imageEmoji: '🚂',
  },
  {
    id: 'prop_wh_megacluster',
    name: 'Мега-кластер автоматизированной логистики',
    type: 'warehouse',
    location: 'Центральный Логистический Парк',
    districtId: 'logistics_hub',
    basePrice: 9500000,
    baseRentDaily: 10200,
    baseMaintenanceDaily: 1350,
    baseOccupancy: 99,
    perks: ['Роботизированная сортировка', 'Автопарк электрофур', 'Контракт с маркетплейсами'],
    description: 'Флагманский распределительный гигант площадью 65,000 кв.м.',
    imageEmoji: '🤖',
  },

  // 6. MALLS (Торговые Центры)
  {
    id: 'prop_mall_district',
    name: 'Районный ТРК «Квартал Молл»',
    type: 'mall',
    location: 'Густонаселенный Район «Юго-Запад»',
    districtId: 'residential_area',
    basePrice: 2500000,
    baseRentDaily: 2700,
    baseMaintenanceDaily: 380,
    baseOccupancy: 91,
    perks: ['Кинотеатр 6 залов', 'Детский развлекательный центр', 'Паркинг'],
    description: 'Любимое место шопинга и семейного досуга для 150 000 жителей района.',
    imageEmoji: '🏬',
  },
  {
    id: 'prop_mall_megamall',
    name: 'Мегамолл «Oceania Grand» с Аквапарком',
    type: 'mall',
    location: 'Пересечение Скоростных Хорд',
    districtId: 'commercial_avenue',
    basePrice: 9800000,
    baseRentDaily: 10500,
    baseMaintenanceDaily: 1420,
    baseOccupancy: 94,
    perks: ['Крытый Аквапарк', 'Ледовая арена', '220 магазинов'],
    description: 'Региональный гигант притяжения с огромным трафиком выходного дня.',
    imageEmoji: '🌊',
  },
  {
    id: 'prop_mall_metropolis',
    name: 'Флагманский Премиум-Молл «Metropolis Plaza»',
    type: 'mall',
    location: 'Центральный Проспект',
    districtId: 'city_center',
    basePrice: 26500000,
    baseRentDaily: 28500,
    baseMaintenanceDaily: 3800,
    baseOccupancy: 97,
    perks: ['Мировые люкс-бренды', 'Рестораны Мишлен', 'Сверхприбыли'],
    description: 'Самый престижный молл страны с максимальной доходностью на квадратный метр.',
    imageEmoji: '💎',
  },

  // 7. FACTORIES (Заводы)
  {
    id: 'prop_factory_metal',
    name: 'Металлообрабатывающий завод',
    type: 'factory',
    location: 'Индустриальная Зона «Промсталь»',
    districtId: 'industrial_zone',
    basePrice: 950000,
    baseRentDaily: 1050,
    baseMaintenanceDaily: 160,
    baseOccupancy: 90,
    perks: ['Литейные печи', 'Подстанция 10 МВт', 'Подъездные пути'],
    description: 'Действующий производственный комплекс с лицензией на металлообработку.',
    imageEmoji: '⚙️',
  },
  {
    id: 'prop_factory_automotive',
    name: 'Автосборочный завод полного цикла',
    type: 'factory',
    location: 'Автокластер «Моторс»',
    districtId: 'industrial_zone',
    basePrice: 4600000,
    baseRentDaily: 4900,
    baseMaintenanceDaily: 720,
    baseOccupancy: 93,
    perks: ['Роботизированная сварка', 'Окрасочный цех KUKA', 'Испытательный полигон'],
    description: 'Индустриальный завод с конвейерной линией сборки 50,000 авто в год.',
    imageEmoji: '🚗',
  },
  {
    id: 'prop_factory_pharma',
    name: 'Фармацевтический биотех-комбинат',
    type: 'factory',
    location: 'Биофарм Кластер «Медицина Будущего»',
    districtId: 'industrial_zone',
    basePrice: 10800000,
    baseRentDaily: 11400,
    baseMaintenanceDaily: 1550,
    baseOccupancy: 96,
    perks: ['Чистые комнаты GMP', 'R&D лаборатории', 'Госзаказы'],
    description: 'Стерильное фармацевтическое производство с международной сертификацией.',
    imageEmoji: '🧬',
  },
  {
    id: 'prop_factory_gigafactory',
    name: 'Высокотехнологичный Gigafactory комплекс',
    type: 'factory',
    location: 'Особая Экономическая Зона',
    districtId: 'industrial_zone',
    basePrice: 32000000,
    baseRentDaily: 34500,
    baseMaintenanceDaily: 4500,
    baseOccupancy: 99,
    perks: ['Производство литий-ионных батарей', '100% зеленая энергия', 'Налоговые льготы ОЭЗ'],
    description: 'Вершина индустриальной мощи. Колоссальная генерация дивидендов и арендных выплат.',
    imageEmoji: '🔋',
  },
];

export const UPGRADE_TIERS: RealEstateUpgradeTier[] = [
  {
    level: 1,
    name: 'Базовое состояние',
    costMultiplier: 0,
    valueBonusMultiplier: 0,
    rentBonusMultiplier: 0,
    maintenanceReduction: 0,
    occupancyBonus: 0,
    description: 'Стандартная чистовая отделка без улучшений.',
  },
  {
    level: 2,
    name: 'Евроремонт и Smart-технологии',
    costMultiplier: 0.18, // 18% от стоимости
    valueBonusMultiplier: 0.28, // +28% к рыночной цене
    rentBonusMultiplier: 0.32, // +32% к аренде
    maintenanceReduction: 0.08, // -8% издержки
    occupancyBonus: 5, // +5% заполняемость
    description: 'Качественные материалы, система «Умный дом», энергосберегающие стеклопакеты и светодиоды.',
  },
  {
    level: 3,
    name: 'Премиум-инфраструктура и Охрана',
    costMultiplier: 0.24,
    valueBonusMultiplier: 0.38,
    rentBonusMultiplier: 0.42,
    maintenanceReduction: 0.15,
    occupancyBonus: 8,
    description: 'Круглосуточный пост охраны, биометрический контроль доступа, дизайнерская отделка холлов.',
  },
  {
    level: 4,
    name: 'Эко-энергетика и Солнечные батареи',
    costMultiplier: 0.32,
    valueBonusMultiplier: 0.48,
    rentBonusMultiplier: 0.55,
    maintenanceReduction: 0.25,
    occupancyBonus: 10,
    description: 'Автономная генерация электроэнергии, тепловые насосы, фильтрация воздуха и сертификация LEED.',
  },
  {
    level: 5,
    name: 'Люкс-статус и VIP-сервис',
    costMultiplier: 0.45,
    valueBonusMultiplier: 0.65,
    rentBonusMultiplier: 0.75,
    maintenanceReduction: 0.35,
    occupancyBonus: 15,
    description: 'Вершина капитализации. Консьерж-сервис мирового уровня, 100% гарантированная заполняемость.',
  },
];
