/**
 * Business Empire: Ultimate
 * Real Esports Disciplines Catalog
 * Includes all 27 requested authentic disciplines:
 * - 11 Mobile Esports (Standoff 2, MLBB, Honor of Kings, Arena of Valor, Free Fire, Clash Royale, Brawl Stars, PUBG Mobile, BGMI, CoD: Mobile, Garena Free Fire)
 * - 10 PC Esports (CS2, Dota 2, League of Legends, VALORANT, R6 Siege, Apex Legends, StarCraft II, Overwatch 2, Rocket League, Deadlock)
 * - 6 Cross-platform & Web Esports (Hearthstone, TFT, Wild Rift, Fortnite, Chess.com, Lichess)
 */

import { DisciplineId, DisciplineInfo } from '../../types/esports';

export const ESPORTS_DISCIPLINES: Record<DisciplineId, DisciplineInfo> = {
  // =========================================================================
  // 📱 МОБИЛЬНЫЙ КИБЕРСПОРТ (iOS / Android)
  // =========================================================================
  standoff_2: {
    id: 'standoff_2',
    name: 'Standoff 2',
    platform: 'Mobile',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 89,
    avgViewers: 340000,
    peakViewers: 1100000,
    prizePoolScale: 1500000,
    proTeamsCount: 120,
    rating: 88,
    tournamentsCount: 16,
    currentSeason: 'Season 8: Major League',
    iconEmoji: '🔫',
    themeColor: 'from-amber-500 to-orange-600',
    roles: ['Entry Fragger', 'Sniper (AWP)', 'In-Game Leader (IGL)', 'Support', 'Lurker'],
    keyAttributes: ['Aim', 'Reaction', 'Utility', 'Positioning', 'Game Sense', 'Teamwork'],
    description: 'Ведущий тактический мобильный 3D-шутер с соревновательной экономикой раундов, гранатами и плентами.',
  },

  mlbb: {
    id: 'mlbb',
    name: 'Mobile Legends: Bang Bang',
    platform: 'Mobile',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 99,
    avgViewers: 1350000,
    peakViewers: 5400000,
    prizePoolScale: 4000000,
    proTeamsCount: 240,
    rating: 98,
    tournamentsCount: 28,
    currentSeason: 'M6 World Championship Circuit',
    iconEmoji: '⚔️',
    themeColor: 'from-blue-600 to-indigo-700',
    roles: ['Gold Laner (Marksman)', 'Mid Laner (Mage)', 'EXP Laner (Fighter)', 'Jungler (Assassin)', 'Roamer (Tank/Support)'],
    keyAttributes: ['Mechanics', 'Map Awareness', 'Farming', 'Decision Making', 'Teamfight', 'Drafting'],
    description: 'Глобальный феномен мобильных MOBA с миллионными стадионами в Азии и Латинской Америке.',
  },

  honor_of_kings: {
    id: 'honor_of_kings',
    name: 'Honor of Kings',
    platform: 'Mobile',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 97,
    avgViewers: 950000,
    peakViewers: 4200000,
    prizePoolScale: 10000000,
    proTeamsCount: 180,
    rating: 96,
    tournamentsCount: 22,
    currentSeason: 'KIC 2026 World Cup',
    iconEmoji: '👑',
    themeColor: 'from-amber-400 to-yellow-600',
    roles: ['Clash Lane', 'Mid Lane', 'Farm Lane', 'Jungler', 'Support/Roam'],
    keyAttributes: ['Mechanics', 'Map Awareness', 'Macro Strategy', 'Fast Reflexes', 'Drafting', 'Teamwork'],
    description: 'Самая кассовая мобильная MOBA в истории с рекордными призовыми фондами KIC World Championship.',
  },

  arena_of_valor: {
    id: 'arena_of_valor',
    name: 'Arena of Valor',
    platform: 'Mobile',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 84,
    avgViewers: 420000,
    peakViewers: 1750000,
    prizePoolScale: 2000000,
    proTeamsCount: 95,
    rating: 83,
    tournamentsCount: 14,
    currentSeason: 'AIC International Championship',
    iconEmoji: '🛡️',
    themeColor: 'from-sky-500 to-blue-700',
    roles: ['Dragon Lane', 'Dark Slayer Lane', 'Mid Lane', 'Jungle', 'Abyssal Support'],
    keyAttributes: ['Mechanics', 'Map Awareness', 'Positioning', 'Teamfight', 'Decision Making'],
    description: 'Международная соревновательная MOBA с быстрыми таймингами и развитой сценой в ЮВА.',
  },

  free_fire: {
    id: 'free_fire',
    name: 'Free Fire',
    platform: 'Mobile',
    genre: 'Battle Royale',
    teamFormat: 'Squads (4v4)',
    rosterSize: 4,
    popularity: 95,
    avgViewers: 890000,
    peakViewers: 4600000,
    prizePoolScale: 2500000,
    proTeamsCount: 190,
    rating: 93,
    tournamentsCount: 20,
    currentSeason: 'FFWS World Series',
    iconEmoji: '🔥',
    themeColor: 'from-orange-500 to-red-600',
    roles: ['Captain / IGL', 'Rusher / Fragger', 'Sniper', 'Support / Grenadier'],
    keyAttributes: ['Aim', 'Movement', 'Gloo Wall Speed', 'Zone Rotation', 'Reaction', 'Teamwork'],
    description: 'Динамичный мобильный Battle Royale с молниеносной установкой стен и рекордной фан-базой.',
  },

  clash_royale: {
    id: 'clash_royale',
    name: 'Clash Royale',
    platform: 'Mobile',
    genre: 'Strategy/RTS',
    teamFormat: '1v1 (Dueling)',
    rosterSize: 2, // Starter + Sub
    popularity: 82,
    avgViewers: 190000,
    peakViewers: 680000,
    prizePoolScale: 1000000,
    proTeamsCount: 65,
    rating: 81,
    tournamentsCount: 12,
    currentSeason: 'CRL World Finals Season 2026',
    iconEmoji: '🏰',
    themeColor: 'from-blue-500 to-sky-600',
    roles: ['Solo Duelist', 'Deck Specialist'],
    keyAttributes: ['Elixir Tracking', 'Card Placement', 'Reaction', 'Drafting', 'Deck Building', 'Prediction'],
    description: 'Тактическая карточная дуэль в реальном времени с подсчетом эликсира и микроконтролем таймингов.',
  },

  brawl_stars: {
    id: 'brawl_stars',
    name: 'Brawl Stars',
    platform: 'Mobile',
    genre: 'Sports/Arcade',
    teamFormat: '3v3',
    rosterSize: 3,
    popularity: 93,
    avgViewers: 410000,
    peakViewers: 1550000,
    prizePoolScale: 1800000,
    proTeamsCount: 130,
    rating: 91,
    tournamentsCount: 18,
    currentSeason: 'BSC World Finals & Monthly Finals',
    iconEmoji: '⭐',
    themeColor: 'from-yellow-400 to-amber-600',
    roles: ['Mid / Gem Carrier', 'Aggro / Lane Pusher', 'Support / Controller'],
    keyAttributes: ['Aim', 'Movement', 'Map Knowledge', 'Reaction', 'Teamwork', 'Draft Strategy'],
    description: 'Взрывной командный экшен 3v3 с разнообразными режимами (Brawl Ball, Gem Grab, Heist, Knockout).',
  },

  pubg_mobile: {
    id: 'pubg_mobile',
    name: 'PUBG Mobile',
    platform: 'Mobile',
    genre: 'Battle Royale',
    teamFormat: 'Squads (4v4)',
    rosterSize: 4,
    popularity: 96,
    avgViewers: 760000,
    peakViewers: 3900000,
    prizePoolScale: 4500000,
    proTeamsCount: 210,
    rating: 95,
    tournamentsCount: 24,
    currentSeason: 'PMGC Global Championship',
    iconEmoji: '🪂',
    themeColor: 'from-yellow-500 to-orange-600',
    roles: ['In-Game Leader (IGL)', 'Assaulter / Scout', 'Fragger', 'Support / Medic'],
    keyAttributes: ['Aim', 'Gyroscope Control', 'Vehicle Rotation', 'Map Reading', 'Teamwork', 'Patience'],
    description: 'Масштабный тактический Battle Royale с реалистичной баллистикой и гироскопической стрельбой.',
  },

  bgmi: {
    id: 'bgmi',
    name: 'BGMI',
    platform: 'Mobile',
    genre: 'Battle Royale',
    teamFormat: 'Squads (4v4)',
    rosterSize: 4,
    popularity: 90,
    avgViewers: 580000,
    peakViewers: 2200000,
    prizePoolScale: 2000000,
    proTeamsCount: 140,
    rating: 89,
    tournamentsCount: 15,
    currentSeason: 'BGIS & BMPS Pro Series',
    iconEmoji: '🇮🇳',
    themeColor: 'from-amber-600 to-emerald-600',
    roles: ['IGL', 'Point Assaulter', 'Entry Fragger', 'Anchor/Support'],
    keyAttributes: ['Aim', 'Close Range Reflexes', 'Zone Strategy', 'Team Communication', 'Consistency'],
    description: 'Индийский супер-хит мобильного киберспорта с огромными стадионами и бешеной поддержкой зрителей.',
  },

  cod_mobile: {
    id: 'cod_mobile',
    name: 'Call of Duty: Mobile',
    platform: 'Mobile',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 88,
    avgViewers: 310000,
    peakViewers: 1200000,
    prizePoolScale: 1700000,
    proTeamsCount: 110,
    rating: 87,
    tournamentsCount: 16,
    currentSeason: 'CODM World Championship Stage 5',
    iconEmoji: '🎖️',
    themeColor: 'from-emerald-600 to-teal-800',
    roles: ['SMG / Slayer', 'AR / Anchor', 'Sniper / Flex', 'Objective Player', 'Support'],
    keyAttributes: ['Aim', 'Slide Canceling', 'Spawn Knowledge', 'Hardpoint Control', 'Reaction', 'Teamwork'],
    description: 'Классический темповый шутер Call of Duty на мобильных экранах с режимами Hardpoint и SnD.',
  },

  garena_free_fire: {
    id: 'garena_free_fire',
    name: 'Garena Free Fire',
    platform: 'Mobile',
    genre: 'Battle Royale',
    teamFormat: 'Squads (4v4)',
    rosterSize: 4,
    popularity: 92,
    avgViewers: 640000,
    peakViewers: 2900000,
    prizePoolScale: 2200000,
    proTeamsCount: 150,
    rating: 91,
    tournamentsCount: 18,
    currentSeason: 'Free Fire Continental Pro League',
    iconEmoji: '⚡',
    themeColor: 'from-rose-500 to-red-700',
    roles: ['Squad Leader', 'Frontline Rusher', 'Marksman', 'Tactician'],
    keyAttributes: ['Aim', 'Wall Deployment', 'Positioning', 'Team Synergies', 'Zone Control'],
    description: 'Улучшенная версия Free Fire MAX с ультра-графикой и жестким соревновательным регламентом.',
  },

  // =========================================================================
  // 🖥️ PC-КИБЕРСПОРТ
  // =========================================================================
  cs2: {
    id: 'cs2',
    name: 'Counter-Strike 2',
    platform: 'PC',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 100,
    avgViewers: 1450000,
    peakViewers: 5800000,
    prizePoolScale: 8000000,
    proTeamsCount: 320,
    rating: 99,
    tournamentsCount: 32,
    currentSeason: 'CS2 Major Circuit & Intel Extreme Masters',
    iconEmoji: '💣',
    themeColor: 'from-amber-500 to-yellow-600',
    roles: ['In-Game Leader (IGL)', 'Primary Sniper (AWPer)', 'Entry Fragger', 'Support / Trade', 'Lurker'],
    keyAttributes: ['Aim', 'Reaction', 'Utility', 'Positioning', 'Game Sense', 'Teamwork'],
    description: 'Золотой стандарт тактических командных шутеров на Source 2 с динамическим дымом и саб-тиком.',
  },

  dota_2: {
    id: 'dota_2',
    name: 'Dota 2',
    platform: 'PC',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 98,
    avgViewers: 1150000,
    peakViewers: 4900000,
    prizePoolScale: 25000000,
    proTeamsCount: 260,
    rating: 98,
    tournamentsCount: 26,
    currentSeason: 'The International & Riyadh Masters',
    iconEmoji: '🛡️',
    themeColor: 'from-red-600 to-stone-900',
    roles: ['Position 1 (Hard Carry)', 'Position 2 (Mid)', 'Position 3 (Offlane)', 'Position 4 (Soft Support)', 'Position 5 (Hard Support / Captain)'],
    keyAttributes: ['Mechanics', 'Map Awareness', 'Farming', 'Decision Making', 'Teamfight', 'Drafting'],
    description: 'Глубочайшая стратегическая MOBA с рекордными миллионными призовыми эгидами The International.',
  },

  lol: {
    id: 'lol',
    name: 'League of Legends',
    platform: 'PC',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 100,
    avgViewers: 2200000,
    peakViewers: 6400000,
    prizePoolScale: 12000000,
    proTeamsCount: 340,
    rating: 100,
    tournamentsCount: 30,
    currentSeason: 'Worlds Championship & MSI Global Circuit',
    iconEmoji: '🧙',
    themeColor: 'from-blue-600 to-cyan-500',
    roles: ['Top Laner', 'Jungler', 'Mid Laner', 'ADC (Bot)', 'Support'],
    keyAttributes: ['Mechanics', 'Wave Control', 'Vision Control', 'Teamfight Coordination', 'Drafting', 'Shotcalling'],
    description: 'Главная киберспортивная дисциплина планеты с франшизными лигами (LCK, LPL, LEC, LCS) и Worlds.',
  },

  valorant: {
    id: 'valorant',
    name: 'VALORANT',
    platform: 'PC',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 99,
    avgViewers: 980000,
    peakViewers: 4100000,
    prizePoolScale: 6000000,
    proTeamsCount: 280,
    rating: 98,
    tournamentsCount: 28,
    currentSeason: 'VCT Champions & Masters Circuit',
    iconEmoji: '🎯',
    themeColor: 'from-rose-600 to-pink-600',
    roles: ['Duelist (Entry)', 'Initiator (Info/Breach)', 'Controller (Smokes)', 'Sentinel (Anchor)', 'Flex / IGL'],
    keyAttributes: ['Aim', 'Ability Usage', 'Crosshair Placement', 'Site Retake', 'Team Coordination', 'Mental Strength'],
    description: 'Тактический шутер от Riot Games со способностями агентов, зрелищными клатчами и VCT Champions.',
  },

  r6_siege: {
    id: 'r6_siege',
    name: "Tom Clancy's Rainbow Six Siege",
    platform: 'PC',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 86,
    avgViewers: 320000,
    peakViewers: 1300000,
    prizePoolScale: 3000000,
    proTeamsCount: 110,
    rating: 86,
    tournamentsCount: 16,
    currentSeason: 'Six Invitational & BLAST R6 Major',
    iconEmoji: '🧱',
    themeColor: 'from-slate-700 to-zinc-900',
    roles: ['Entry Fragger', 'Hard Breacher', 'Support / Flank Watch', 'Roamer', 'Anchor / IGL'],
    keyAttributes: ['Map Destruction Knowledge', 'Drone Information', 'Crossfires', 'Gadget Synergy', 'Reaction'],
    description: 'Ультра-тактический шутер с разрушаемым окружением, вертикальным геймплеем и гаджетами операторов.',
  },

  apex_legends: {
    id: 'apex_legends',
    name: 'Apex Legends',
    platform: 'PC',
    genre: 'Battle Royale',
    teamFormat: 'Trios (3v3)',
    rosterSize: 3,
    popularity: 90,
    avgViewers: 440000,
    peakViewers: 1800000,
    prizePoolScale: 3500000,
    proTeamsCount: 160,
    rating: 89,
    tournamentsCount: 20,
    currentSeason: 'ALGS Championship Pro League',
    iconEmoji: '🚀',
    themeColor: 'from-red-600 to-amber-600',
    roles: ['In-Game Leader (IGL)', 'Entry Fragger / Duelist', 'Anchor / Support / Controller'],
    keyAttributes: ['Aim', 'Movement (Tap Strafe)', 'Positioning', 'Endgame Zone Calls', 'Ability Synergies'],
    description: 'Высокоскоростной Battle Royale с вертикальной динамикой, скольжениями и легендарным ALGS.',
  },

  starcraft_2: {
    id: 'starcraft_2',
    name: 'StarCraft II',
    platform: 'PC',
    genre: 'Strategy/RTS',
    teamFormat: '1v1 (Solo RTS)',
    rosterSize: 2, // 1 Active + 1 Sub
    popularity: 83,
    avgViewers: 170000,
    peakViewers: 650000,
    prizePoolScale: 1500000,
    proTeamsCount: 60,
    rating: 83,
    tournamentsCount: 14,
    currentSeason: 'ESL Pro Tour & IEM Katowice Finals',
    iconEmoji: '🛸',
    themeColor: 'from-sky-600 to-indigo-900',
    roles: ['Terran Main', 'Zerg Main', 'Protoss Main'],
    keyAttributes: ['APM (Actions Per Minute)', 'Multitasking', 'Micro Control', 'Macro Economy', 'Build Order Strategy', 'Scouting'],
    description: 'Культовая стратегия в реальном времени с запредельным APM (350+ действий в минуту) и глубокой тактикой.',
  },

  overwatch_2: {
    id: 'overwatch_2',
    name: 'Overwatch 2',
    platform: 'PC',
    genre: 'FPS/Tactical',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 84,
    avgViewers: 260000,
    peakViewers: 950000,
    prizePoolScale: 2000000,
    proTeamsCount: 90,
    rating: 84,
    tournamentsCount: 16,
    currentSeason: 'OWCS (Overwatch Champions Series)',
    iconEmoji: '🤖',
    themeColor: 'from-orange-500 to-amber-500',
    roles: ['Tank', 'Hitscan DPS', 'Projectile / Flex DPS', 'Main Support', 'Flex Support'],
    keyAttributes: ['Aim', 'Ultimate Tracking', 'Positioning', 'Teamfight Timing', 'Hero Flexibility'],
    description: 'Командный героический шутер с быстрыми ультимейтами, комбо-ротациями и динамичными захватами точек.',
  },

  rocket_league: {
    id: 'rocket_league',
    name: 'Rocket League',
    platform: 'PC',
    genre: 'Sports/Arcade',
    teamFormat: '3v3',
    rosterSize: 3,
    popularity: 87,
    avgViewers: 350000,
    peakViewers: 1400000,
    prizePoolScale: 2500000,
    proTeamsCount: 130,
    rating: 87,
    tournamentsCount: 18,
    currentSeason: 'RLCS World Championship Season',
    iconEmoji: '🏎️',
    themeColor: 'from-blue-500 to-sky-400',
    roles: ['Striker', 'Midfield Playmaker', 'Goalkeeper / Last Man'],
    keyAttributes: ['Aerial Mechanics', 'Boost Management', 'Rotations', 'Speed & Recovery', 'Accuracy', 'Teamwork'],
    description: 'Футбольный экшен на реактивных автомобилях с невероятной физикой полетов и филигранным контролем мяча.',
  },

  deadlock: {
    id: 'deadlock',
    name: 'Deadlock',
    platform: 'PC',
    genre: 'MOBA',
    teamFormat: '6v6',
    rosterSize: 6,
    popularity: 91,
    avgViewers: 520000,
    peakViewers: 2100000,
    prizePoolScale: 3000000,
    proTeamsCount: 150,
    rating: 90,
    tournamentsCount: 18,
    currentSeason: 'Deadlock Premier Pro Invitational',
    iconEmoji: '🕯️',
    themeColor: 'from-amber-600 to-stone-800',
    roles: ['Laning Carry', 'Mid Initiator', 'Ganker / Assassin', 'Support / Crowd Control', 'Split Pusher', 'Tank Flex'],
    keyAttributes: ['Aim Tracking', 'Zipline Movement', 'Farming Souls', 'Item Builds', 'Teamfight Execution', 'Map Awareness'],
    description: 'Новейшая гибридная 6v6 MOBA/шутер от третьего лица от Valve с 4 линиями, зиплайнами и покупкой предметов.',
  },

  // =========================================================================
  // 🔄 КРОССПЛАТФОРМЕННЫЙ & WEB-КИБЕРСПОРТ
  // =========================================================================
  hearthstone: {
    id: 'hearthstone',
    name: 'Hearthstone',
    platform: 'Cross-platform',
    genre: 'Card/Autobattler',
    teamFormat: '1v1 (Card Duels)',
    rosterSize: 2, // 1 Starter + 1 Specialist
    popularity: 79,
    avgViewers: 150000,
    peakViewers: 540000,
    prizePoolScale: 800000,
    proTeamsCount: 50,
    rating: 79,
    tournamentsCount: 12,
    currentSeason: 'Masters Tour & World Championship',
    iconEmoji: '🎴',
    themeColor: 'from-amber-500 to-yellow-700',
    roles: ['Standard Master', 'Conquest Strategist'],
    keyAttributes: ['Deck Building', 'Mulligan Decisions', 'RNG Management', 'Lethal Calculation', 'Meta Adaptability'],
    description: 'Классическая коллекционная карточная игра от Blizzard с динамичными матчами и турнирами формата Conquest.',
  },

  tft: {
    id: 'tft',
    name: 'Teamfight Tactics (TFT)',
    platform: 'Cross-platform',
    genre: 'Card/Autobattler',
    teamFormat: '1v1 / FFA (8 Players)',
    rosterSize: 2,
    popularity: 89,
    avgViewers: 420000,
    peakViewers: 1600000,
    prizePoolScale: 1500000,
    proTeamsCount: 90,
    rating: 88,
    tournamentsCount: 16,
    currentSeason: 'TFT Championship & Vegas Open',
    iconEmoji: '♟️',
    themeColor: 'from-teal-500 to-emerald-700',
    roles: ['Econ Strategist', 'Fast 8 Player', 'Reroll Specialist'],
    keyAttributes: ['Economy Management', 'Positioning', 'Augment Selection', 'Pivot Ability', 'Board Strength Reading'],
    description: 'Ведущий автобаттлер по вселенной League of Legends с миллионами тактических комбинаций фигур и предметов.',
  },

  wild_rift: {
    id: 'wild_rift',
    name: 'League of Legends: Wild Rift',
    platform: 'Cross-platform',
    genre: 'MOBA',
    teamFormat: '5v5',
    rosterSize: 5,
    popularity: 85,
    avgViewers: 290000,
    peakViewers: 1150000,
    prizePoolScale: 2000000,
    proTeamsCount: 95,
    rating: 84,
    tournamentsCount: 14,
    currentSeason: 'Wild Rift Icons Global Championship',
    iconEmoji: '⚡',
    themeColor: 'from-sky-500 to-cyan-700',
    roles: ['Baron Lane', 'Jungle', 'Mid', 'Dragon Lane (ADC)', 'Support'],
    keyAttributes: ['Touch Mechanics', 'Macro Awareness', 'Objective Smite Control', 'Team Coordination', 'Drafting'],
    description: 'Мобильно-планшетная версия League of Legends с адаптированным управлением и динамичным темпом матчей.',
  },

  fortnite: {
    id: 'fortnite',
    name: 'Fortnite',
    platform: 'Cross-platform',
    genre: 'Battle Royale',
    teamFormat: 'Duos / Squads',
    rosterSize: 4,
    popularity: 97,
    avgViewers: 920000,
    peakViewers: 4800000,
    prizePoolScale: 8000000,
    proTeamsCount: 220,
    rating: 96,
    tournamentsCount: 26,
    currentSeason: 'FNCS Global Championship Season',
    iconEmoji: '⛏️',
    themeColor: 'from-purple-600 to-pink-600',
    roles: ['IGL / Tarper', 'Fragger', 'Support / Piece Controller', 'Anchor'],
    keyAttributes: ['Building & Editing Speed', 'Piece Control', 'Aim', 'Zone Surge Management', 'Endgame Tarping'],
    description: 'Феномен со строительством, мгновенными редакторами конструкций и грандиозными турнирами FNCS.',
  },

  chess_com: {
    id: 'chess_com',
    name: 'Chess.com',
    platform: 'Web',
    genre: 'Chess',
    teamFormat: '1v1 (Mind Sports)',
    rosterSize: 2, // 1 Starter Grandmaster + 1 Coach/Sub
    popularity: 93,
    avgViewers: 430000,
    peakViewers: 2300000,
    prizePoolScale: 2500000,
    proTeamsCount: 80,
    rating: 92,
    tournamentsCount: 20,
    currentSeason: 'Champions Chess Tour & Speed Chess Championship',
    iconEmoji: '♟️',
    themeColor: 'from-emerald-600 to-zinc-900',
    roles: ['Grandmaster Duelist', 'Blitz / Bullet Prodigy'],
    keyAttributes: ['Calculation Speed', 'Opening Theory', 'Tactics / Spotting Blunders', 'Time Trouble Play', 'Endgame Technique', 'Psychology'],
    description: 'Королевская интеллектуальная игра на платформе Chess.com с быстрыми блиц/буллит партиями и гроссмейстерами.',
  },

  lichess: {
    id: 'lichess',
    name: 'Lichess',
    platform: 'Web',
    genre: 'Chess',
    teamFormat: '1v1 (Mind Sports)',
    rosterSize: 2,
    popularity: 87,
    avgViewers: 230000,
    peakViewers: 920000,
    prizePoolScale: 1200000,
    proTeamsCount: 60,
    rating: 86,
    tournamentsCount: 16,
    currentSeason: 'Lichess Elite Arena & Titled Arena Grand Prix',
    iconEmoji: '♞',
    themeColor: 'from-slate-600 to-zinc-800',
    roles: ['Arena Berserk Master', 'Classical & Blitz Specialist'],
    keyAttributes: ['Berserk Strategy', 'Puzzle Rating', 'Pattern Recognition', 'Ultra-bullet Reflexes', 'Deep Positional Play'],
    description: 'Открытая киберспортивная шахматная арена с марафонами Berserk и престижными Titled Arena.',
  },
};

export const ALL_DISCIPLINE_IDS = Object.keys(ESPORTS_DISCIPLINES) as DisciplineId[];
