/**
 * Business Empire: Ultimate
 * Automotive Spare Parts Catalog & Manufacturing Recipes
 * Integrates directly with raw materials, warehouses, factory production lines,
 * and repair workshops.
 */

import { AutoPartItem } from '../../types/automotive';

export const AUTO_PARTS_CATALOG: AutoPartItem[] = [
  // 1. ДВИГАТЕЛЬ & НАВЕСНОЕ ОБОРУДОВАНИЕ (ENGINE)
  {
    id: 'part_engine_assembly_i4',
    name: 'Двигатель 4-цилиндровый Turbo в сборе',
    category: 'engine',
    quality: 'Стандарт',
    basePrice: 3800,
    marketPrice: 4200,
    supplier: 'Bosch & Mahle Powertrain',
    weight: 140,
    volume: 0.8,
    productionCost: 2100,
    materialRequirements: [
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 2 },
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 3 },
      { commodityId: 'cat_komplektuyushchie_item_1_var_1', commodityName: 'Процессор (CPU)', quantity: 2 },
    ],
    description: 'Блок цилиндров, коленвал, поршневая группа, ГБЦ и навесные датчики.',
  },
  {
    id: 'part_engine_v8_twin_turbo',
    name: 'Двигатель V8 Twin-Turbo High-Performance',
    category: 'engine',
    quality: 'Премиум',
    basePrice: 12500,
    marketPrice: 14200,
    supplier: 'AMG & M-GmbH Performance Parts',
    weight: 220,
    volume: 1.2,
    productionCost: 6800,
    materialRequirements: [
      { commodityId: 'cat_metally_item_2_var_2', commodityName: 'Авиационный дюралюминий Д16Т', quantity: 4 },
      { commodityId: 'cat_metally_item_3_var_2', commodityName: 'Титан ВТ1-0 пруток', quantity: 2 },
      { commodityId: 'cat_komplektuyushchie_item_1_var_2', commodityName: '16 ядер 32 потока Флагман Box', quantity: 3 },
    ],
    description: 'Собранный вручную битурбированный V8 с коваными поршнями и спортивным распредвалом.',
  },
  {
    id: 'part_turbocharger_unit',
    name: 'Турбокомпрессор Twin-Scroll с актуатором',
    category: 'engine',
    quality: 'Оригинал',
    basePrice: 950,
    marketPrice: 1100,
    supplier: 'Garrett Motion & BorgWarner',
    weight: 8.5,
    volume: 0.03,
    productionCost: 520,
    materialRequirements: [
      { commodityId: 'cat_metally_item_3_var_1', commodityName: 'Никель катодный 99.9%', quantity: 1 },
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 1 },
    ],
    description: 'Высокотемпературная крыльчатка из сплава Инконель для мгновенного наддува.',
  },
  {
    id: 'part_alternator_starter_kit',
    name: 'Генератор 180A + Стартер редукторный',
    category: 'engine',
    quality: 'Стандарт',
    basePrice: 420,
    marketPrice: 490,
    supplier: 'Denso & Valeo Systems',
    weight: 11,
    volume: 0.04,
    productionCost: 220,
    materialRequirements: [
      { commodityId: 'cat_metally_item_1_var_1', commodityName: 'Медь катодная Grade A', quantity: 1 },
      { commodityId: 'cat_plastik_item_2_var_2', commodityName: 'ABS-пластик ударопрочный', quantity: 1 },
    ],
    description: 'Система запуска и надежного энергоснабжения бортовой сети.',
  },

  // 2. ТРАНСМИССИЯ (TRANSMISSION)
  {
    id: 'part_gearbox_auto_8speed',
    name: 'Автоматическая коробка передач 8-ст (ZF / Aisin)',
    category: 'transmission',
    quality: 'Оригинал',
    basePrice: 3200,
    marketPrice: 3600,
    supplier: 'ZF Friedrichshafen & Aisin Seiki',
    weight: 88,
    volume: 0.45,
    productionCost: 1750,
    materialRequirements: [
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 2 },
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 2 },
      { commodityId: 'cat_masla_item_2_var_1', commodityName: 'ATF Dexron VI для АКПП', quantity: 4 },
    ],
    description: 'Гидромеханическая 8-ступенчатая коробка с мехатроником и пакетом фрикционов.',
  },
  {
    id: 'part_clutch_flywheel_kit',
    name: 'Сцепление двухдисковое + Двухмассовый маховик',
    category: 'transmission',
    quality: 'Стандарт',
    basePrice: 680,
    marketPrice: 790,
    supplier: 'LuK & Sachs Automotive',
    weight: 18,
    volume: 0.05,
    productionCost: 340,
    materialRequirements: [
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 1 },
      { commodityId: 'cat_metally_item_1_var_1', commodityName: 'Медь катодная Grade A', quantity: 1 },
    ],
    description: 'Комплект гашения крутильных колебаний и плавной передачи момента.',
  },

  // 3. ТОРМОЗНАЯ СИСТЕМА (BRAKES)
  {
    id: 'part_brakes_discs_pads_std',
    name: 'Тормозные диски вентилируемые + Колодки (комплект)',
    category: 'brakes',
    quality: 'Стандарт',
    basePrice: 180,
    marketPrice: 220,
    supplier: 'Brembo & TRW Aftermarket',
    weight: 16,
    volume: 0.03,
    productionCost: 95,
    materialRequirements: [
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 1 },
    ],
    description: 'Чугунные вентилируемые диски с полуметаллическими фрикционными накладками.',
  },
  {
    id: 'part_brakes_carbon_ceramic',
    name: 'Углерод-керамическая тормозная система Track-Day',
    category: 'brakes',
    quality: 'Люкс',
    basePrice: 4500,
    marketPrice: 5400,
    supplier: 'Brembo Carbon Ceramic Matrix',
    weight: 14,
    volume: 0.04,
    productionCost: 2300,
    materialRequirements: [
      { commodityId: 'cat_metally_item_3_var_2', commodityName: 'Титан ВТ1-0 пруток', quantity: 2 },
      { commodityId: 'cat_metally_item_2_var_2', commodityName: 'Авиационный дюралюминий Д16Т', quantity: 1 },
    ],
    description: 'Композитные роторы из карбида кремния и 6-поршневые моноблочные суппорты.',
  },

  // 4. ПОДВЕСКА (SUSPENSION)
  {
    id: 'part_suspension_struts_arms',
    name: 'Амортизаторы газомасляные + Рычаги подвески (комплект)',
    category: 'suspension',
    quality: 'Стандарт',
    basePrice: 360,
    marketPrice: 430,
    supplier: 'Bilstein & Lemförder',
    weight: 24,
    volume: 0.08,
    productionCost: 190,
    materialRequirements: [
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 1 },
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 1 },
    ],
    description: 'Газонаполненные стойки, сайлентблоки и кованые алюминиевые рычаги.',
  },
  {
    id: 'part_air_suspension_strut',
    name: 'Пневмобаллоны подвески с компрессором',
    category: 'suspension',
    quality: 'Премиум',
    basePrice: 1400,
    marketPrice: 1650,
    supplier: 'Continental Air Spring Systems',
    weight: 22,
    volume: 0.12,
    productionCost: 750,
    materialRequirements: [
      { commodityId: 'cat_plastik_item_2_var_2', commodityName: 'ABS-пластик ударопрочный', quantity: 2 },
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 1 },
    ],
    description: 'Многокамерная адаптивная пневмоподвеска с блоком электромагнитных клапанов.',
  },

  // 5. ЭЛЕКТРОНИКА И ЭБУ (ELECTRONICS)
  {
    id: 'part_ecu_brain_harness',
    name: 'Электронный блок управления (ЭБУ / ECU) + Коса проводки',
    category: 'electronics',
    quality: 'Оригинал',
    basePrice: 750,
    marketPrice: 890,
    supplier: 'Bosch Automotive Electronics',
    weight: 4.5,
    volume: 0.02,
    productionCost: 380,
    materialRequirements: [
      { commodityId: 'cat_komplektuyushchie_item_1_var_1', commodityName: 'Процессор (CPU)', quantity: 1 },
      { commodityId: 'cat_komplektuyushchie_item_6_var_2', commodityName: 'B650 / B760 Средний класс', quantity: 1 },
      { commodityId: 'cat_metally_item_1_var_1', commodityName: 'Медь катодная Grade A', quantity: 1 },
    ],
    description: 'Центральный мозг автомобиля с прошивкой впрыска, ABS, ESP и подушек безопасности.',
  },
  {
    id: 'part_multimedia_digital_cockpit',
    name: 'Цифровой экран кокпита + Аудиосистема 12 динамиков',
    category: 'electronics',
    quality: 'Премиум',
    basePrice: 1100,
    marketPrice: 1350,
    supplier: 'Harman Kardon & LG Display Auto',
    weight: 8,
    volume: 0.06,
    productionCost: 580,
    materialRequirements: [
      { commodityId: 'cat_komplektuyushchie_item_5_var_1', commodityName: 'OLED 120Hz Модуль', quantity: 2 },
      { commodityId: 'cat_komplektuyushchie_item_3_var_1', commodityName: 'DDR5 32GB Память', quantity: 1 },
      { commodityId: 'cat_plastik_item_2_var_2', commodityName: 'ABS-пластик ударопрочный', quantity: 1 },
    ],
    description: 'Сдвоенный изогнутый 4K-дисплей, навигация, беспроводной CarPlay и усилитель звука.',
  },

  // 6. КУЗОВ И ОПТИКА (BODY & OPTICS)
  {
    id: 'part_body_panels_bumpers',
    name: 'Комплект кузовных панелей (Капот, крылья, бамперы)',
    category: 'body',
    quality: 'Стандарт',
    basePrice: 850,
    marketPrice: 1050,
    supplier: 'Magna International & Gordon Auto Body',
    weight: 45,
    volume: 0.65,
    productionCost: 420,
    materialRequirements: [
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 2 },
      { commodityId: 'cat_plastik_item_2_var_2', commodityName: 'ABS-пластик ударопрочный', quantity: 2 },
    ],
    description: 'Оцинкованный стальной и пластиковый обвес с катафорезным грунтованием.',
  },
  {
    id: 'part_matrix_led_headlights',
    name: 'Матричные лазерные фары Matrix LED (пара)',
    category: 'body',
    quality: 'Премиум',
    basePrice: 1600,
    marketPrice: 1950,
    supplier: 'Hella & Osram Automotive Lighting',
    weight: 7,
    volume: 0.08,
    productionCost: 820,
    materialRequirements: [
      { commodityId: 'cat_plastik_item_2_var_3', commodityName: 'Поликарбонат оптический для фар', quantity: 1 },
      { commodityId: 'cat_komplektuyushchie_item_1_var_1', commodityName: 'Процессор (CPU)', quantity: 1 },
    ],
    description: 'Адаптивный дальний свет с вырезанием встречного потока и динамическими поворотниками.',
  },

  // 7. САЛОН И ИНТЕРЬЕР (INTERIOR)
  {
    id: 'part_interior_leather_seats',
    name: 'Комплект сидений с электроприводом и кожей Nappa',
    category: 'interior',
    quality: 'Премиум',
    basePrice: 1500,
    marketPrice: 1800,
    supplier: 'Lear Corporation & Faurecia',
    weight: 55,
    volume: 0.9,
    productionCost: 780,
    materialRequirements: [
      { commodityId: 'cat_mebel_item_3_var_2', commodityName: 'Итальянская кожа aniline', quantity: 1 },
      { commodityId: 'cat_stroymaterialy_item_2_var_1', commodityName: 'Арматура строительная стальная', quantity: 1 },
      { commodityId: 'cat_plastik_item_2_var_2', commodityName: 'ABS-пластик ударопрочный', quantity: 1 },
    ],
    description: 'Ортопедические кресла с памятью положений, вентиляцией и массажем 8 зон.',
  },

  // 8. ШИНЫ И ДИСКИ (WHEELS & TIRES)
  {
    id: 'part_tires_set_premium_r19',
    name: 'Комплект премиальных шин R19 UHP (4 шт.)',
    category: 'tires',
    quality: 'Премиум',
    basePrice: 580,
    marketPrice: 690,
    supplier: 'Michelin & Continental Tires',
    weight: 42,
    volume: 0.32,
    productionCost: 280,
    materialRequirements: [
      { commodityId: 'cat_shiny_item_1_var_2', commodityName: 'R18 225/45 Зимняя премиум', quantity: 4 },
    ],
    description: 'Сверхвысокопроизводительные шины с максимальным сцеплением на мокром и сухом асфальте.',
  },
  {
    id: 'part_wheels_forged_r20',
    name: 'Кованые легкосплавные диски R20 (комплект 4 шт.)',
    category: 'wheels',
    quality: 'Премиум',
    basePrice: 1200,
    marketPrice: 1450,
    supplier: 'BBS & Vossen Forged Wheels',
    weight: 38,
    volume: 0.35,
    productionCost: 620,
    materialRequirements: [
      { commodityId: 'cat_metally_item_2_var_2', commodityName: 'Авиационный дюралюминий Д16Т', quantity: 2 },
    ],
    description: 'Моноблочная ковка авиационного сплава 6061-T6 с минимальным неподрессоренным весом.',
  },

  // 9. БАТАРЕЯ ДЛЯ ЭЛЕКТРОМОБИЛЕЙ (BATTERY / EV PACK)
  {
    id: 'part_ev_battery_pack_90kwh',
    name: 'Тяговая батарея Li-Ion NMC 90 kWh 800V',
    category: 'battery',
    quality: 'Премиум',
    basePrice: 8500,
    marketPrice: 9900,
    supplier: 'CATL & LG Energy Solution',
    weight: 520,
    volume: 0.95,
    productionCost: 4800,
    materialRequirements: [
      { commodityId: 'cat_metally_item_4_var_1', commodityName: 'Карбонат лития Battery Grade', quantity: 3 },
      { commodityId: 'cat_metally_item_3_var_1', commodityName: 'Никель катодный 99.9%', quantity: 2 },
      { commodityId: 'cat_metally_item_1_var_1', commodityName: 'Медь катодная Grade A', quantity: 2 },
      { commodityId: 'cat_metally_item_2_var_1', commodityName: 'Алюминий первичный слитки', quantity: 2 },
    ],
    description: 'Высоковольтная батарея с жидкостным термостатированием и поддержкой зарядки 350 кВт.',
  },

  // 10. ТЕХНИЧЕСКИЕ ЖИДКОСТИ И МАСЛА (FLUIDS)
  {
    id: 'part_oil_and_filters_full_service',
    name: 'Комплект ТО (Масло 5W-30 PAO + 4 фильтра + Свечи)',
    category: 'fluids',
    quality: 'Стандарт',
    basePrice: 95,
    marketPrice: 120,
    supplier: 'Mobil 1 & Mann Filter',
    weight: 6.5,
    volume: 0.02,
    productionCost: 48,
    materialRequirements: [
      { commodityId: 'cat_masla_item_1_var_2', commodityName: '0W-20 PAO Эстеры', quantity: 5 },
    ],
    description: 'Синтетическое масло, масляный, воздушный, салонный, топливный фильтры и иридиевые свечи.',
  },
];
