/**
 * Business Empire: Ultimate
 * Industrial Production Catalog, Recipes & Factory Blueprints
 */

import {
  FactoryType,
  FactoryChainId,
  FactoryRecipe,
  FactoryUpgradeTier,
  ProductionChainDefinition,
} from '../../types/production';

export interface FactoryBlueprint {
  type: FactoryType;
  name: string;
  categoryTitle: string;
  tagline: string;
  description: string;
  purchaseCost: number;
  baseCapacityUnitsDaily: number;
  baseProductionTimeHours: number;
  minEmployees: number;
  baseSalaryDailyPerWorker: number;
  baseElectricityKWhDaily: number;
  baseMaintenanceDaily: number;
  icon: string;
  bannerGradient: string;
  supportedChains: FactoryChainId[];
  defaultRecipeId: string;
}

export const FACTORY_BLUEPRINTS: Record<FactoryType, FactoryBlueprint> = {
  food_factory: {
    type: 'food_factory',
    name: 'Пищевой комбинат',
    categoryTitle: 'Пищевая промышленность',
    tagline: 'Глубокая переработка агрокультур, мукомольные линии и хлебопекарни',
    description: 'Комплекс элеваторов, вальцовых мельниц и автоматизированных подовых печей непрерывного цикла.',
    purchaseCost: 280000,
    baseCapacityUnitsDaily: 1200,
    baseProductionTimeHours: 4,
    minEmployees: 12,
    baseSalaryDailyPerWorker: 95,
    baseElectricityKWhDaily: 480,
    baseMaintenanceDaily: 240,
    icon: 'Wheat',
    bannerGradient: 'from-amber-600/20 via-orange-600/10 to-transparent',
    supportedChains: ['grain_to_bread'],
    defaultRecipeId: 'recipe_grain_to_flour',
  },
  textile_factory: {
    type: 'textile_factory',
    name: 'Текстильная фабрика',
    categoryTitle: 'Легкая промышленность',
    tagline: 'Прядильно-ткацкие станки, крашение и пошив готовой брендовой одежды',
    description: 'Пневмомеханические прядильные машины и швейные конвейеры японского стандарта.',
    purchaseCost: 350000,
    baseCapacityUnitsDaily: 600,
    baseProductionTimeHours: 6,
    minEmployees: 18,
    baseSalaryDailyPerWorker: 90,
    baseElectricityKWhDaily: 620,
    baseMaintenanceDaily: 310,
    icon: 'Shirt',
    bannerGradient: 'from-violet-600/20 via-purple-600/10 to-transparent',
    supportedChains: ['cotton_to_clothing'],
    defaultRecipeId: 'recipe_cotton_to_fabric',
  },
  metallurgy_plant: {
    type: 'metallurgy_plant',
    name: 'Металлургический завод',
    categoryTitle: 'Тяжелая металлургия',
    tagline: 'Дуговые сталеплавильные печи, сортопрокатные станы и отливка деталей',
    description: 'Высокотемпературная плавка руды и легирование конструкционных сталей для машиностроения.',
    purchaseCost: 850000,
    baseCapacityUnitsDaily: 350,
    baseProductionTimeHours: 8,
    minEmployees: 32,
    baseSalaryDailyPerWorker: 135,
    baseElectricityKWhDaily: 2400,
    baseMaintenanceDaily: 750,
    icon: 'Flame',
    bannerGradient: 'from-red-600/20 via-orange-700/10 to-transparent',
    supportedChains: ['iron_to_autoparts'],
    defaultRecipeId: 'recipe_iron_to_steel',
  },
  electronics_plant: {
    type: 'electronics_plant',
    name: 'Электронный завод',
    categoryTitle: 'Высокотехнологичное микропроизводство',
    tagline: 'Нефтеполимерный синтез, поверхностный монтаж SMT и сборка микрочипов',
    description: 'Чистые комнаты класса ISO 5, роботы-установщики компонентов и вакуумные паяльные печи.',
    purchaseCost: 1200000,
    baseCapacityUnitsDaily: 450,
    baseProductionTimeHours: 6,
    minEmployees: 28,
    baseSalaryDailyPerWorker: 160,
    baseElectricityKWhDaily: 1850,
    baseMaintenanceDaily: 890,
    icon: 'Cpu',
    bannerGradient: 'from-cyan-600/20 via-blue-600/10 to-transparent',
    supportedChains: ['oil_to_electronics'],
    defaultRecipeId: 'recipe_oil_to_plastic',
  },
  autoparts_factory: {
    type: 'autoparts_factory',
    name: 'Завод автозапчастей',
    categoryTitle: 'Автомобильные компоненты',
    tagline: 'Тормозные системы, подвеска, турбины и агрегатная сборка ДВС и трансмиссий',
    description: 'Многокоординатные станки ЧПУ, роботы лазерной сварки и стенды гидродинамических испытаний.',
    purchaseCost: 950000,
    baseCapacityUnitsDaily: 220,
    baseProductionTimeHours: 8,
    minEmployees: 25,
    baseSalaryDailyPerWorker: 140,
    baseElectricityKWhDaily: 1400,
    baseMaintenanceDaily: 620,
    icon: 'Cog',
    bannerGradient: 'from-amber-600/20 via-yellow-600/10 to-transparent',
    supportedChains: ['iron_to_autoparts'],
    defaultRecipeId: 'recipe_steel_to_autoparts',
  },
  automobile_plant: {
    type: 'automobile_plant',
    name: 'Автосборочный завод',
    categoryTitle: 'Автомобилестроение полного цикла',
    tagline: 'Сварочные роботы KUKA, катафорезная покраска и конвейер финальной сборки',
    description: 'Масштабный автогигант полного цикла выпуска легковых машин, кроссоверов и коммерческих грузовиков.',
    purchaseCost: 3200000,
    baseCapacityUnitsDaily: 25,
    baseProductionTimeHours: 12,
    minEmployees: 65,
    baseSalaryDailyPerWorker: 175,
    baseElectricityKWhDaily: 4200,
    baseMaintenanceDaily: 1950,
    icon: 'Car',
    bannerGradient: 'from-emerald-600/20 via-teal-600/10 to-transparent',
    supportedChains: ['car_assembly'],
    defaultRecipeId: 'recipe_assemble_sedan',
  },
};

export const FACTORY_RECIPES: FactoryRecipe[] = [
  // ==========================================
  // 1. ЦЕПОЧКА: ЗЕРНО → МУКА → ХЛЕБ (Пищевой завод)
  // ==========================================
  {
    id: 'recipe_grain_to_flour',
    factoryType: 'food_factory',
    chainId: 'grain_to_bread',
    name: 'Помол зерна в муку высшего сорта',
    tagline: 'Зерно → Мука',
    description: 'Переработка продовольственной пшеницы на вальцовых мельницах с отделением отрубей.',
    tierRequired: 1,
    cycleHours: 4,
    inputs: [
      { category: 'Зерно', name: 'Пшеница продовольственная', quantity: 2, unit: 'т', estimatedCost: 220 },
    ],
    outputs: [
      {
        category: 'Продукты',
        name: 'Мука пшеничная высший сорт',
        quantity: 1.8,
        unit: 'т',
        quality: 'Стандарт',
        weight: 1000,
        volume: 1.2,
        baseMarketValue: 480,
      },
    ],
    laborRequirement: 8,
    electricityKWhPerBatch: 120,
    reagentCostPerBatch: 40,
  },
  {
    id: 'recipe_flour_to_bread',
    factoryType: 'food_factory',
    chainId: 'grain_to_bread',
    name: 'Промышленная выпечка хлеба и багетов',
    tagline: 'Мука → Хлеб',
    description: 'Автоматизированный замес теста, расстойка и подовая выпечка свежего хлеба для розничных сетей.',
    tierRequired: 1,
    cycleHours: 3,
    inputs: [
      { category: 'Продукты', name: 'Мука пшеничная высший сорт', quantity: 0.5, unit: 'т', estimatedCost: 480 },
      { category: 'Продукты', name: 'Сахар и подсластители', quantity: 0.05, unit: 'т', estimatedCost: 900 },
    ],
    outputs: [
      {
        category: 'Продукты',
        name: 'Хлеб свежий подовый и багеты',
        quantity: 650,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 0.6,
        volume: 0.002,
        baseMarketValue: 1.9,
      },
    ],
    laborRequirement: 10,
    electricityKWhPerBatch: 160,
    reagentCostPerBatch: 65,
  },
  {
    id: 'recipe_premium_bakery_pastry',
    factoryType: 'food_factory',
    chainId: 'grain_to_bread',
    name: 'Кондитерская линия: Круассаны и десерты',
    tagline: 'Мука + Шоколад → Премиум выпечка',
    description: 'Слоеное французское тесто со сливочным маслом и шоколадной начинкой для люксовых кофеен.',
    tierRequired: 3,
    cycleHours: 5,
    inputs: [
      { category: 'Продукты', name: 'Мука пшеничная высший сорт', quantity: 0.4, unit: 'т', estimatedCost: 480 },
      { category: 'Продукты', name: 'Шоколад сырьевой', quantity: 0.15, unit: 'т', estimatedCost: 9000 },
    ],
    outputs: [
      {
        category: 'Продукты',
        name: 'Круассаны и премиум десерты',
        quantity: 800,
        unit: 'шт.',
        quality: 'Люкс',
        weight: 0.25,
        volume: 0.001,
        baseMarketValue: 4.5,
      },
    ],
    laborRequirement: 14,
    electricityKWhPerBatch: 210,
    reagentCostPerBatch: 120,
  },

  // ==========================================
  // 2. ЦЕПОЧКА: ХЛОПОК → ТКАНЬ → ОДЕЖДА (Текстильная фабрика)
  // ==========================================
  {
    id: 'recipe_cotton_to_fabric',
    factoryType: 'textile_factory',
    chainId: 'cotton_to_clothing',
    name: 'Прядение хлопка и ткачество полотна',
    tagline: 'Хлопок → Ткань',
    description: 'Очистка хлопкового волокна, гребенное прядение и производство плотной ткани и денима.',
    tierRequired: 1,
    cycleHours: 6,
    inputs: [
      { category: 'Хлопок', name: 'Хлопок-волокно первичное', quantity: 1.5, unit: 'т', estimatedCost: 1950 },
    ],
    outputs: [
      {
        category: 'Одежда',
        name: 'Ткань хлопковая и деним в рулонах',
        quantity: 1.3,
        unit: 'т',
        quality: 'Стандарт',
        weight: 1000,
        volume: 1.8,
        baseMarketValue: 4200,
      },
    ],
    laborRequirement: 14,
    electricityKWhPerBatch: 280,
    reagentCostPerBatch: 90,
  },
  {
    id: 'recipe_fabric_to_clothing',
    factoryType: 'textile_factory',
    chainId: 'cotton_to_clothing',
    name: 'Пошив базовой одежды (Футболки & Джинсы)',
    tagline: 'Ткань → Одежда',
    description: 'Раскройный автоматизированный комплекс и конвейерный пошив футболок и классических джинсов.',
    tierRequired: 1,
    cycleHours: 5,
    inputs: [
      { category: 'Одежда', name: 'Ткань хлопковая и деним в рулонах', quantity: 0.3, unit: 'т', estimatedCost: 4200 },
    ],
    outputs: [
      {
        category: 'Одежда',
        name: 'Футболка базовая хлопковая',
        quantity: 250,
        unit: 'шт.',
        quality: 'Стандарт',
        weight: 0.25,
        volume: 0.001,
        baseMarketValue: 18,
      },
      {
        category: 'Одежда',
        name: 'Джинсы классические',
        quantity: 150,
        unit: 'шт.',
        quality: 'Стандарт',
        weight: 0.7,
        volume: 0.003,
        baseMarketValue: 55,
      },
    ],
    laborRequirement: 18,
    electricityKWhPerBatch: 220,
    reagentCostPerBatch: 80,
  },
  {
    id: 'recipe_designer_suits',
    factoryType: 'textile_factory',
    chainId: 'cotton_to_clothing',
    name: 'Пошив деловых костюмов и курток',
    tagline: 'Ткань → Деловые костюмы',
    description: 'Индивидуальный машинный крой премиальных мужских и женских костюмов с водоотталкивающей пропиткой.',
    tierRequired: 3,
    cycleHours: 8,
    inputs: [
      { category: 'Одежда', name: 'Ткань хлопковая и деним в рулонах', quantity: 0.5, unit: 'т', estimatedCost: 4200 },
    ],
    outputs: [
      {
        category: 'Одежда',
        name: 'Костюм деловой классический',
        quantity: 80,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 1.8,
        volume: 0.01,
        baseMarketValue: 240,
      },
    ],
    laborRequirement: 22,
    electricityKWhPerBatch: 340,
    reagentCostPerBatch: 180,
  },

  // ==========================================
  // 3. ЦЕПОЧКА: ЖЕЛЕЗО → СТАЛЬ → ДЕТАЛИ → АВТОЗАПЧАСТИ (Металлургия & Завод автозапчастей)
  // ==========================================
  {
    id: 'recipe_iron_to_steel',
    factoryType: 'metallurgy_plant',
    chainId: 'iron_to_autoparts',
    name: 'Выплавка конструкционной стали',
    tagline: 'Железо → Сталь',
    description: 'Конвертерная плавка железной руды и лома с продувкой кислородом и раскислением ферросплавами.',
    tierRequired: 1,
    cycleHours: 8,
    inputs: [
      { category: 'Металлы', name: 'Арматура строительная стальная', quantity: 3, unit: 'т', estimatedCost: 580 },
    ],
    outputs: [
      {
        category: 'Металлы',
        name: 'Сталь листовая и прокат конструкционный',
        quantity: 2.8,
        unit: 'т',
        quality: 'Промышленный',
        weight: 1000,
        volume: 0.15,
        baseMarketValue: 1250,
      },
    ],
    laborRequirement: 24,
    electricityKWhPerBatch: 950,
    reagentCostPerBatch: 220,
  },
  {
    id: 'recipe_steel_to_machined_parts',
    factoryType: 'metallurgy_plant',
    chainId: 'iron_to_autoparts',
    name: 'Штамповка и ковка механических деталей',
    tagline: 'Сталь → Детали',
    description: 'Горячая объемная штамповка коленвалов, зубчатых венцов, фланцев и прецизионных механических отливок.',
    tierRequired: 2,
    cycleHours: 6,
    inputs: [
      { category: 'Металлы', name: 'Сталь листовая и прокат конструкционный', quantity: 1.5, unit: 'т', estimatedCost: 1250 },
    ],
    outputs: [
      {
        category: 'Комплектующие',
        name: 'Механические детали и заготовки узлов',
        quantity: 200,
        unit: 'шт.',
        quality: 'Промышленный',
        weight: 6.5,
        volume: 0.005,
        baseMarketValue: 35,
      },
    ],
    laborRequirement: 20,
    electricityKWhPerBatch: 680,
    reagentCostPerBatch: 160,
  },
  {
    id: 'recipe_steel_to_autoparts',
    factoryType: 'autoparts_factory',
    chainId: 'iron_to_autoparts',
    name: 'Производство тормозных систем и стоек',
    tagline: 'Сталь + Детали → Автозапчасти',
    description: 'Высокоточная проточка вентилируемых дисков, сборка газомасляных амортизаторов и суппортов.',
    tierRequired: 1,
    cycleHours: 6,
    inputs: [
      { category: 'Металлы', name: 'Сталь листовая и прокат конструкционный', quantity: 0.8, unit: 'т', estimatedCost: 1250 },
      { category: 'Комплектующие', name: 'Механические детали и заготовки узлов', quantity: 60, unit: 'шт.', estimatedCost: 35 },
    ],
    outputs: [
      {
        category: 'Автозапчасти',
        name: 'Тормозные диски и колодки',
        quantity: 40,
        unit: 'комплект',
        quality: 'Оригинал',
        weight: 12,
        volume: 0.015,
        baseMarketValue: 125,
      },
      {
        category: 'Автозапчасти',
        name: 'Амортизаторы подвески',
        quantity: 30,
        unit: 'комплект',
        quality: 'Оригинал',
        weight: 4.5,
        volume: 0.012,
        baseMarketValue: 95,
      },
    ],
    laborRequirement: 18,
    electricityKWhPerBatch: 450,
    reagentCostPerBatch: 140,
  },
  {
    id: 'recipe_powertrain_assembly',
    factoryType: 'autoparts_factory',
    chainId: 'iron_to_autoparts',
    name: 'Сборка двигателей и турбокомпрессоров',
    tagline: 'Детали + Турбины → ДВС и агрегаты',
    description: 'Роботизированная сборка турбированных 4-цилиндровых двигателей, балансировка валов и опрессовка.',
    tierRequired: 3,
    cycleHours: 10,
    inputs: [
      { category: 'Комплектующие', name: 'Механические детали и заготовки узлов', quantity: 120, unit: 'шт.', estimatedCost: 35 },
      { category: 'Комплектующие', name: 'Микрочипы и электронные платы управления', quantity: 20, unit: 'шт.', estimatedCost: 110 },
      { category: 'Масла', name: 'Моторное масло синтетическое', quantity: 150, unit: 'л', estimatedCost: 9 },
    ],
    outputs: [
      {
        category: 'Автозапчасти',
        name: 'Турбокомпрессор в сборе',
        quantity: 25,
        unit: 'комплект',
        quality: 'Премиум',
        weight: 8.5,
        volume: 0.02,
        baseMarketValue: 620,
      },
    ],
    laborRequirement: 24,
    electricityKWhPerBatch: 720,
    reagentCostPerBatch: 300,
  },

  // ==========================================
  // 4. ЦЕПОЧКА: НЕФТЬ → ПЛАСТИК → КОМПОНЕНТЫ → ЭЛЕКТРОНИКА (Электронный завод)
  // ==========================================
  {
    id: 'recipe_oil_to_plastic',
    factoryType: 'electronics_plant',
    chainId: 'oil_to_electronics',
    name: 'Каталитический пиролиз нефти в полимеры',
    tagline: 'Нефть → Пластик',
    description: 'Термический крекинг углеводородов и полимеризация гранулированного полиэтилена и ABS-пластика.',
    tierRequired: 1,
    cycleHours: 6,
    inputs: [
      { category: 'Нефть', name: 'Сырая нефть маркерных сортов', quantity: 12, unit: 'барр.', estimatedCost: 82 },
    ],
    outputs: [
      {
        category: 'Пластик',
        name: 'Полиэтилен гранулированный первичный',
        quantity: 1.4,
        unit: 'т',
        quality: 'Промышленный',
        weight: 1000,
        volume: 1.2,
        baseMarketValue: 1450,
      },
      {
        category: 'Пластик',
        name: 'Инженерные пластики и полимеры',
        quantity: 0.6,
        unit: 'т',
        quality: 'Премиум',
        weight: 1000,
        volume: 1.0,
        baseMarketValue: 2400,
      },
    ],
    laborRequirement: 16,
    electricityKWhPerBatch: 520,
    reagentCostPerBatch: 180,
  },
  {
    id: 'recipe_plastic_to_components',
    factoryType: 'electronics_plant',
    chainId: 'oil_to_electronics',
    name: 'SMT-монтаж плат и микрочипов',
    tagline: 'Пластик + Медь → Микрокомпоненты',
    description: 'Автоматическая пайка многослойных печатных плат PCB, монтаж процессоров и модулей оперативной памяти.',
    tierRequired: 2,
    cycleHours: 6,
    inputs: [
      { category: 'Пластик', name: 'Инженерные пластики и полимеры', quantity: 0.3, unit: 'т', estimatedCost: 2400 },
      { category: 'Металлы', name: 'Медь катодная Grade A', quantity: 0.1, unit: 'т', estimatedCost: 8800 },
    ],
    outputs: [
      {
        category: 'Комплектующие',
        name: 'Микрочипы и электронные платы управления',
        quantity: 180,
        unit: 'шт.',
        quality: 'Оригинал',
        weight: 0.2,
        volume: 0.0005,
        baseMarketValue: 115,
      },
      {
        category: 'Комплектующие',
        name: 'Оперативная память (RAM)',
        quantity: 120,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 0.08,
        volume: 0.0002,
        baseMarketValue: 95,
      },
    ],
    laborRequirement: 22,
    electricityKWhPerBatch: 690,
    reagentCostPerBatch: 280,
  },
  {
    id: 'recipe_components_to_electronics',
    factoryType: 'electronics_plant',
    chainId: 'oil_to_electronics',
    name: 'Сборка смартфонов и Smart TV',
    tagline: 'Компоненты → Потребительская электроника',
    description: 'Финальная сборка флагманских смартфонов, беспроводных наушников и 4K Smart TV с калибровкой экранов.',
    tierRequired: 3,
    cycleHours: 8,
    inputs: [
      { category: 'Комплектующие', name: 'Микрочипы и электронные платы управления', quantity: 80, unit: 'шт.', estimatedCost: 115 },
      { category: 'Комплектующие', name: 'Оперативная память (RAM)', quantity: 40, unit: 'шт.', estimatedCost: 95 },
      { category: 'Пластик', name: 'Инженерные пластики и полимеры', quantity: 0.2, unit: 'т', estimatedCost: 2400 },
    ],
    outputs: [
      {
        category: 'Смартфоны',
        name: 'Смартфон флагманский',
        quantity: 35,
        unit: 'шт.',
        quality: 'Оригинал',
        weight: 0.35,
        volume: 0.0008,
        baseMarketValue: 1100,
      },
      {
        category: 'Электроника',
        name: 'Беспроводные наушники',
        quantity: 60,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 0.25,
        volume: 0.001,
        baseMarketValue: 140,
      },
    ],
    laborRequirement: 26,
    electricityKWhPerBatch: 850,
    reagentCostPerBatch: 420,
  },

  // ==========================================
  // 5. ЦЕПОЧКА: ДРЕВЕСИНА → ДОСКИ → МЕБЕЛЬ (Пищевой завод / Деревообработка)
  // ==========================================
  {
    id: 'recipe_wood_to_lumber',
    factoryType: 'food_factory', // Multi-purpose woodworking module
    chainId: 'wood_to_furniture',
    name: 'Распиловка круглого леса и сушка',
    tagline: 'Древесина → Доски',
    description: 'Ленточнопильная распиловка хвойного кругляка и сушка в конвекционных камерах до влажности 10%.',
    tierRequired: 1,
    cycleHours: 4,
    inputs: [
      { category: 'Древесина', name: 'Пиломатериалы хвойных пород', quantity: 8, unit: 'м³', estimatedCost: 180 },
    ],
    outputs: [
      {
        category: 'Древесина',
        name: 'Плитные материалы и фанера',
        quantity: 6.5,
        unit: 'м³',
        quality: 'Стандарт',
        weight: 680,
        volume: 1.0,
        baseMarketValue: 340,
      },
    ],
    laborRequirement: 10,
    electricityKWhPerBatch: 180,
    reagentCostPerBatch: 50,
  },
  {
    id: 'recipe_lumber_to_furniture',
    factoryType: 'food_factory',
    chainId: 'wood_to_furniture',
    name: 'Производство столов, шкафов и диванов',
    tagline: 'Доски + Ткань → Мебель',
    description: 'ЧПУ-фрезеровка мебельных щитов, кромкооблицовка и обивка эргономичной офисной и домашней мебели.',
    tierRequired: 2,
    cycleHours: 6,
    inputs: [
      { category: 'Древесина', name: 'Плитные материалы и фанера', quantity: 2, unit: 'м³', estimatedCost: 340 },
      { category: 'Одежда', name: 'Ткань хлопковая и деним в рулонах', quantity: 0.15, unit: 'т', estimatedCost: 4200 },
    ],
    outputs: [
      {
        category: 'Мебель',
        name: 'Стол рабочий / переговорный',
        quantity: 25,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 32,
        volume: 0.28,
        baseMarketValue: 380,
      },
      {
        category: 'Мебель',
        name: 'Диван модульный',
        quantity: 10,
        unit: 'шт.',
        quality: 'Стандарт',
        weight: 85,
        volume: 1.4,
        baseMarketValue: 820,
      },
    ],
    laborRequirement: 16,
    electricityKWhPerBatch: 290,
    reagentCostPerBatch: 110,
  },

  // ==========================================
  // 6. ЦЕПОЧКА: АВТОСБОРКА (Автозавод)
  // ==========================================
  {
    id: 'recipe_assemble_sedan',
    factoryType: 'automobile_plant',
    chainId: 'car_assembly',
    name: 'Сборка городского седана «Apex Executive»',
    tagline: 'Автозапчасти + Электроника + Сталь → Седан',
    description: 'Сварка несущего кузова, катафорез, роботизированная установка силовой установки и салона.',
    tierRequired: 1,
    cycleHours: 8,
    inputs: [
      { category: 'Автозапчасти', name: 'Тормозные диски и колодки', quantity: 2, unit: 'комплект', estimatedCost: 125 },
      { category: 'Автозапчасти', name: 'Амортизаторы подвески', quantity: 2, unit: 'комплект', estimatedCost: 95 },
      { category: 'Металлы', name: 'Сталь листовая и прокат конструкционный', quantity: 1.1, unit: 'т', estimatedCost: 1250 },
      { category: 'Комплектующие', name: 'Микрочипы и электронные платы управления', quantity: 15, unit: 'шт.', estimatedCost: 115 },
      { category: 'Шины', name: 'Шина легковая R16-R20', quantity: 4, unit: 'шт.', estimatedCost: 95 },
    ],
    outputs: [
      {
        category: 'Автозапчасти',
        name: 'Готовый автомобиль «Apex Executive Sedan»',
        quantity: 1,
        unit: 'шт.',
        quality: 'Оригинал',
        weight: 1450,
        volume: 12.0,
        baseMarketValue: 28500,
      },
    ],
    laborRequirement: 35,
    electricityKWhPerBatch: 1100,
    reagentCostPerBatch: 650,
  },
  {
    id: 'recipe_assemble_suv',
    factoryType: 'automobile_plant',
    chainId: 'car_assembly',
    name: 'Сборка полноприводного кроссовера «Titan AWD»',
    tagline: 'Автозапчасти + ДВС + Сталь → Кроссовер SUV',
    description: 'Интеграция адаптивной пневмоподвески, полноприводной трансмиссии и кожаного салона.',
    tierRequired: 2,
    cycleHours: 10,
    inputs: [
      { category: 'Автозапчасти', name: 'Тормозные диски и колодки', quantity: 3, unit: 'комплект', estimatedCost: 125 },
      { category: 'Автозапчасти', name: 'Турбокомпрессор в сборе', quantity: 1, unit: 'комплект', estimatedCost: 620 },
      { category: 'Металлы', name: 'Сталь листовая и прокат конструкционный', quantity: 1.6, unit: 'т', estimatedCost: 1250 },
      { category: 'Комплектующие', name: 'Микрочипы и электронные платы управления', quantity: 30, unit: 'шт.', estimatedCost: 115 },
      { category: 'Шины', name: 'Шина легковая R16-R20', quantity: 4, unit: 'шт.', estimatedCost: 95 },
    ],
    outputs: [
      {
        category: 'Автозапчасти',
        name: 'Готовый автомобиль «Titan Grand SUV AWD»',
        quantity: 1,
        unit: 'шт.',
        quality: 'Премиум',
        weight: 2100,
        volume: 16.0,
        baseMarketValue: 49500,
      },
    ],
    laborRequirement: 45,
    electricityKWhPerBatch: 1450,
    reagentCostPerBatch: 950,
  },
];

export const UPGRADE_TIERS: FactoryUpgradeTier[] = [
  {
    level: 1,
    name: 'Уровень 1: Базовый пусковой цех',
    description: 'Первичные полуавтоматические производственные линии с ручным контролем качества.',
    upgradeCost: 0,
    capacityMultiplier: 1.0,
    cycleTimeReduction: 0.0,
    energyEfficiency: 1.0,
    minEmployees: 12,
    maxEmployees: 25,
    dailyRent: 120,
    dailyMaintenance: 80,
    unlockedRecipes: [],
  },
  {
    level: 2,
    name: 'Уровень 2: Механизированная линия',
    description: 'Установка ленточных конвейеров, гидравлических прессов и пневмоинструмента (+35% емкость).',
    upgradeCost: 120000,
    capacityMultiplier: 1.35,
    cycleTimeReduction: 0.08,
    energyEfficiency: 0.95,
    minEmployees: 18,
    maxEmployees: 35,
    dailyRent: 220,
    dailyMaintenance: 140,
    unlockedRecipes: ['recipe_steel_to_machined_parts', 'recipe_plastic_to_components', 'recipe_lumber_to_furniture', 'recipe_assemble_suv'],
  },
  {
    level: 3,
    name: 'Уровень 3: ЧПУ-модули и автоматика',
    description: 'Интеграция ЧПУ-станков, автоматических дозаторов и оптических сканеров брака (+75% емкость).',
    upgradeCost: 280000,
    capacityMultiplier: 1.75,
    cycleTimeReduction: 0.15,
    energyEfficiency: 0.90,
    minEmployees: 24,
    maxEmployees: 50,
    dailyRent: 380,
    dailyMaintenance: 220,
    unlockedRecipes: ['recipe_premium_bakery_pastry', 'recipe_designer_suits', 'recipe_powertrain_assembly', 'recipe_components_to_electronics'],
  },
  {
    level: 4,
    name: 'Уровень 4: Роботизированный комплекс',
    description: 'Манипуляторы промышленной сварки, вакуумный захват и адресная буферизация деталей (+120% емкость).',
    upgradeCost: 550000,
    capacityMultiplier: 2.2,
    cycleTimeReduction: 0.22,
    energyEfficiency: 0.85,
    minEmployees: 30,
    maxEmployees: 70,
    dailyRent: 580,
    dailyMaintenance: 340,
    unlockedRecipes: [],
  },
  {
    level: 5,
    name: 'Уровень 5: Индустрия 4.0 & Smart Factory',
    description: 'Цифровой двойник цеха, предиктивная аналитика поломок и сверхбыстрая переналадка (+180% емкость).',
    upgradeCost: 1100000,
    capacityMultiplier: 2.8,
    cycleTimeReduction: 0.30,
    energyEfficiency: 0.78,
    minEmployees: 40,
    maxEmployees: 95,
    dailyRent: 850,
    dailyMaintenance: 490,
    unlockedRecipes: [],
  },
  {
    level: 6,
    name: 'Уровень 6: Мегафабрика полного цикла',
    description: 'Сверхмощный промышленный хаб с автономной логистикой AGV и рекуперацией тепла (+250% емкость).',
    upgradeCost: 2200000,
    capacityMultiplier: 3.5,
    cycleTimeReduction: 0.38,
    energyEfficiency: 0.70,
    minEmployees: 55,
    maxEmployees: 130,
    dailyRent: 1300,
    dailyMaintenance: 720,
    unlockedRecipes: [],
  },
];

export const PRODUCTION_CHAINS: ProductionChainDefinition[] = [
  {
    id: 'oil_to_electronics',
    title: 'Нефть → Пластик → Компоненты → Электроника',
    subtitle: 'Высокотехнологичный микроэлектронный кластер',
    icon: 'Cpu',
    accentColor: 'from-cyan-500 to-blue-600',
    description: 'Глубокая переработка сырой нефти в инженерные полимеры, монтаж печатных плат и выпуск премиальных гаджетов.',
    associatedFactories: ['electronics_plant'],
    steps: [
      {
        id: 'step_oil',
        name: 'Сырая нефть',
        category: 'Нефть',
        type: 'raw',
        iconName: 'Droplet',
        unit: 'барр.',
        avgMarketPrice: 82,
        inStockQuantity: 0,
      },
      {
        id: 'step_plastic',
        name: 'Пластик & Полимеры',
        category: 'Пластик',
        type: 'intermediate',
        iconName: 'Box',
        factoryType: 'electronics_plant',
        factoryName: 'Электронный завод (Крекинг)',
        recipeName: 'Каталитический пиролиз',
        unit: 'т',
        avgMarketPrice: 1650,
        inStockQuantity: 0,
      },
      {
        id: 'step_components',
        name: 'Микрочипы и платы SMT',
        category: 'Комплектующие',
        type: 'intermediate',
        iconName: 'Cpu',
        factoryType: 'electronics_plant',
        factoryName: 'Электронный завод (SMT цех)',
        recipeName: 'SMT-монтаж плат',
        unit: 'шт.',
        avgMarketPrice: 115,
        inStockQuantity: 0,
      },
      {
        id: 'step_electronics',
        name: 'Смартфоны & Smart TV',
        category: 'Смартфоны',
        type: 'finished',
        iconName: 'Smartphone',
        factoryType: 'electronics_plant',
        factoryName: 'Электронный завод (Сборка)',
        recipeName: 'Сборка смартфонов',
        unit: 'шт.',
        avgMarketPrice: 1100,
        inStockQuantity: 0,
      },
    ],
  },
  {
    id: 'cotton_to_clothing',
    title: 'Хлопок → Ткань → Одежда',
    subtitle: 'Текстильно-швейный кластер',
    icon: 'Shirt',
    accentColor: 'from-purple-500 to-pink-600',
    description: 'Переработка хлопкового сырья в элитный деним и хлопковое полотно с последующим пошивом одежды.',
    associatedFactories: ['textile_factory'],
    steps: [
      {
        id: 'step_cotton',
        name: 'Хлопок-волокно',
        category: 'Хлопок',
        type: 'raw',
        iconName: 'Feather',
        unit: 'т',
        avgMarketPrice: 1950,
        inStockQuantity: 0,
      },
      {
        id: 'step_fabric',
        name: 'Ткань & Деним рулоны',
        category: 'Одежда',
        type: 'intermediate',
        iconName: 'Layers',
        factoryType: 'textile_factory',
        factoryName: 'Текстильная фабрика (Ткачество)',
        recipeName: 'Прядение и ткачество',
        unit: 'т',
        avgMarketPrice: 4200,
        inStockQuantity: 0,
      },
      {
        id: 'step_clothing',
        name: 'Футболки, Джинсы, Костюмы',
        category: 'Одежда',
        type: 'finished',
        iconName: 'Shirt',
        factoryType: 'textile_factory',
        factoryName: 'Текстильная фабрика (Пошив)',
        recipeName: 'Пошив одежды',
        unit: 'шт.',
        avgMarketPrice: 55,
        inStockQuantity: 0,
      },
    ],
  },
  {
    id: 'iron_to_autoparts',
    title: 'Железо → Сталь → Детали → Автозапчасти',
    subtitle: 'Металлургический и автокомпонентный комплекс',
    icon: 'Flame',
    accentColor: 'from-red-500 to-amber-600',
    description: 'Выплавка конструкционных марок стали, ковка механических узлов и сборка автозапчастей.',
    associatedFactories: ['metallurgy_plant', 'autoparts_factory'],
    steps: [
      {
        id: 'step_iron',
        name: 'Металлосырье & Руда',
        category: 'Металлы',
        type: 'raw',
        iconName: 'Boxes',
        unit: 'т',
        avgMarketPrice: 580,
        inStockQuantity: 0,
      },
      {
        id: 'step_steel',
        name: 'Конструкционная сталь',
        category: 'Металлы',
        type: 'intermediate',
        iconName: 'Shield',
        factoryType: 'metallurgy_plant',
        factoryName: 'Металлургический завод',
        recipeName: 'Выплавка стали',
        unit: 'т',
        avgMarketPrice: 1250,
        inStockQuantity: 0,
      },
      {
        id: 'step_machined_parts',
        name: 'Механические детали',
        category: 'Комплектующие',
        type: 'intermediate',
        iconName: 'Cog',
        factoryType: 'metallurgy_plant',
        factoryName: 'Металлургический завод (Штамповка)',
        recipeName: 'Штамповка деталей',
        unit: 'шт.',
        avgMarketPrice: 35,
        inStockQuantity: 0,
      },
      {
        id: 'step_autoparts',
        name: 'Тормоза, Амортизаторы, Турбины',
        category: 'Автозапчасти',
        type: 'finished',
        iconName: 'Wrench',
        factoryType: 'autoparts_factory',
        factoryName: 'Завод автозапчастей',
        recipeName: 'Производство тормозных систем',
        unit: 'комплект',
        avgMarketPrice: 125,
        inStockQuantity: 0,
      },
    ],
  },
  {
    id: 'grain_to_bread',
    title: 'Зерно → Мука → Хлеб',
    subtitle: 'Агропромышленный мукомольный комплекс',
    icon: 'Wheat',
    accentColor: 'from-amber-500 to-yellow-600',
    description: 'Приемка и помол отборной пшеницы, обогащение муки и конвейерная выпечка подового хлеба.',
    associatedFactories: ['food_factory'],
    steps: [
      {
        id: 'step_grain',
        name: 'Пшеница продовольственная',
        category: 'Зерно',
        type: 'raw',
        iconName: 'Wheat',
        unit: 'т',
        avgMarketPrice: 220,
        inStockQuantity: 0,
      },
      {
        id: 'step_flour',
        name: 'Мука высший сорт',
        category: 'Продукты',
        type: 'intermediate',
        iconName: 'Package',
        factoryType: 'food_factory',
        factoryName: 'Пищевой комбинат (Мельница)',
        recipeName: 'Помол зерна в муку',
        unit: 'т',
        avgMarketPrice: 480,
        inStockQuantity: 0,
      },
      {
        id: 'step_bread',
        name: 'Хлеб свежий & Багеты',
        category: 'Продукты',
        type: 'finished',
        iconName: 'Utensils',
        factoryType: 'food_factory',
        factoryName: 'Пищевой комбинат (Пекарня)',
        recipeName: 'Промышленная выпечка хлеба',
        unit: 'шт.',
        avgMarketPrice: 1.9,
        inStockQuantity: 0,
      },
    ],
  },
  {
    id: 'wood_to_furniture',
    title: 'Древесина → Доски → Мебель',
    subtitle: 'Деревообрабатывающий и мебельный кластер',
    icon: 'Hammer',
    accentColor: 'from-emerald-500 to-green-700',
    description: 'Заготовка древесины, камерная сушка пиломатериалов и ЧПУ-производство корпусной и мягкой мебели.',
    associatedFactories: ['food_factory'],
    steps: [
      {
        id: 'step_wood',
        name: 'Пиломатериалы хвойные',
        category: 'Древесина',
        type: 'raw',
        iconName: 'Trees',
        unit: 'м³',
        avgMarketPrice: 180,
        inStockQuantity: 0,
      },
      {
        id: 'step_lumber',
        name: 'Фанера & Доска сухая',
        category: 'Древесина',
        type: 'intermediate',
        iconName: 'Layers',
        factoryType: 'food_factory',
        factoryName: 'Деревообрабатывающий цех',
        recipeName: 'Распиловка и сушка',
        unit: 'м³',
        avgMarketPrice: 340,
        inStockQuantity: 0,
      },
      {
        id: 'step_furniture',
        name: 'Столы, Шкафы, Диваны',
        category: 'Мебель',
        type: 'finished',
        iconName: 'Armchair',
        factoryType: 'food_factory',
        factoryName: 'Мебельная фабрика',
        recipeName: 'Производство мебели',
        unit: 'шт.',
        avgMarketPrice: 380,
        inStockQuantity: 0,
      },
    ],
  },
  {
    id: 'car_assembly',
    title: 'Автозапчасти + Электроника + Сталь → Автомобили',
    subtitle: 'Флагманский автомобилестроительный холдинг',
    icon: 'Car',
    accentColor: 'from-blue-600 to-indigo-700',
    description: 'Полный сборочный цикл седанов и кроссоверов, снабжающий автосалоны, дилерские центры и биржу.',
    associatedFactories: ['automobile_plant'],
    steps: [
      {
        id: 'step_auto_inputs',
        name: 'Автозапчасти & Платы',
        category: 'Автозапчасти',
        type: 'raw',
        iconName: 'Wrench',
        unit: 'комплект',
        avgMarketPrice: 125,
        inStockQuantity: 0,
      },
      {
        id: 'step_car_body',
        name: 'Сварной кузов со сталью',
        category: 'Металлы',
        type: 'intermediate',
        iconName: 'Shield',
        factoryType: 'automobile_plant',
        factoryName: 'Автозавод (Сварочный цех)',
        recipeName: 'Сварка кузова',
        unit: 'т',
        avgMarketPrice: 1250,
        inStockQuantity: 0,
      },
      {
        id: 'step_finished_car',
        name: 'Автомобили «Apex» & «Titan»',
        category: 'Автозапчасти',
        type: 'finished',
        iconName: 'Car',
        factoryType: 'automobile_plant',
        factoryName: 'Автозавод (Главный конвейер)',
        recipeName: 'Сборка легковых автомобилей',
        unit: 'шт.',
        avgMarketPrice: 28500,
        inStockQuantity: 0,
      },
    ],
  },
];
