/**
 * Business Empire: Ultimate
 * Comprehensive 100+ Car Models Catalog
 * Spans 17 distinct automotive categories with authentic specs,
 * engine characteristics, reliability, depreciation, and realistic economics.
 */

import { CarModelTemplate } from '../../types/automotive';

export const CAR_CATALOG: CarModelTemplate[] = [
  // ==================== 1. БЮДЖЕТНЫЕ (BUDGET) ====================
  {
    id: 'car_lada_granta',
    brand: 'Lada',
    model: 'Granta',
    generation: 'FL',
    category: 'budget',
    baseYear: 2021,
    engine: '1.6 8V (90 л.с.)',
    enginePowerHp: 90,
    fuelType: 'petrol',
    transmission: 'manual',
    driveType: 'fwd',
    fuelConsumption: 6.8,
    baseNewPrice: 11000,
    baseMarketPrice: 8200,
    demand: 1.8,
    rarity: 1,
    reliability: 68,
    repairCostFactor: 0.6,
    depreciationPerYear: 0.08,
    description: 'Народный доступный седан с максимально дешевыми запчастями и неприхотливым мотором.',
  },
  {
    id: 'car_renault_logan',
    brand: 'Renault',
    model: 'Logan',
    generation: 'II Stepway',
    category: 'budget',
    baseYear: 2020,
    engine: '1.6 K4M (113 л.с.)',
    enginePowerHp: 113,
    fuelType: 'petrol',
    transmission: 'manual',
    driveType: 'fwd',
    fuelConsumption: 7.2,
    baseNewPrice: 14500,
    baseMarketPrice: 10400,
    demand: 1.6,
    rarity: 1,
    reliability: 82,
    repairCostFactor: 0.7,
    depreciationPerYear: 0.09,
    description: 'Легендарная неубиваемая подвеска B0 и отличная ликвидность в таксопарках и рознице.',
  },
  {
    id: 'car_hyundai_solaris',
    brand: 'Hyundai',
    model: 'Solaris',
    generation: 'II Restyling',
    category: 'budget',
    baseYear: 2021,
    engine: '1.6 Gamma (123 л.с.)',
    enginePowerHp: 123,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 6.6,
    baseNewPrice: 18500,
    baseMarketPrice: 14200,
    demand: 2.1,
    rarity: 1,
    reliability: 84,
    repairCostFactor: 0.8,
    depreciationPerYear: 0.07,
    description: 'Хит продаж вторичного рынка. Идеальный баланс надежности, динамики и ликвидности.',
  },
  {
    id: 'car_kia_rio',
    brand: 'Kia',
    model: 'Rio',
    generation: 'IV X-Line',
    category: 'budget',
    baseYear: 2020,
    engine: '1.6 MPI (123 л.с.)',
    enginePowerHp: 123,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 6.8,
    baseNewPrice: 19000,
    baseMarketPrice: 14800,
    demand: 2.0,
    rarity: 1,
    reliability: 83,
    repairCostFactor: 0.8,
    depreciationPerYear: 0.07,
    description: 'Приподнятый практичный кросс-хэтчбек с высоким спросом среди городских перекупов.',
  },
  {
    id: 'car_vw_polo',
    brand: 'Volkswagen',
    model: 'Polo Liftback',
    generation: 'VI',
    category: 'budget',
    baseYear: 2021,
    engine: '1.4 TSI (125 л.с.) Turbo',
    enginePowerHp: 125,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'fwd',
    fuelConsumption: 5.9,
    baseNewPrice: 21000,
    baseMarketPrice: 16500,
    demand: 1.9,
    rarity: 2,
    reliability: 78,
    repairCostFactor: 0.95,
    depreciationPerYear: 0.08,
    description: 'Турбомотор с роботом DSG — отличная динамика и вместительный багажник-лифтбек.',
  },
  {
    id: 'car_skoda_rapid',
    brand: 'Skoda',
    model: 'Rapid',
    generation: 'II',
    category: 'budget',
    baseYear: 2021,
    engine: '1.6 MPI (110 л.с.)',
    enginePowerHp: 110,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 6.5,
    baseNewPrice: 20000,
    baseMarketPrice: 15800,
    demand: 1.8,
    rarity: 1,
    reliability: 82,
    repairCostFactor: 0.85,
    depreciationPerYear: 0.08,
    description: 'Simply Clever решения, огромный багажник и классический надежный гидроавтомат Aisin.',
  },
  {
    id: 'car_chery_tiggo_2',
    brand: 'Chery',
    model: 'Tiggo 2 Pro',
    generation: 'I',
    category: 'budget',
    baseYear: 2022,
    engine: '1.5 ACTECO (106 л.с.)',
    enginePowerHp: 106,
    fuelType: 'petrol',
    transmission: 'cvt',
    driveType: 'fwd',
    fuelConsumption: 7.4,
    baseNewPrice: 16500,
    baseMarketPrice: 12800,
    demand: 1.4,
    rarity: 1,
    reliability: 70,
    repairCostFactor: 0.75,
    depreciationPerYear: 0.12,
    description: 'Доступный китайский городской паркетник с ярким салоном и мультимедиа сенсором.',
  },

  // ==================== 2. ГОРОДСКИЕ (CITY / HATCHBACK) ====================
  {
    id: 'car_fiat_500',
    brand: 'Fiat',
    model: '500',
    generation: 'Cult',
    category: 'city',
    baseYear: 2019,
    engine: '1.2 Fire (69 л.с.)',
    enginePowerHp: 69,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'fwd',
    fuelConsumption: 5.1,
    baseNewPrice: 19500,
    baseMarketPrice: 13200,
    demand: 1.5,
    rarity: 3,
    reliability: 75,
    repairCostFactor: 0.85,
    depreciationPerYear: 0.08,
    description: 'Культовый итальянский нео-ретро дизайн. Стильный, маневренный и очень легкий в парковке.',
  },
  {
    id: 'car_mini_cooper',
    brand: 'MINI',
    model: 'Cooper S 3D',
    generation: 'F56',
    category: 'city',
    baseYear: 2020,
    engine: '2.0 TwinPower Turbo (192 л.с.)',
    enginePowerHp: 192,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'fwd',
    fuelConsumption: 6.4,
    baseNewPrice: 38000,
    baseMarketPrice: 27500,
    demand: 1.7,
    rarity: 3,
    reliability: 76,
    repairCostFactor: 1.4,
    depreciationPerYear: 0.10,
    description: 'Картинговая управляемость, премиальный салон и дерзкий разгон до сотни за 6.7 сек.',
  },
  {
    id: 'car_vw_golf',
    brand: 'Volkswagen',
    model: 'Golf',
    generation: 'VIII GTI',
    category: 'city',
    baseYear: 2021,
    engine: '2.0 TSI EA888 (245 л.с.)',
    enginePowerHp: 245,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'fwd',
    fuelConsumption: 7.0,
    baseNewPrice: 46000,
    baseMarketPrice: 36000,
    demand: 1.9,
    rarity: 4,
    reliability: 80,
    repairCostFactor: 1.3,
    depreciationPerYear: 0.08,
    description: 'Эталон горячих хэтчбеков с блокировкой дифференциала VAQ и цифровым кокпитом Innovision.',
  },
  {
    id: 'car_toyota_yaris',
    brand: 'Toyota',
    model: 'Yaris GR',
    generation: 'IV 4WD',
    category: 'city',
    baseYear: 2022,
    engine: '1.6 Turbo G16E-GTS (261 л.с.)',
    enginePowerHp: 261,
    fuelType: 'petrol',
    transmission: 'manual',
    driveType: 'awd',
    fuelConsumption: 8.2,
    baseNewPrice: 42000,
    baseMarketPrice: 39500,
    demand: 2.4,
    rarity: 7,
    reliability: 91,
    repairCostFactor: 1.5,
    depreciationPerYear: 0.03,
    description: 'Раллийный омологационный снаряд WRC с полным приводом GR-FOUR. Почти не теряет в цене.',
  },

  // ==================== 3. СЕДАНЫ (SEDAN) ====================
  {
    id: 'car_toyota_camry',
    brand: 'Toyota',
    model: 'Camry',
    generation: 'XV70 Restyling',
    category: 'sedan',
    baseYear: 2021,
    engine: '2.5 Dynamic Force (200 л.с.)',
    enginePowerHp: 200,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 6.9,
    baseNewPrice: 36000,
    baseMarketPrice: 29500,
    demand: 2.3,
    rarity: 1,
    reliability: 94,
    repairCostFactor: 0.9,
    depreciationPerYear: 0.05,
    description: 'Абсолютный король ликвидности. Надежнейший автомат 8-ст и высочайший спрос у покупателей.',
  },
  {
    id: 'car_kia_k5',
    brand: 'Kia',
    model: 'K5',
    generation: 'DL3 GT-Line',
    category: 'sedan',
    baseYear: 2021,
    engine: '2.5 Smartstream (194 л.с.)',
    enginePowerHp: 194,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 7.3,
    baseNewPrice: 33000,
    baseMarketPrice: 25800,
    demand: 1.9,
    rarity: 1,
    reliability: 81,
    repairCostFactor: 0.95,
    depreciationPerYear: 0.08,
    description: 'Футуристичный хищный дизайн оптики "сердцебиение", панорамная крыша и популярность в бизнесе.',
  },
  {
    id: 'car_mazda_6',
    brand: 'Mazda',
    model: '6',
    generation: 'GJ III Restyling',
    category: 'sedan',
    baseYear: 2020,
    engine: '2.5 SkyActiv-G Turbo (231 л.с.)',
    enginePowerHp: 231,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'fwd',
    fuelConsumption: 8.4,
    baseNewPrice: 35000,
    baseMarketPrice: 26500,
    demand: 1.7,
    rarity: 2,
    reliability: 86,
    repairCostFactor: 1.05,
    depreciationPerYear: 0.07,
    description: 'Эмоциональный дизайн KODO, фирменный цвет Soul Red Crystal и отличная турбо-тяга.',
  },
  {
    id: 'car_skoda_superb',
    brand: 'Skoda',
    model: 'Superb',
    generation: 'III Laurin & Klement',
    category: 'sedan',
    baseYear: 2020,
    engine: '2.0 TSI (280 л.с.) 4x4',
    enginePowerHp: 280,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 8.5,
    baseNewPrice: 48000,
    baseMarketPrice: 34500,
    demand: 1.6,
    rarity: 3,
    reliability: 83,
    repairCostFactor: 1.2,
    depreciationPerYear: 0.09,
    description: 'Королевский простор для задних пассажиров, полный привод и разгон до 100 км/ч за 5.6 с.',
  },

  // ==================== 4. УНИВЕРСАЛЫ (WAGON) ====================
  {
    id: 'car_volvo_v60',
    brand: 'Volvo',
    model: 'V60 Cross Country',
    generation: 'II',
    category: 'wagon',
    baseYear: 2021,
    engine: '2.0 D4 AWD (190 л.с.) Diesel',
    enginePowerHp: 190,
    fuelType: 'diesel',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 6.2,
    baseNewPrice: 52000,
    baseMarketPrice: 38500,
    demand: 1.5,
    rarity: 4,
    reliability: 88,
    repairCostFactor: 1.35,
    depreciationPerYear: 0.09,
    description: 'Скандинавская практичность, высокий клиренс 210 мм и эталонные системы безопасности City Safety.',
  },
  {
    id: 'car_audi_a4_avant',
    brand: 'Audi',
    model: 'A4 allroad quattro',
    generation: 'B9 Restyling',
    category: 'wagon',
    baseYear: 2020,
    engine: '2.0 TDI (190 л.с.) quattro',
    enginePowerHp: 190,
    fuelType: 'diesel',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 5.7,
    baseNewPrice: 54000,
    baseMarketPrice: 37000,
    demand: 1.6,
    rarity: 4,
    reliability: 84,
    repairCostFactor: 1.4,
    depreciationPerYear: 0.09,
    description: 'Премиальный вседорожный универсал с легендарным приводом quattro и матричными фарами.',
  },
  {
    id: 'car_subaru_outback',
    brand: 'Subaru',
    model: 'Outback',
    generation: 'VI',
    category: 'wagon',
    baseYear: 2022,
    engine: '2.5 Boxer FB25 (188 л.с.)',
    enginePowerHp: 188,
    fuelType: 'petrol',
    transmission: 'cvt',
    driveType: 'awd',
    fuelConsumption: 7.9,
    baseNewPrice: 45000,
    baseMarketPrice: 36000,
    demand: 1.7,
    rarity: 3,
    reliability: 89,
    repairCostFactor: 1.25,
    depreciationPerYear: 0.07,
    description: 'Симметричный полный привод Symmetrical AWD, комплекс стереокамер EyeSight и надежный оппозитник.',
  },

  // ==================== 5. КРОССОВЕРЫ (CROSSOVER) ====================
  {
    id: 'car_toyota_rav4',
    brand: 'Toyota',
    model: 'RAV4',
    generation: 'XA50',
    category: 'crossover',
    baseYear: 2021,
    engine: '2.5 Dynamic Force (199 л.с.) AWD',
    enginePowerHp: 199,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 7.3,
    baseNewPrice: 42000,
    baseMarketPrice: 34500,
    demand: 2.4,
    rarity: 1,
    reliability: 93,
    repairCostFactor: 0.9,
    depreciationPerYear: 0.05,
    description: 'Самый продаваемый кроссовер в мире. Железная ликвидность и моментальная перепродажа.',
  },
  {
    id: 'car_vw_tiguan',
    brand: 'Volkswagen',
    model: 'Tiguan',
    generation: 'II R-Line',
    category: 'crossover',
    baseYear: 2021,
    engine: '2.0 TSI (220 л.с.) 4Motion',
    enginePowerHp: 220,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 8.4,
    baseNewPrice: 46000,
    baseMarketPrice: 35000,
    demand: 2.0,
    rarity: 2,
    reliability: 82,
    repairCostFactor: 1.15,
    depreciationPerYear: 0.08,
    description: 'Мощный двухлитровый турбомотор, легкий чип-тюнинг до 300+ сил и спортивный обвес R-Line.',
  },
  {
    id: 'car_mazda_cx5',
    brand: 'Mazda',
    model: 'CX-5',
    generation: 'KF Restyling',
    category: 'crossover',
    baseYear: 2021,
    engine: '2.5 Skyactiv-G (194 л.с.) AWD',
    enginePowerHp: 194,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 7.8,
    baseNewPrice: 39000,
    baseMarketPrice: 30500,
    demand: 1.9,
    rarity: 1,
    reliability: 88,
    repairCostFactor: 1.0,
    depreciationPerYear: 0.07,
    description: 'Превосходная шумоизоляция, благородные материалы отделки и надежный гидротрансформатор.',
  },
  {
    id: 'car_geely_monjaro',
    brand: 'Geely',
    model: 'Monjaro',
    generation: 'I Flagship',
    category: 'crossover',
    baseYear: 2023,
    engine: '2.0 Turbo JLH-4G20TD (238 л.с.) AWD',
    enginePowerHp: 238,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 8.5,
    baseNewPrice: 44000,
    baseMarketPrice: 37500,
    demand: 2.3,
    rarity: 2,
    reliability: 85,
    repairCostFactor: 1.1,
    depreciationPerYear: 0.07,
    description: 'Построен на платформе Volvo CMA. Три гигантских экрана на торпедо и 8-ступенчатый Aisin.',
  },

  // ==================== 6. ВНЕДОРОЖНИКИ / SUV ====================
  {
    id: 'car_toyota_lc300',
    brand: 'Toyota',
    model: 'Land Cruiser 300',
    generation: 'GR Sport',
    category: 'suv',
    baseYear: 2022,
    engine: '3.5 V6 Twin-Turbo V35A (415 л.с.)',
    enginePowerHp: 415,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 12.8,
    baseNewPrice: 115000,
    baseMarketPrice: 98000,
    demand: 2.3,
    rarity: 4,
    reliability: 92,
    repairCostFactor: 1.4,
    depreciationPerYear: 0.04,
    description: 'Флагман рамных внедорожников. Система E-KDSS, блокировки всех дифференциалов и статус.',
  },
  {
    id: 'car_lexus_lx600',
    brand: 'Lexus',
    model: 'LX 600',
    generation: 'IV VIP',
    category: 'suv',
    baseYear: 2023,
    engine: '3.5 V6 Twin-Turbo (415 л.с.) AWD',
    enginePowerHp: 415,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 13.2,
    baseNewPrice: 145000,
    baseMarketPrice: 128000,
    demand: 2.0,
    rarity: 5,
    reliability: 91,
    repairCostFactor: 1.6,
    depreciationPerYear: 0.05,
    description: 'Роскошь представительского класса на рамном шасси. Раздельный задний ряд с массажем.',
  },
  {
    id: 'car_land_rover_defender',
    brand: 'Land Rover',
    model: 'Defender 110',
    generation: 'L663 V8 Carpathian',
    category: 'suv',
    baseYear: 2022,
    engine: '5.0 Supercharged V8 (525 л.с.)',
    enginePowerHp: 525,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 14.5,
    baseNewPrice: 135000,
    baseMarketPrice: 105000,
    demand: 1.7,
    rarity: 5,
    reliability: 72,
    repairCostFactor: 1.8,
    depreciationPerYear: 0.11,
    description: 'Неповторимый брутальный силуэт, компрессорный ревущий V8 и пневмоподвеска Terrain Response 2.',
  },
  {
    id: 'car_tank_500',
    brand: 'Tank',
    model: '500',
    generation: 'I Premium',
    category: 'suv',
    baseYear: 2023,
    engine: '3.0 V6 Twin-Turbo (299 л.с.) 4WD',
    enginePowerHp: 299,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 11.5,
    baseNewPrice: 68000,
    baseMarketPrice: 57000,
    demand: 2.1,
    rarity: 3,
    reliability: 84,
    repairCostFactor: 1.15,
    depreciationPerYear: 0.08,
    description: 'Современный рамный тяжеловес с отделкой кожей Nappa, панорамным люком и 9-ст гидроавтоматом.',
  },

  // ==================== 7. ПИКАПЫ (PICKUP) ====================
  {
    id: 'car_ford_f150',
    brand: 'Ford',
    model: 'F-150 Raptor',
    generation: 'XIV Gen 3',
    category: 'pickup',
    baseYear: 2022,
    engine: '3.5 High-Output EcoBoost (450 л.с.)',
    enginePowerHp: 450,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 15.2,
    baseNewPrice: 95000,
    baseMarketPrice: 82000,
    demand: 2.0,
    rarity: 5,
    reliability: 86,
    repairCostFactor: 1.5,
    depreciationPerYear: 0.06,
    description: 'Пустынный покоритель на амортизаторах Fox Live Valve 3.1 и 37-дюймовых колесах BFGoodrich.',
  },
  {
    id: 'car_toyota_hilux',
    brand: 'Toyota',
    model: 'Hilux',
    generation: 'VIII GR Sport',
    category: 'pickup',
    baseYear: 2021,
    engine: '2.8 D-4D (204 л.с.) Diesel',
    enginePowerHp: 204,
    fuelType: 'diesel',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 8.8,
    baseNewPrice: 52000,
    baseMarketPrice: 43000,
    demand: 2.2,
    rarity: 2,
    reliability: 96,
    repairCostFactor: 0.85,
    depreciationPerYear: 0.04,
    description: 'Символ нерушимости. Проедет миллион километров при минимальном базовом обслуживании.',
  },
  {
    id: 'car_ram_1500',
    brand: 'RAM',
    model: '1500 TRX',
    generation: 'V Launch Edition',
    category: 'pickup',
    baseYear: 2022,
    engine: '6.2 Supercharged HEMI V8 (702 л.с.)',
    enginePowerHp: 702,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: '4wd',
    fuelConsumption: 21.0,
    baseNewPrice: 125000,
    baseMarketPrice: 108000,
    demand: 1.9,
    rarity: 6,
    reliability: 82,
    repairCostFactor: 1.9,
    depreciationPerYear: 0.06,
    description: 'Монстр с компрессорным мотором Hellcat. Разгон 0-100 км/ч за 4.5 секунды на любом грунте.',
  },

  // ==================== 8. СПОРТКАРЫ (SPORT) ====================
  {
    id: 'car_porsche_911',
    brand: 'Porsche',
    model: '911 Carrera S',
    generation: '992',
    category: 'sport',
    baseYear: 2021,
    engine: '3.0 Twin-Turbo Boxer 6 (450 л.с.)',
    enginePowerHp: 450,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 10.4,
    baseNewPrice: 155000,
    baseMarketPrice: 138000,
    demand: 2.2,
    rarity: 5,
    reliability: 92,
    repairCostFactor: 1.8,
    depreciationPerYear: 0.04,
    description: 'Икона спорткаров. Робот PDK переключает передачи молниеносно, а развесовка идеальна.',
  },
  {
    id: 'car_bmw_m3',
    brand: 'BMW',
    model: 'M3 Competition',
    generation: 'G80 xDrive',
    category: 'sport',
    baseYear: 2022,
    engine: '3.0 Twin-Turbo S58 (510 л.с.)',
    enginePowerHp: 510,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 10.8,
    baseNewPrice: 105000,
    baseMarketPrice: 92000,
    demand: 2.4,
    rarity: 4,
    reliability: 84,
    repairCostFactor: 1.6,
    depreciationPerYear: 0.06,
    description: 'Легендарный мотор S58 с огромным потенциалом для Stage 2 тюнинга (до 700+ л.с.) и полный привод M xDrive.',
  },
  {
    id: 'car_chevrolet_corvette',
    brand: 'Chevrolet',
    model: 'Corvette Stingray',
    generation: 'C8 3LT',
    category: 'sport',
    baseYear: 2021,
    engine: '6.2 LT2 V8 (495 л.с.) Mid-Engine',
    enginePowerHp: 495,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 12.1,
    baseNewPrice: 90000,
    baseMarketPrice: 78000,
    demand: 2.0,
    rarity: 4,
    reliability: 87,
    repairCostFactor: 1.35,
    depreciationPerYear: 0.06,
    description: 'Первый среднемоторный Корвет в истории. Повадки европейского суперкара по цене маслкара.',
  },
  {
    id: 'car_nissan_gtr',
    brand: 'Nissan',
    model: 'GT-R Nismo',
    generation: 'R35',
    category: 'sport',
    baseYear: 2020,
    engine: '3.8 VR38DETT Twin-Turbo (600 л.с.)',
    enginePowerHp: 600,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 13.5,
    baseNewPrice: 215000,
    baseMarketPrice: 185000,
    demand: 1.9,
    rarity: 6,
    reliability: 88,
    repairCostFactor: 2.1,
    depreciationPerYear: 0.02,
    description: 'Годзилла треков. Карбоновые крылья, керамические тормоза Brembo и ручная сборка двигателей Takumi.',
  },

  // ==================== 9. ПРЕМИУМ (PREMIUM) ====================
  {
    id: 'car_bmw_5_series',
    brand: 'BMW',
    model: '530d xDrive',
    generation: 'G30 LCI M Sport',
    category: 'premium',
    baseYear: 2021,
    engine: '3.0 Inline-6 B57 (249 л.с.) Diesel',
    enginePowerHp: 249,
    fuelType: 'diesel',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 6.3,
    baseNewPrice: 72000,
    baseMarketPrice: 54000,
    demand: 2.3,
    rarity: 2,
    reliability: 90,
    repairCostFactor: 1.3,
    depreciationPerYear: 0.07,
    description: 'Золотой стандарт дизельного премиума. Двигатель B57 сочетает ураганную тягу 650 Нм и расход 6 литров.',
  },
  {
    id: 'car_mercedes_e_class',
    brand: 'Mercedes-Benz',
    model: 'E 300 4MATIC',
    generation: 'W213 Restyling AMG Line',
    category: 'premium',
    baseYear: 2021,
    engine: '2.0 Turbo M264 (258 л.с.)',
    enginePowerHp: 258,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 7.8,
    baseNewPrice: 75000,
    baseMarketPrice: 56000,
    demand: 2.2,
    rarity: 2,
    reliability: 87,
    repairCostFactor: 1.35,
    depreciationPerYear: 0.08,
    description: 'Плавность хода, контурная подсветка 64 цветов, система MBUX и высокий авторитет бренда.',
  },
  {
    id: 'car_audi_a6',
    brand: 'Audi',
    model: 'A6 55 TFSI quattro',
    generation: 'C8 S line',
    category: 'premium',
    baseYear: 2021,
    engine: '3.0 V6 TFSI (340 л.с.) Mild Hybrid',
    enginePowerHp: 340,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 7.9,
    baseNewPrice: 78000,
    baseMarketPrice: 57500,
    demand: 1.8,
    rarity: 3,
    reliability: 83,
    repairCostFactor: 1.4,
    depreciationPerYear: 0.09,
    description: 'Двухэкранный сенсорный кокпит MMI Touch Response, пневмоподвеска и полный привод quattro ultra.',
  },
  {
    id: 'car_bmw_x5',
    brand: 'BMW',
    model: 'X5 xDrive40i',
    generation: 'G05 M Sport',
    category: 'premium',
    baseYear: 2021,
    engine: '3.0 B58 TwinPower Turbo (340 л.с.)',
    enginePowerHp: 340,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 9.2,
    baseNewPrice: 88000,
    baseMarketPrice: 69000,
    demand: 2.5,
    rarity: 3,
    reliability: 89,
    repairCostFactor: 1.45,
    depreciationPerYear: 0.06,
    description: 'Хит перекупов и автосалонов в премиальном сегменте. Мотор B58 признан одним из лучших за десятилетие.',
  },

  // ==================== 10. ЛЮКС (LUXURY) ====================
  {
    id: 'car_mercedes_s_class',
    brand: 'Mercedes-Benz',
    model: 'S 580 4MATIC',
    generation: 'W223 Long',
    category: 'luxury',
    baseYear: 2022,
    engine: '4.0 Biturbo V8 M176 (503 л.с.) EQ Boost',
    enginePowerHp: 503,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 10.9,
    baseNewPrice: 168000,
    baseMarketPrice: 139000,
    demand: 2.1,
    rarity: 5,
    reliability: 86,
    repairCostFactor: 2.2,
    depreciationPerYear: 0.08,
    description: 'Эталон представительского седана. Полноуправляемое шасси, звук Burmester 4D и 3D-приборная панель.',
  },
  {
    id: 'car_rolls_royce_ghost',
    brand: 'Rolls-Royce',
    model: 'Ghost',
    generation: 'II Extended',
    category: 'luxury',
    baseYear: 2022,
    engine: '6.75 Twin-Turbo V12 (571 л.с.)',
    enginePowerHp: 571,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'awd',
    fuelConsumption: 15.8,
    baseNewPrice: 420000,
    baseMarketPrice: 380000,
    demand: 1.4,
    rarity: 9,
    reliability: 93,
    repairCostFactor: 4.5,
    depreciationPerYear: 0.03,
    description: 'Магический ковер-самолет. Подвеска Planar, звездное небо Starlight Headliner и абсолютная тишина.',
  },
  {
    id: 'car_bentley_flying_spur',
    brand: 'Bentley',
    model: 'Flying Spur W12',
    generation: 'III Mulliner',
    category: 'luxury',
    baseYear: 2021,
    engine: '6.0 Twin-Turbo W12 TSI (635 л.с.)',
    enginePowerHp: 635,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 14.7,
    baseNewPrice: 295000,
    baseMarketPrice: 235000,
    demand: 1.6,
    rarity: 7,
    reliability: 88,
    repairCostFactor: 3.2,
    depreciationPerYear: 0.07,
    description: 'Аристократичный британский гран-туризмо со скоростью 333 км/ч и отделкой шпоном редких пород дерева.',
  },

  // ==================== 11. ЭЛЕКТРОМОБИЛИ (EV) ====================
  {
    id: 'car_tesla_model_3',
    brand: 'Tesla',
    model: 'Model 3',
    generation: 'Highland Long Range Dual Motor',
    category: 'ev',
    baseYear: 2023,
    engine: 'Dual Motor AWD (498 л.с.) 82 kWh',
    enginePowerHp: 498,
    fuelType: 'electric',
    transmission: 'single_speed',
    driveType: 'awd',
    fuelConsumption: 14.5,
    baseNewPrice: 49000,
    baseMarketPrice: 41000,
    demand: 2.4,
    rarity: 2,
    reliability: 87,
    repairCostFactor: 1.1,
    depreciationPerYear: 0.08,
    description: 'Обновленная тихая версия Highland с вентиляцией сидений, автопилотом FSD и запасом хода 629 км.',
  },
  {
    id: 'car_tesla_model_s_plaid',
    brand: 'Tesla',
    model: 'Model S Plaid',
    generation: 'Tri-Motor',
    category: 'ev',
    baseYear: 2022,
    engine: 'Tri-Motor Carbon-Wrapped (1020 л.с.)',
    enginePowerHp: 1020,
    fuelType: 'electric',
    transmission: 'single_speed',
    driveType: 'awd',
    fuelConsumption: 18.9,
    baseNewPrice: 110000,
    baseMarketPrice: 86000,
    demand: 2.1,
    rarity: 5,
    reliability: 83,
    repairCostFactor: 1.7,
    depreciationPerYear: 0.09,
    description: 'Разгон 0-100 км/ч за 2.1 секунды. Уничтожает большинство суперкаров в дрэг-рейсинге.',
  },
  {
    id: 'car_porsche_taycan',
    brand: 'Porsche',
    model: 'Taycan Turbo S',
    generation: 'Cross Turismo',
    category: 'ev',
    baseYear: 2022,
    engine: 'Dual Permanent Magnet (761 л.с.) 93.4 kWh',
    enginePowerHp: 761,
    fuelType: 'electric',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 22.4,
    baseNewPrice: 195000,
    baseMarketPrice: 142000,
    demand: 1.8,
    rarity: 6,
    reliability: 88,
    repairCostFactor: 2.4,
    depreciationPerYear: 0.11,
    description: '800-вольтовая архитектура, зарядка за 20 минут и непревзойденная трековая управляемость Porsche.',
  },
  {
    id: 'car_zeekr_001',
    brand: 'Zeekr',
    model: '001',
    generation: 'YOU 4WD 100kWh',
    category: 'ev',
    baseYear: 2023,
    engine: 'Dual Motor (544 л.с.) Пневма',
    enginePowerHp: 544,
    fuelType: 'electric',
    transmission: 'single_speed',
    driveType: 'awd',
    fuelConsumption: 17.2,
    baseNewPrice: 58000,
    baseMarketPrice: 48000,
    demand: 2.5,
    rarity: 3,
    reliability: 89,
    repairCostFactor: 1.25,
    depreciationPerYear: 0.07,
    description: 'Хит импорта и перепродаж. Пневмоподвеска с регулировкой клиренса до 200 мм и двери с электроприводом.',
  },

  // ==================== 12. ГИБРИДЫ (HYBRID / EREV) ====================
  {
    id: 'car_toyota_prius',
    brand: 'Toyota',
    model: 'Prius',
    generation: 'V PHEV',
    category: 'hybrid',
    baseYear: 2023,
    engine: '2.0 Dynamic Force Hybrid (223 л.с.)',
    enginePowerHp: 223,
    fuelType: 'hybrid',
    transmission: 'cvt',
    driveType: 'fwd',
    fuelConsumption: 3.8,
    baseNewPrice: 38000,
    baseMarketPrice: 33000,
    demand: 2.2,
    rarity: 2,
    reliability: 97,
    repairCostFactor: 0.85,
    depreciationPerYear: 0.05,
    description: 'Великолепный футуристичный кузов купе-пропорций, разгон 6.7 с и рекордный минимальный расход топлива.',
  },
  {
    id: 'car_li_auto_l9',
    brand: 'Li Auto',
    model: 'L9 Max',
    generation: 'I Flagship EREV',
    category: 'hybrid',
    baseYear: 2023,
    engine: '1.5 Turbo Range Extender + 2 Motors (449 л.с.)',
    enginePowerHp: 449,
    fuelType: 'hybrid',
    transmission: 'single_speed',
    driveType: 'awd',
    fuelConsumption: 6.8,
    baseNewPrice: 72000,
    baseMarketPrice: 62000,
    demand: 2.6,
    rarity: 4,
    reliability: 90,
    repairCostFactor: 1.35,
    depreciationPerYear: 0.06,
    description: 'Семейный 6-местный кинотеатр на колесах с лидаром, холодильником, проекцией и запасом хода 1315 км.',
  },

  // ==================== 13. КЛАССИЧЕСКИЕ (CLASSIC / RETRO) ====================
  {
    id: 'car_mercedes_w124_e500',
    brand: 'Mercedes-Benz',
    model: 'E 500 (W124)',
    generation: 'Волчок (Porsche Built)',
    category: 'classic',
    baseYear: 1993,
    engine: '5.0 V8 M119 (326 л.с.)',
    enginePowerHp: 326,
    fuelType: 'petrol',
    transmission: 'automatic',
    driveType: 'rwd',
    fuelConsumption: 13.5,
    baseNewPrice: 75000,
    baseMarketPrice: 68000,
    demand: 1.8,
    rarity: 8,
    reliability: 91,
    repairCostFactor: 2.5,
    depreciationPerYear: -0.04, // APPRECIATES in value
    description: 'Культовый "Волчок", собранный вручную на заводе Porsche в Цуффенхаузене. Растет в цене каждый год.',
  },
  {
    id: 'car_bmw_e30_m3',
    brand: 'BMW',
    model: 'M3 (E30)',
    generation: 'Sport Evolution',
    category: 'classic',
    baseYear: 1990,
    engine: '2.5 S14 4-Cylinder (238 л.с.)',
    enginePowerHp: 238,
    fuelType: 'petrol',
    transmission: 'manual',
    driveType: 'rwd',
    fuelConsumption: 10.2,
    baseNewPrice: 40000,
    baseMarketPrice: 95000,
    demand: 2.0,
    rarity: 9,
    reliability: 88,
    repairCostFactor: 2.8,
    depreciationPerYear: -0.06, // APPRECIATES
    description: 'Священный Грааль гоночной серии DTM. Расширенные крылья и чистейшая механическая связь водителя и авто.',
  },
  {
    id: 'car_toyota_supra_mk4',
    brand: 'Toyota',
    model: 'Supra',
    generation: 'Mk4 A80 Twin-Turbo',
    category: 'classic',
    baseYear: 1997,
    engine: '3.0 2JZ-GTE Twin-Turbo (330 л.с.)',
    enginePowerHp: 330,
    fuelType: 'petrol',
    transmission: 'manual',
    driveType: 'rwd',
    fuelConsumption: 12.0,
    baseNewPrice: 45000,
    baseMarketPrice: 85000,
    demand: 2.5,
    rarity: 8,
    reliability: 95,
    repairCostFactor: 2.2,
    depreciationPerYear: -0.05,
    description: 'Легендарный чугунный блок 2JZ, выдерживающий 1000+ л.с. Коллекционный актив наивысшей ценности.',
  },

  // ==================== 14. КОММЕРЧЕСКИЙ ТРАНСПОРТ (COMMERCIAL) ====================
  {
    id: 'car_mercedes_sprinter',
    brand: 'Mercedes-Benz',
    model: 'Sprinter 319 CDI',
    generation: 'III Long High Roof',
    category: 'commercial',
    baseYear: 2021,
    engine: '3.0 V6 CDI OM642 (190 л.с.) Diesel',
    enginePowerHp: 190,
    fuelType: 'diesel',
    transmission: 'automatic',
    driveType: 'rwd',
    fuelConsumption: 9.4,
    baseNewPrice: 62000,
    baseMarketPrice: 48000,
    demand: 2.2,
    rarity: 2,
    reliability: 88,
    repairCostFactor: 1.2,
    depreciationPerYear: 0.07,
    description: 'Флагман коммерческих фургонов. Вместимость 14 кубометров, грузоподъемность до 2 тонн.',
  },
  {
    id: 'car_ford_transit',
    brand: 'Ford',
    model: 'Transit Custom',
    generation: 'IV 350 L3H2',
    category: 'commercial',
    baseYear: 2021,
    engine: '2.0 EcoBlue (170 л.с.) Diesel',
    enginePowerHp: 170,
    fuelType: 'diesel',
    transmission: 'manual',
    driveType: 'fwd',
    fuelConsumption: 8.1,
    baseNewPrice: 44000,
    baseMarketPrice: 33000,
    demand: 2.1,
    rarity: 1,
    reliability: 82,
    repairCostFactor: 0.95,
    depreciationPerYear: 0.08,
    description: 'Рабочая лошадка малого и среднего бизнеса. Огромный выбор доступных аналоговых запчастей.',
  },
  {
    id: 'car_gazelle_next',
    brand: 'GAZ',
    model: 'GAZelle Next',
    generation: 'Euro-5 Long',
    category: 'commercial',
    baseYear: 2021,
    engine: '2.8 Cummins ISF (149 л.с.) Turbo Diesel',
    enginePowerHp: 149,
    fuelType: 'diesel',
    transmission: 'manual',
    driveType: 'rwd',
    fuelConsumption: 10.5,
    baseNewPrice: 28000,
    baseMarketPrice: 21000,
    demand: 2.0,
    rarity: 1,
    reliability: 74,
    repairCostFactor: 0.65,
    depreciationPerYear: 0.09,
    description: 'Основа внутригородской логистики. Дешевый ремонт в любом гараже и максимальная доступность деталей.',
  },

  // ==================== 15. ТЯЖЕЛЫЕ ГРУЗОВИКИ (TRUCK) ====================
  {
    id: 'car_scania_r500',
    brand: 'Scania',
    model: 'R500 Highline',
    generation: 'Next Generation 4x2',
    category: 'truck',
    baseYear: 2021,
    engine: '13.0 DC13 Inline-6 (500 л.с.) 2550 Нм',
    enginePowerHp: 500,
    fuelType: 'diesel',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 26.5,
    baseNewPrice: 155000,
    baseMarketPrice: 122000,
    demand: 2.3,
    rarity: 3,
    reliability: 95,
    repairCostFactor: 1.4,
    depreciationPerYear: 0.06,
    description: 'Королева магистралей. Топовый тягач с коробкой Opticruise и непревзойденной топливной экономичностью.',
  },
  {
    id: 'car_volvo_fh16',
    brand: 'Volvo Trucks',
    model: 'FH16 750 Globetrotter XL',
    generation: 'FH IV 6x4',
    category: 'truck',
    baseYear: 2022,
    engine: '16.1 D16K (750 л.с.) 3550 Нм',
    enginePowerHp: 750,
    fuelType: 'diesel',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 31.0,
    baseNewPrice: 195000,
    baseMarketPrice: 165000,
    demand: 1.8,
    rarity: 5,
    reliability: 96,
    repairCostFactor: 1.6,
    depreciationPerYear: 0.05,
    description: 'Самый мощный серийный грузовик Европы для перевозки негабаритных и сверхтяжелых грузов до 120 тонн.',
  },
  {
    id: 'car_kamaz_54901',
    brand: 'KAMAZ',
    model: '54901 (K5)',
    generation: 'K5 Hi-Tech',
    category: 'truck',
    baseYear: 2022,
    engine: '12.0 R6 KAMAZ-910 (450 л.с.)',
    enginePowerHp: 450,
    fuelType: 'diesel',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 28.0,
    baseNewPrice: 110000,
    baseMarketPrice: 88000,
    demand: 1.9,
    rarity: 2,
    reliability: 81,
    repairCostFactor: 1.0,
    depreciationPerYear: 0.08,
    description: 'Флагманский российский магистральный тягач на каркасе кабины Mercedes Actros с коробкой TraXon.',
  },

  // ==================== 16. СУПЕРКАРЫ (SUPERCAR) ====================
  {
    id: 'car_ferrari_f8',
    brand: 'Ferrari',
    model: 'F8 Tributo',
    generation: 'Mid-Rear V8',
    category: 'supercar',
    baseYear: 2021,
    engine: '3.9 Twin-Turbo V8 F154 (720 л.с.)',
    enginePowerHp: 720,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 12.9,
    baseNewPrice: 310000,
    baseMarketPrice: 280000,
    demand: 2.2,
    rarity: 7,
    reliability: 88,
    repairCostFactor: 3.5,
    depreciationPerYear: 0.03,
    description: 'Дань уважения самому мощному V8 в истории марки. 0-100 за 2.9 с, максималка 340 км/ч и неповторимый рев.',
  },
  {
    id: 'car_lamborghini_huracan',
    brand: 'Lamborghini',
    model: 'Huracan EVO',
    generation: 'LP640-4',
    category: 'supercar',
    baseYear: 2021,
    engine: '5.2 V10 FSI Atmospheric (640 л.с.) 8700 rpm',
    enginePowerHp: 640,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 14.8,
    baseNewPrice: 290000,
    baseMarketPrice: 260000,
    demand: 2.4,
    rarity: 7,
    reliability: 87,
    repairCostFactor: 3.4,
    depreciationPerYear: 0.03,
    description: 'Последний из могикан — атмосферный V10 с оборотами до небес и системой динамики движения LDVI.',
  },
  {
    id: 'car_mclaren_720s',
    brand: 'McLaren',
    model: '720S',
    generation: 'Super Series',
    category: 'supercar',
    baseYear: 2020,
    engine: '4.0 Twin-Turbo V8 M840T (720 л.с.) Carbon MonoCage',
    enginePowerHp: 720,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 12.2,
    baseNewPrice: 320000,
    baseMarketPrice: 245000,
    demand: 1.8,
    rarity: 7,
    reliability: 79,
    repairCostFactor: 3.8,
    depreciationPerYear: 0.08,
    description: 'Карбоновый монокок Proactive Chassis Control II, двери-бабочки и сумасшедшая динамика на прямых.',
  },

  // ==================== 17. ГИПЕРКАРЫ (HYPERCAR) ====================
  {
    id: 'car_bugatti_chiron',
    brand: 'Bugatti',
    model: 'Chiron Super Sport',
    generation: 'W16 Quad-Turbo',
    category: 'hypercar',
    baseYear: 2022,
    engine: '8.0 Quad-Turbo W16 (1600 л.с.) 1600 Нм',
    enginePowerHp: 1600,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'awd',
    fuelConsumption: 22.5,
    baseNewPrice: 3800000,
    baseMarketPrice: 4200000,
    demand: 1.6,
    rarity: 10,
    reliability: 94,
    repairCostFactor: 12.0,
    depreciationPerYear: -0.05, // APPRECIATES
    description: 'Вершина инженерного искусства человечества. Максимальная скорость 440 км/ч, ограниченный тираж.',
  },
  {
    id: 'car_koenigsegg_jesko',
    brand: 'Koenigsegg',
    model: 'Jesko Attack',
    generation: 'LST Mega-Car',
    category: 'hypercar',
    baseYear: 2023,
    engine: '5.0 Twin-Turbo V8 Flat-Plane (1600 л.с. E85)',
    enginePowerHp: 1600,
    fuelType: 'petrol',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 24.0,
    baseNewPrice: 3400000,
    baseMarketPrice: 4100000,
    demand: 1.7,
    rarity: 10,
    reliability: 92,
    repairCostFactor: 11.0,
    depreciationPerYear: -0.06, // APPRECIATES
    description: 'Коробка Light Speed Transmission (9 сцеплений), прижимная сила 1400 кг и углепластиковые диски.',
  },
  {
    id: 'car_rimac_nevera',
    brand: 'Rimac',
    model: 'Nevera',
    generation: 'All-Electric Hypercar',
    category: 'hypercar',
    baseYear: 2023,
    engine: '4 PMAC Motors (1914 л.с.) 2360 Нм 120 kWh',
    enginePowerHp: 1914,
    fuelType: 'electric',
    transmission: 'single_speed',
    driveType: 'awd',
    fuelConsumption: 28.0,
    baseNewPrice: 2500000,
    baseMarketPrice: 2750000,
    demand: 1.5,
    rarity: 10,
    reliability: 90,
    repairCostFactor: 9.5,
    depreciationPerYear: -0.03,
    description: 'Рекордсмен мира по 23 дисциплинам разгона. 0-100 км/ч за 1.81 с, 0-400-0 км/ч за 29.93 секунды.',
  },
  {
    id: 'car_ferrari_laferrari',
    brand: 'Ferrari',
    model: 'LaFerrari',
    generation: 'Aperta HY-KERS',
    category: 'hypercar',
    baseYear: 2016,
    engine: '6.3 V12 + HY-KERS Electric (963 л.с.)',
    enginePowerHp: 963,
    fuelType: 'hybrid',
    transmission: 'robot',
    driveType: 'rwd',
    fuelConsumption: 15.0,
    baseNewPrice: 1500000,
    baseMarketPrice: 3900000,
    demand: 2.1,
    rarity: 10,
    reliability: 91,
    repairCostFactor: 10.0,
    depreciationPerYear: -0.08,
    description: 'Икона "Святой троицы" гиперкаров. Коллекционная редкость, выросшая в цене почти втрое.',
  },
];
