/**
 * Business Empire: Ultimate
 * Master Catalog of 54+ Global Macroeconomic, Commodity & Market Events
 */

import { EconomicEventDefinition } from '../../types/worldEconomy';

export const GLOBAL_ECONOMIC_EVENTS_CATALOG: EconomicEventDefinition[] = [
  // 1. MACROECONOMIC & MONETARY
  {
    id: 'evt_economic_boom',
    title: 'Глобальный экономический бум',
    category: 'macroeconomics',
    severity: 'boom',
    icon: '🚀',
    description: 'Мировая экономика переживает мощную фазу экспансии. Потребительский спрос бьет исторические рекорды, бизнес активно инвестирует в расширение мощностей.',
    consequences: [
      'Рост ВВП: +3.5%',
      'Потребительское доверие: +25 пунктов',
      'Выручка розничных магазинов: +25%',
      'Спрос на автомобили и недвижимость: +20%',
      'Инфляционное давление: +1.2%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      economicGrowthDelta: 3.5,
      consumerConfidenceDelta: 25,
      unemploymentDelta: -1.2,
      inflationDelta: 1.2,
      retailSalesMultiplier: 1.25,
      carSalesMultiplier: 1.20,
      realEstateDemandMultiplier: 1.18,
      stockMarketSentiment: 0.08,
    },
    newsHeadline: 'Рекордный рост мирового ВВП: фондовые рынки обновляют максимумы',
    newsBody: 'Бизнес рапортует о стремительном росте выручки. Розничные сети и автосалоны фиксируют ажиотажный приток покупателей по всему миру.',
    suggestedAction: 'Открывайте новые торговые точки и увеличивайте объем товарных закупок.',
  },
  {
    id: 'evt_deep_recession',
    title: 'Глобальная рецессия и спад спроса',
    category: 'macroeconomics',
    severity: 'critical',
    icon: '📉',
    description: 'Замедление мировой торговли и кризис ликвидности привели к сокращению потребительских расходов и заморозке корпоративных инвестиций.',
    consequences: [
      'Рост ВВП: -4.0% (падение в отрицательную зону)',
      'Потребительское доверие: -30 пунктов',
      'Падение розничных продаж: -25%',
      'Рост безработицы: +2.5%',
      'Снижение спроса на автосалоны: -30%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 30,
    modifiers: {
      economicGrowthDelta: -4.0,
      consumerConfidenceDelta: -30,
      unemploymentDelta: 2.5,
      retailSalesMultiplier: 0.75,
      carSalesMultiplier: 0.70,
      realEstateDemandMultiplier: 0.82,
      stockMarketSentiment: -0.10,
    },
    newsHeadline: 'Мировая экономика погрузилась в рецессию: домохозяйства сокращают траты',
    newsBody: 'Крупнейшие корпорации замораживают найм. Спрос на премиальные товары и авто снизился до многолетних минимумов.',
    suggestedAction: 'Сформируйте подушку ликвидности в кэше и оптимизируйте арендные расходы.',
  },
  {
    id: 'evt_stagflation_shock',
    title: 'Стагфляционный шок',
    category: 'macroeconomics',
    severity: 'major',
    icon: '⚡',
    description: 'Редкое и тяжелое состояние экономики: резкий скачок издержек и инфляции на фоне нулевого или отрицательного роста ВВП.',
    consequences: [
      'Инфляция: +4.5%',
      'Рост ВВП: -2.2%',
      'Операционные издержки заводов: +20%',
      'Падение покупательской способности: -18%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      inflationDelta: 4.5,
      economicGrowthDelta: -2.2,
      productionCostMultiplier: 1.20,
      retailSalesMultiplier: 0.85,
      consumerConfidenceDelta: -20,
    },
    newsHeadline: 'Экономисты бьют тревогу: мир столкнулся со стагфляцией',
    newsBody: 'Цены на сырье и готовую продукцию растут, в то время как потребительские доходы не успевают за инфляцией.',
    suggestedAction: 'Хеджируйте издержки через прямые оптовые контракты на сырье.',
  },
  {
    id: 'evt_cb_rate_hike',
    title: 'Экстренное повышение ставки Центрального Банка',
    category: 'monetary_policy',
    severity: 'major',
    icon: '🏛️',
    description: 'Для борьбы с перегревом цен Центробанк резко поднял ключевую ставку. Кредиты для бизнеса подорожали, доходность по депозитам выросла.',
    consequences: [
      'Ключевая ставка: +3.0%',
      'Ставки по банковским кредитам: +3.5%',
      'Доходность депозитов: +2.8%',
      'Охлаждение рынка акций: -6%',
    ],
    durationDaysMin: 14,
    durationDaysMax: 25,
    modifiers: {
      interestRateDelta: 3.0,
      bankLoanRateModifier: 0.035,
      consumerConfidenceDelta: -8,
      stockMarketSentiment: -0.06,
    },
    newsHeadline: 'Центробанк резко поднял ставку до максимальных значений за 5 лет',
    newsBody: 'Регулятор пытается обуздать инфляцию. Банки синхронно повышают проценты по кредитам для коммерческих предприятий.',
    suggestedAction: 'Временно воздержитесь от новых кредитов и размещайте свободный кэш на депозитах.',
  },
  {
    id: 'evt_cb_rate_cut',
    title: 'Смягчение ДКП и снижение процентных ставок',
    category: 'monetary_policy',
    severity: 'moderate',
    icon: '💸',
    description: 'Центробанк снизил учетную ставку для стимулирования деловой активности. Стоимость заемного капитала упала.',
    consequences: [
      'Ключевая ставка: -2.5%',
      'Кредиты для бизнеса стали дешевле на 2.5%',
      'Рост рынка акций: +7%',
      'Оживление инвестиций в фабрики и недвижимость: +12%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      interestRateDelta: -2.5,
      bankLoanRateModifier: -0.025,
      stockMarketSentiment: 0.07,
      realEstateDemandMultiplier: 1.12,
      economicGrowthDelta: 1.2,
    },
    newsHeadline: 'Кредиты дешевеют: ЦБ объявил о масштабном снижении ставки',
    newsBody: 'Инвесторы и предприниматели получили доступ к дешевой ликвидности. Ожидается всплеск сделок в недвижимости и производстве.',
    suggestedAction: 'Идеальное время для оформления кредитов на строительство заводов и складов.',
  },
  {
    id: 'evt_tax_hike_corporate',
    title: 'Повышение корпоративных налогов',
    category: 'macroeconomics',
    severity: 'moderate',
    icon: '📑',
    description: 'Правительство ввело дополнительный фискальный сбор на сверхприбыль и повысило базовую налоговую ставку на бизнес.',
    consequences: [
      'Чистая прибыль корпораций: -10%',
      'Операционные накладные расходы: +8%',
      'Снижение дивидендных доходностей акций: -1.2%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 26,
    modifiers: {
      productionCostMultiplier: 1.08,
      stockMarketSentiment: -0.04,
      economicGrowthDelta: -0.8,
    },
    newsHeadline: 'Парламент одобрил повышение корпоративного налога на прибыль',
    newsBody: 'Бизнес-ассоциации выражают обеспокоенность ростом фискальной нагрузки на реальный сектор экономики.',
    suggestedAction: 'Сфокусируйтесь на оптимизации издержек и энергоэффективности.',
  },
  {
    id: 'evt_tax_cut_stimulus',
    title: 'Налоговая реформа и пакет стимулов для бизнеса',
    category: 'macroeconomics',
    severity: 'boom',
    icon: '🎁',
    description: 'Принята масштабная программа налоговых каникул и субсидий на новое промышленное оборудование.',
    consequences: [
      'Снижение издержек бизнеса: -7%',
      'Рост рентабельности производства: +12%',
      'Рост ВВП: +1.8%',
      'Потребительское доверие: +15 пунктов',
    ],
    durationDaysMin: 20,
    durationDaysMax: 32,
    modifiers: {
      productionCostMultiplier: 0.93,
      economicGrowthDelta: 1.8,
      consumerConfidenceDelta: 15,
      stockMarketSentiment: 0.06,
    },
    newsHeadline: 'Бизнес получил налоговые льготы: объявлен национальный пакет стимулов',
    newsBody: 'Предприятия смогут реинвестировать сэкономленные налоги в развитие производственных линий и расширение штата.',
    suggestedAction: 'Инвестируйте в новые фабрики и технологии автоматизации.',
  },
  {
    id: 'evt_stock_market_crash',
    title: 'Биржевой обвал: "Черный Вторник"',
    category: 'macroeconomics',
    severity: 'critical',
    icon: '💥',
    description: 'Панические распродажи на мировых фондовых площадках. Котировки акций рухнули на 15-30% за считанные дни.',
    consequences: [
      'Котировки акций: -20% в среднем',
      'Потребительское доверие: -25 пунктов',
      'Падение спроса на люкс-товары: -35%',
      'Ограничение банковского кредитования',
    ],
    durationDaysMin: 12,
    durationDaysMax: 20,
    modifiers: {
      stockMarketSentiment: -0.22,
      consumerConfidenceDelta: -25,
      carSalesMultiplier: 0.75,
      realEstateDemandMultiplier: 0.85,
    },
    newsHeadline: 'Паника на бирже: фондовые индексы зафиксировали рекордное суточное падение',
    newsBody: 'Инвесторы бегут из рисковых активов в защитный кэш. Оценка публичных компаний упала на триллионы долларов.',
    suggestedAction: 'Скупайте недооцененные фундаментально сильные акции на дне рынка.',
  },

  // 2. ENERGY & COMMODITIES (НЕФТЬ, СЫРЬЕ, УРОЖАЙ)
  {
    id: 'evt_oil_crisis_embargo',
    title: 'Нефтяной кризис и эмбарго ОПЕК+',
    category: 'energy_commodities',
    severity: 'critical',
    icon: '🛢️',
    description: 'Геополитическое обострение на Ближнем Востоке парализовало поставки через Ормузский пролив. Мировые цены на нефть взлетели.',
    consequences: [
      'Нефть (Brent): +35% ($115+/bbl)',
      'Стоимость транспортировки и логистики: +25%',
      'Топливные расходы автопарка: +30%',
      'Себестоимость полимеров и пластика: +22%',
      'Инфляция: +2.1%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 30,
    modifiers: {
      oilPricePercentChange: 0.35,
      transportCostPercentChange: 0.25,
      inflationDelta: 2.1,
      productionCostMultiplier: 1.15,
      commodityCategoryPriceMod: [
        { category: 'Нефть', multiplier: 1.35 },
        { category: 'Пластик', multiplier: 1.25 },
        { category: 'Масла', multiplier: 1.30 },
      ],
    },
    newsHeadline: 'Дефицит нефти: котировки Brent пробили $115 за баррель',
    newsBody: 'Транспортные компании поднимают тарифы на грузоперевозки на 20-30%. Заводы по производству пластмасс и химии пересматривают отпускные цены.',
    suggestedAction: 'Закупайте нефтепродукты и сырье заранее до дальнейшего удорожания логистики.',
  },
  {
    id: 'evt_oil_glut_price_war',
    title: 'Ценовая война экспортеров: обвал цен на нефть',
    category: 'energy_commodities',
    severity: 'moderate',
    icon: '⛽',
    description: 'Крупнейшие нефтедобывающие страны не смогли договориться о квотах и начали демпинг. Рынок залит дешевым сырьем.',
    consequences: [
      'Нефть: -30% ($50/bbl)',
      'Стоимость логистики и грузоперевозок: -18%',
      'Снижение производственных издержек: -8%',
      'Торможение инфляции: -1.2%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      oilPricePercentChange: -0.30,
      transportCostPercentChange: -0.18,
      productionCostMultiplier: 0.92,
      inflationDelta: -1.2,
      commodityCategoryPriceMod: [
        { category: 'Нефть', multiplier: 0.70 },
        { category: 'Пластик', multiplier: 0.82 },
        { category: 'Масла', multiplier: 0.75 },
      ],
    },
    newsHeadline: 'Обвал нефтяных котировок: бензин и дизель рекордно подешевели',
    newsBody: 'Логистические расходы предприятий существенно снизились, что дало импульс производственному сектору.',
    suggestedAction: 'Используйте дешевую логистику для межрегиональных поставок и заполнения удаленных складов.',
  },
  {
    id: 'evt_semiconductor_shortage',
    title: 'Глобальный дефицит микрочипов и полупроводников',
    category: 'industry_tech',
    severity: 'major',
    icon: '💻',
    description: 'Авария на ключевых тайваньских фабриках чипов вызвала острую нехватку микроэлектроники для гаджетов и автопрома.',
    consequences: [
      'Цены на смартфоны, ПК и компоненты: +35%',
      'Цены на новые автомобили: +20%',
      'Сроки поставки авто и электроники: +50%',
      'Высокая маржа у магазинов электроники: +30%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      carSalesMultiplier: 1.15,
      commodityCategoryPriceMod: [
        { category: 'Электроника', multiplier: 1.35 },
        { category: 'Смартфоны', multiplier: 1.30 },
        { category: 'Компьютеры', multiplier: 1.40 },
        { category: 'Комплектующие', multiplier: 1.45 },
        { category: 'Бытовая техника', multiplier: 1.22 },
      ],
    },
    newsHeadline: 'Кризис полупроводников: заводы электроники останавливают сборку',
    newsBody: 'Торговые сети сообщают об опустении полок с флагманскими смартфонами и видеокартами. Цены на спотовом рынке бьют рекорды.',
    suggestedAction: 'Продавайте накопленные складские запасы электроники с повышенной розничной наценкой.',
  },
  {
    id: 'evt_crop_failure_drought',
    title: 'Аномальная засуха и неурожай зерновых',
    category: 'energy_commodities',
    severity: 'major',
    icon: '🌾',
    description: 'Жестокая засуха в ключевых аграрных регионах уничтожила до 30% посевов. Мировые цены на пшеницу, зерно и продукты взлетели.',
    consequences: [
      'Зерно и агросырье: +40%',
      'Продукты питания и бакалея: +25%',
      'Выручка продуктовых супермаркетов: +18%',
      'Инфляция продовольственной корзины: +2.5%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      inflationDelta: 1.8,
      commodityCategoryPriceMod: [
        { category: 'Зерно', multiplier: 1.45 },
        { category: 'Продукты', multiplier: 1.25 },
        { category: 'Напитки', multiplier: 1.18 },
      ],
    },
    newsHeadline: 'Угроза продовольственного дефицита: цены на зерно и муку подскочили на 40%',
    newsBody: 'Продуктовые супермаркеты фиксируют рост среднего чека, а оптовые базы борются за остатки зерна на элеваторах.',
    suggestedAction: 'Сфокусируйте оптовую торговлю на продуктах питания и агросырье.',
  },
  {
    id: 'evt_bumper_harvest_surplus',
    title: 'Рекордный урожай и избыток продовольствия',
    category: 'energy_commodities',
    severity: 'minor',
    icon: '🚜',
    description: 'Идеальные погодные условия привели к небывалому сбору зерна и овощей. Оптовые цены на сельхозпродукцию пошли вниз.',
    consequences: [
      'Зерно: -30%',
      'Продукты питания: -15%',
      'Снижение себестоимости пищевых фабрик: -20%',
      'Снижение общей инфляции: -0.8%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      inflationDelta: -0.8,
      commodityCategoryPriceMod: [
        { category: 'Зерно', multiplier: 0.70 },
        { category: 'Продукты', multiplier: 0.85 },
      ],
    },
    newsHeadline: 'Аграрный триумф: элеваторы переполнены рекордным урожаем',
    newsBody: 'Оптовые цены на базовые продукты упали. Пищевые комбинаты работают с максимальной маржинальностью.',
    suggestedAction: 'Закупайте зерно по минимальным ценам для производства готовых продуктов.',
  },
  {
    id: 'evt_steel_metals_supercycle',
    title: 'Металлургический суперцикл: взлет цен на сталь и медь',
    category: 'energy_commodities',
    severity: 'major',
    icon: '🏗️',
    description: 'Масштабные инфраструктурные стройки в Азии и Америке вызвали дефицит металлопроката, арматуры и цветных металлов.',
    consequences: [
      'Металлы и прокат: +35%',
      'Стройматериалы: +22%',
      'Удорожание строительства новых фабрик и зданий: +15%',
      'Сверхприбыли металлургических холдингов',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      productionCostMultiplier: 1.12,
      commodityCategoryPriceMod: [
        { category: 'Металлы', multiplier: 1.35 },
        { category: 'Стройматериалы', multiplier: 1.22 },
        { category: 'Инструменты', multiplier: 1.18 },
      ],
    },
    newsHeadline: 'Металлургический бум: тонна стали и меди достигла десятилетних пиков',
    newsBody: 'Строительные и машиностроительные компании закладывают в сметы возросшие затраты на металлоконструкции.',
    suggestedAction: 'Торгуйте металлами на оптовой бирже с высокой маржой.',
  },
  {
    id: 'evt_plastics_chemical_surge',
    title: 'Дефицит полимеров и химического сырья',
    category: 'energy_commodities',
    severity: 'moderate',
    icon: '🧪',
    description: 'Внеплановые остановки нефтехимических крекинг-установок привели к дефициту полипропилена и синтетических смол.',
    consequences: [
      'Пластик и полимеры: +30%',
      'Автозапчасти и шины: +18%',
      'Упаковочные материалы: +15%',
    ],
    durationDaysMin: 14,
    durationDaysMax: 24,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Пластик', multiplier: 1.30 },
        { category: 'Автозапчасти', multiplier: 1.18 },
        { category: 'Шины', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Химическая промышленность бьет тревогу из-за нехватки полимеров',
    newsBody: 'Производители упаковки, автокомпонентов и бытовой техники сталкиваются с ростом стоимости гранул пластика.',
    suggestedAction: 'Переориентируйте поставки пластика на промышленные заводы-потребители.',
  },
  {
    id: 'evt_timber_deficit',
    title: 'Кризис лесозаготовок и дефицит древесины',
    category: 'energy_commodities',
    severity: 'moderate',
    icon: '🌲',
    description: 'Ограничения на вырубку и лесные пожары сократили предложение качественного пиловочника на мировом рынке.',
    consequences: [
      'Древесина и брус: +35%',
      'Мебель: +20%',
      'Стройматериалы: +12%',
    ],
    durationDaysMin: 14,
    durationDaysMax: 26,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Древесина', multiplier: 1.35 },
        { category: 'Мебель', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Цены на пиломатериалы подскочили: мебельные фабрики поднимают цены',
    newsBody: 'Рост стоимости круглого леса отразился на розничных ценах в мебельных и строительных гипермаркетах.',
    suggestedAction: 'Продавайте складские запасы древесины мебельным фабрикам.',
  },

  // 3. LOGISTICS & SUPPLY CHAINS
  {
    id: 'evt_suez_canal_blockage',
    title: 'Блокировка морских торговых проливов',
    category: 'logistics_supply',
    severity: 'critical',
    icon: '🚢',
    description: 'Крупный контейнеровоз сел на мель в ключевом судоходном канале. Сотни судов вынуждены идти в обход материка.',
    consequences: [
      'Стоимость морских перевозок: +40%',
      'Общие транспортные расходы: +30%',
      'Задержка поставок импортных товаров: +100%',
      'Дефицит импортной одежды, обуви и гаджетов: +15%',
    ],
    durationDaysMin: 12,
    durationDaysMax: 22,
    modifiers: {
      transportCostPercentChange: 0.30,
      retailSalesMultiplier: 0.92,
      commodityCategoryPriceMod: [
        { category: 'Одежда', multiplier: 1.18 },
        { category: 'Обувь', multiplier: 1.18 },
        { category: 'Электроника', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Транспортный коллапс: паралич Суэцкого канала остановил 12% мировой торговли',
    newsBody: 'Ставки фрахта взлетели. Тысячи контейнеров застряли на рейде. Товарные склады испытывают перебои с пополнением.',
    suggestedAction: 'Полагайтесь на внутренние склады и локальный автомобильный транспорт.',
  },
  {
    id: 'evt_trucking_strike',
    title: 'Общенациональная забастовка дальнобойщиков',
    category: 'logistics_supply',
    severity: 'major',
    icon: '🚛',
    description: 'Профсоюзы водителей грузовиков остановили перевозки, требуя индексации тарифов и компенсации цен на дизель.',
    consequences: [
      'Стоимость автоперевозок: +35%',
      'Складские расходы на хранение: +20%',
      'Торможение пополнения магазинов',
    ],
    durationDaysMin: 10,
    durationDaysMax: 18,
    modifiers: {
      transportCostPercentChange: 0.35,
      productionCostMultiplier: 1.10,
    },
    newsHeadline: 'Трассы перекрыты: забастовка перевозчиков парализовала доставку товаров',
    newsBody: 'Ритейлеры вынуждены платить двойные тарифы частным экспедиторам за срочные рейсы.',
    suggestedAction: 'Используйте собственный автопарк грузовиков для бесперебойных поставок.',
  },
  {
    id: 'evt_customs_tariff_war',
    title: 'Торговая война и ввод заградительных пошлин',
    category: 'logistics_supply',
    severity: 'major',
    icon: '🛡️',
    description: 'Ведущие державы ввели 25% взаимные тарифы на импорт промышленного оборудования, металлов и электроники.',
    consequences: [
      'Импортные товары подорожали на 20-25%',
      'Снижение мировой торговли: -15%',
      'Рост спроса на локальных производителей: +18%',
      'Инфляция: +1.5%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      inflationDelta: 1.5,
      economicGrowthDelta: -1.1,
      commodityCategoryPriceMod: [
        { category: 'Электроника', multiplier: 1.22 },
        { category: 'Автозапчасти', multiplier: 1.25 },
        { category: 'Одежда', multiplier: 1.15 },
      ],
    },
    newsHeadline: 'Эскалация торговой войны: новые тарифы вступили в силу в полночь',
    newsBody: 'Импортеры перекладывают пошлины на плечи конечных покупателей. Локальные заводы получают конкурентное преимущество.',
    suggestedAction: 'Развивайте собственные производственные фабрики внутри страны.',
  },
  {
    id: 'evt_global_port_congestion',
    title: 'Контейнерный кризис и перегрузка морских портов',
    category: 'logistics_supply',
    severity: 'moderate',
    icon: '📦',
    description: 'Очереди на разгрузку в крупнейших портах достигли 3 недель из-за нехватки портовых кранов и складских площадей.',
    consequences: [
      'Логистические расходы: +20%',
      'Рост цен на аренду складов: +15%',
      'Повышенный спрос на готовые товары на складах',
    ],
    durationDaysMin: 14,
    durationDaysMax: 25,
    modifiers: {
      transportCostPercentChange: 0.20,
      commodityCategoryPriceMod: [
        { category: 'Бытовая техника', multiplier: 1.15 },
        { category: 'Мебель', multiplier: 1.12 },
      ],
    },
    newsHeadline: 'Порты не справляются с потоком грузов: дефицит порожних контейнеров',
    newsBody: 'Компании, обладающие большими складскими площадями, выигрывают за счет наличия товара.',
    suggestedAction: 'Сдавайте свободные площади складов в субаренду по повышенным ставкам.',
  },

  // 4. INDUSTRY, TECH & INNOVATION
  {
    id: 'evt_ai_industrial_breakthrough',
    title: 'Прорыв в генеративном ИИ и промышленной автоматизации',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🤖',
    description: 'Внедрение новых нейросетевых алгоритмов управления производством повысило выработку заводов на 25% и сократило брак.',
    consequences: [
      'Производительность фабрик: +25%',
      'Снижение производственных издержек: -15%',
      'Взлет акций технологических компаний: +18%',
      'Рост спроса на R&D и патенты: +30%',
    ],
    durationDaysMin: 22,
    durationDaysMax: 40,
    modifiers: {
      factoryOutputMultiplier: 1.25,
      productionCostMultiplier: 0.85,
      stockMarketSentiment: 0.12,
      economicGrowthDelta: 1.5,
    },
    newsHeadline: 'ИИ-революция в промышленности: производительность фабрик побила рекорд',
    newsBody: 'Автоматизированные конвейеры снижают себестоимость выпуска продукции. Технологический сектор лидирует на бирже.',
    suggestedAction: 'Инвестируйте в технологии и открывайте высокотехнологичные фабрики.',
  },
  {
    id: 'evt_ev_mass_adoption',
    title: 'Ажиотажный спрос на электромобили (EV Boom)',
    category: 'industry_tech',
    severity: 'boom',
    icon: '⚡',
    description: 'Государственные субсидии и удешевление батарей вызвали лавинообразный спрос на электрокары и гибриды.',
    consequences: [
      'Продажи автомобилей в автосалонах: +35%',
      'Спрос на аккумуляторы и литий: +50%',
      'Снижение потребления бензина: -8%',
      'Рост рентабельности автодилеров: +25%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      carSalesMultiplier: 1.35,
      commodityCategoryPriceMod: [
        { category: 'Автозапчасти', multiplier: 1.25 },
        { category: 'Комплектующие', multiplier: 1.30 },
      ],
    },
    newsHeadline: 'Бум электромобилей: очереди в автосалонах растянулись на месяцы',
    newsBody: 'Автодилеры фиксируют рекордную маржу на продаже электрокаров и премиальных гибридных моделей.',
    suggestedAction: 'Закупайте современные автомобили и электрокары в автосалоны.',
  },
  {
    id: 'evt_mega_corp_bankruptcy',
    title: 'Банкротство транснационального ритейл-гиганта',
    category: 'industry_tech',
    severity: 'major',
    icon: '🏛️',
    description: 'Крупнейшая мировая торговая сеть объявила о несостоятельности из-за долгов. Освободились огромные доли рынка.',
    consequences: [
      'Передел рынка ритейла в пользу конкурентов: +20% к выручке',
      'Распродажа товарных остатков с дисконтом 40%',
      'Падение ставок аренды торговых площадей',
    ],
    durationDaysMin: 14,
    durationDaysMax: 26,
    modifiers: {
      retailSalesMultiplier: 1.20,
      stockMarketSentiment: -0.05,
    },
    newsHeadline: 'Крах ритейл-империи: крупнейшая сеть закрывает сотни гипермаркетов',
    newsBody: 'Освободившиеся торговые локации и покупательский трафик перераспределяются между независимыми игроками.',
    suggestedAction: 'Занимайте освободившиеся ниши и открывайте новые магазины.',
  },
  {
    id: 'evt_cyberattack_banking',
    title: 'Масштабная кибератака на банковскую систему',
    category: 'industry_tech',
    severity: 'major',
    icon: '👾',
    description: 'Хакерская группировка атаковала процессинговые центры межбанковских платежей. Проведение транзакций замедлилось.',
    consequences: [
      'Временное замораживание кредитных линий',
      'Падение доверия потребителей: -15 пунктов',
      'Задержки в расчетах с контрагентами',
    ],
    durationDaysMin: 8,
    durationDaysMax: 15,
    modifiers: {
      consumerConfidenceDelta: -15,
      bankLoanRateModifier: 0.02,
      stockMarketSentiment: -0.08,
    },
    newsHeadline: 'Сбой межбанковской сети: кибератака нарушила расчеты в десятках стран',
    newsBody: 'Банки переходят на резервные защищенные протоколы. Финансовые регуляторы проводят аудит кибербезопасности.',
    suggestedAction: 'Держите операционный запас наличных средств на основном счете.',
  },
  {
    id: 'evt_biotech_medical_boom',
    title: 'Биотехнологический прорыв: новые медицинские препараты',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🧬',
    description: 'Успешные клинические испытания революционной платформы препаратов привели к взрывному росту фармацевтического сектора.',
    consequences: [
      'Взлет акций фармкомпаний: +25%',
      'Рост спроса на специализированное сырье',
      'Общий подъем фондового рынка',
    ],
    durationDaysMin: 18,
    durationDaysMax: 30,
    modifiers: {
      stockMarketSentiment: 0.09,
      economicGrowthDelta: 1.0,
    },
    newsHeadline: 'Медицинский триумф: зарегистрирована новая терапевтическая платформа',
    newsBody: 'Инвесторы вкладывают миллиарды в фарминдустрию. Ожидается увеличение продолжительности активной жизни населения.',
    suggestedAction: 'Приобретайте акции фармацевтических и биотехнологических компаний.',
  },

  // 5. RETAIL, CONSUMER & REAL ESTATE
  {
    id: 'evt_consumer_spending_frenzy',
    title: 'Потребительская эйфория и сезон супершопинга',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '🛍️',
    description: 'Рост реальных зарплат и оптимизм покупателей привели к рекордному заполнению торговых центров и бутиков.',
    consequences: [
      'Потребительское доверие: +30 пунктов (индекс 130+)',
      'Выручка всех розничных магазинов: +30%',
      'Продажи одежды, обуви и косметики: +35%',
      'Продажи ресторанов и кафе: +25%',
    ],
    durationDaysMin: 14,
    durationDaysMax: 25,
    modifiers: {
      consumerConfidenceDelta: 30,
      retailSalesMultiplier: 1.30,
      carSalesMultiplier: 1.18,
      commodityCategoryPriceMod: [
        { category: 'Одежда', multiplier: 1.20 },
        { category: 'Обувь', multiplier: 1.20 },
        { category: 'Смартфоны', multiplier: 1.15 },
      ],
    },
    newsHeadline: 'Шопинг-лихорадка: торговые центры фиксируют рекордный наплыв посетителей',
    newsBody: 'Покупатели с готовностью тратят сбережения. Розничные сети рапортуют о максимальной дневной выручке за всю историю.',
    suggestedAction: 'Максимизируйте товарные остатки на полках розничных магазинов.',
  },
  {
    id: 'evt_luxury_goods_craze',
    title: 'Бум роскоши: взрывной спрос на люкс и суперкары',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '👑',
    description: 'Рост числа сверхбогатых инвесторов вызвал беспрецедентный спрос на элитную недвижимость, люксовые часы и спорткары.',
    consequences: [
      'Спрос на элитные авто: +45%',
      'Аренда элитной недвижимости: +25%',
      'Маржа ювелирных и люкс-бутиков: +40%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      carSalesMultiplier: 1.40,
      realEstateDemandMultiplier: 1.25,
      commodityCategoryPriceMod: [
        { category: 'Одежда', multiplier: 1.30 },
      ],
    },
    newsHeadline: 'Рынок роскоши на пике: суперкары и элитные пентхаусы раскупаются за часы',
    newsBody: 'Премиальный сегмент демонстрирует рекордную устойчивость и маржинальность.',
    suggestedAction: 'Приобретайте элитную коммерческую недвижимость и премиальные спорткары.',
  },
  {
    id: 'evt_real_estate_bubble',
    title: 'Ипотечный бум и взлет цен на недвижимость',
    category: 'real_estate',
    severity: 'major',
    icon: '🏢',
    description: 'Льготные кредиты разогнали стоимость квадратного метра жилой и коммерческой недвижимости до исторических пиков.',
    consequences: [
      'Рыночная стоимость объектов недвижимости: +25%',
      'Арендные ставки коммерческих помещений: +20%',
      'Заполняемость арендаторами: 95-100%',
      'Удорожание покупки новых зданий: +25%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      realEstateDemandMultiplier: 1.25,
      economicGrowthDelta: 1.2,
      inflationDelta: 1.0,
    },
    newsHeadline: 'Рынок недвижимости бьет рекорды: арендные ставки выросли на 20%',
    newsBody: 'Инвесторы активно скупают квадратные метры в мегаполисах, рассчитывая на продолжение роста капитализации.',
    suggestedAction: 'Сдавайте всю имеющуюся недвижимость в аренду по максимальным ставкам.',
  },
  {
    id: 'evt_housing_cooling',
    title: 'Охлаждение рынка жилья и коррекция цен',
    category: 'real_estate',
    severity: 'moderate',
    icon: '📉',
    description: 'Высокие ставки по ипотеке охладили спрос на покупку недвижимости. Собственники вынуждены снижать аренду.',
    consequences: [
      'Цены на покупку недвижимости: -15%',
      'Арендные поступления: -12%',
      'Увеличение времени поиска арендаторов',
    ],
    durationDaysMin: 16,
    durationDaysMax: 28,
    modifiers: {
      realEstateDemandMultiplier: 0.88,
      consumerConfidenceDelta: -10,
    },
    newsHeadline: 'Коррекция в недвижимости: цены на покупку зданий снизились на 15%',
    newsBody: 'Для покупателей с кэшем открывается отличное окно возможностей для покупки объектов со скидкой.',
    suggestedAction: 'Выкупайте качественные объекты коммерческой недвижимости по дисконтным ценам.',
  },
  {
    id: 'evt_labor_shortage_wage_spike',
    title: 'Острый дефицит рабочей силы и рост зарплат',
    category: 'macroeconomics',
    severity: 'major',
    icon: '👥',
    description: 'Рекордно низкая безработица создала жестокую конкуренцию за квалифицированных сотрудников между корпорациями.',
    consequences: [
      'Уровень безработицы упал до 2.5%',
      'Зарплатные ожидания персонала: +20%',
      'Расходы на содержание штата: +20%',
      'Сложность быстрого найма специалистов',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      unemploymentDelta: -2.0,
      inflationDelta: 1.4,
      productionCostMultiplier: 1.12,
      consumerConfidenceDelta: 12,
    },
    newsHeadline: 'Кадровый голод: компании повышают зарплаты на 20% для удержания сотрудников',
    newsBody: 'Соискатели диктуют условия на рынке труда. Предприятия вынуждены увеличивать фонд оплаты труда.',
    suggestedAction: 'Автоматизируйте рабочие процессы с помощью R&D технологий.',
  },
  {
    id: 'evt_mass_migration_influx',
    title: 'Приток трудовых ресурсов и стабилизация зарплат',
    category: 'macroeconomics',
    severity: 'moderate',
    icon: '🧳',
    description: 'Упрощение визовых режимов и трудовой мобильности привлекло сотни тысяч квалифицированных специалистов.',
    consequences: [
      'Расходы на персонал снизились на 10%',
      'Упростился найм рабочих на заводы и склады',
      'Рост базового потребления товаров: +10%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      unemploymentDelta: 1.5,
      productionCostMultiplier: 0.92,
      retailSalesMultiplier: 1.08,
      inflationDelta: -0.6,
    },
    newsHeadline: 'Рынок труда стабилизировался: приток специалистов снизил затраты бизнеса на найм',
    newsBody: 'Производственные компании смогли полностью укомплектовать смены на заводах и складах.',
    suggestedAction: 'Нанимайте дополнительный персонал для расширения производственных линий.',
  },
  {
    id: 'evt_black_friday_frenzy',
    title: 'Глобальная распродажа: "Черная Пятница"',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '🏷️',
    description: 'Ежегодный глобальный марафон скидок. Миллионы покупателей штурмуют онлайн и офлайн магазины.',
    consequences: [
      'Трафик в розничных магазинах: +50%',
      'Объем продаж электроники и одежды: +60%',
      'Высокая скорость оборачиваемости складских запасов',
    ],
    durationDaysMin: 7,
    durationDaysMax: 12,
    modifiers: {
      consumerConfidenceDelta: 25,
      retailSalesMultiplier: 1.50,
      commodityCategoryPriceMod: [
        { category: 'Электроника', multiplier: 0.90 },
        { category: 'Одежда', multiplier: 0.85 },
        { category: 'Обувь', multiplier: 0.85 },
      ],
    },
    newsHeadline: 'Черная Пятница бьет рекорды: суточный оборот ритейла превысил годовые средние',
    newsBody: 'Очереди на кассах не иссякают. Склады работают в круглосуточном режиме на отгрузку.',
    suggestedAction: 'Заранее наполните магазины популярными товарами.',
  },
  {
    id: 'evt_tourism_travel_boom',
    title: 'Глобальный туристический бум',
    category: 'retail_consumer',
    severity: 'moderate',
    icon: '✈️',
    description: 'Открытие новых авиамаршрутов и снятие ограничений привели к рекордному потоку туристов и деловых путешественников.',
    consequences: [
      'Заполняемость отелей и арендной недвижимости: +30%',
      'Выручка ресторанов, кафе и сувенирных лавок: +30%',
      'Рост спроса на аренду авто: +25%',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      realEstateDemandMultiplier: 1.20,
      retailSalesMultiplier: 1.15,
      carSalesMultiplier: 1.15,
      consumerConfidenceDelta: 15,
    },
    newsHeadline: 'Аэропорты и отели переполнены: туристический сектор показывает рекордные доходы',
    newsBody: 'Ресторанный бизнес и владельцы апартаментов фиксируют максимальную загрузку за последние годы.',
    suggestedAction: 'Инвестируйте в недвижимость туристических локаций и ресторанный бизнес.',
  },

  // 6. GEOPOLITICS & GLOBAL SHIFTS
  {
    id: 'evt_gov_infra_program',
    title: 'Государственная программа мега-инфраструктуры',
    category: 'geopolitics',
    severity: 'boom',
    icon: '🌉',
    description: 'Правительство выделило рекордный триллионный бюджет на строительство мостов, портов, железных дорог и скоростных магистралей.',
    consequences: [
      'Спрос на стройматериалы и металлы: +35%',
      'Рост заказов для тяжелой промышленности: +25%',
      'Ускорение роста ВВП: +2.0%',
      'Создание сотен тысяч рабочих мест',
    ],
    durationDaysMin: 22,
    durationDaysMax: 38,
    modifiers: {
      economicGrowthDelta: 2.0,
      unemploymentDelta: -1.5,
      productionCostMultiplier: 1.10,
      commodityCategoryPriceMod: [
        { category: 'Стройматериалы', multiplier: 1.35 },
        { category: 'Металлы', multiplier: 1.30 },
        { category: 'Инструменты', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Триллион на стройку: правительство запустило крупнейший инфраструктурный проект века',
    newsBody: 'Подрядчики металлургии и строительных материалов обеспечены государственными заказами на годы вперед.',
    suggestedAction: 'Увеличивайте производство строительных материалов и металлоконструкций.',
  },
  {
    id: 'evt_green_energy_mandate',
    title: 'Зеленая трансформация и углеродные субсидии',
    category: 'energy_commodities',
    severity: 'moderate',
    icon: '🌱',
    description: 'Введены строгие экологические стандарты на традиционное топливо и масштабные налоговые вычеты для чистой энергетики.',
    consequences: [
      'Субсидии экологичным заводам: +15% к марже',
      'Налоги на старые углеводородные производства',
      'Рост акций возобновляемой энергетики: +20%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 30,
    modifiers: {
      stockMarketSentiment: 0.05,
      commodityCategoryPriceMod: [
        { category: 'Нефть', multiplier: 0.90 },
      ],
    },
    newsHeadline: 'Зеленый переход: чистая энергетика получает беспрецедентные налоговые льготы',
    newsBody: 'Предприятия модернизируют фильтры и переходят на солнечную и ветровую генерацию.',
    suggestedAction: 'Модернизируйте технологии предприятий до стандартов эко-эффективности.',
  },
  {
    id: 'evt_patent_expiry_wave',
    title: 'Истечение сроков ключевых патентов',
    category: 'industry_tech',
    severity: 'moderate',
    icon: '📜',
    description: 'Защита сотен фундаментальных патентов истекла. Рынок наводнили доступные дженерики и открытые технологии.',
    consequences: [
      'Снижение себестоимости сложной электроники: -15%',
      'Удешевление автозапчастей и медикаментов: -20%',
      'Увеличение конкуренции среди производителей',
    ],
    durationDaysMin: 16,
    durationDaysMax: 28,
    modifiers: {
      productionCostMultiplier: 0.88,
      commodityCategoryPriceMod: [
        { category: 'Комплектующие', multiplier: 0.80 },
        { category: 'Автозапчасти', multiplier: 0.82 },
      ],
    },
    newsHeadline: 'Технологии стали доступнее: истекли патенты на ключевые компоненты',
    newsBody: 'Малый и средний бизнес получил возможность производить высокотехнологичную продукцию без роялти.',
    suggestedAction: 'Организуйте производство аналогов с минимальной себестоимостью.',
  },
  {
    id: 'evt_rare_earths_export_curb',
    title: 'Эмбарго на экспорт редкоземельных металлов',
    category: 'energy_commodities',
    severity: 'major',
    icon: '💎',
    description: 'Ведущая добывающая страна ограничила экспорт неодима, лития и кобальта. Высокотехнологичные фабрики на грани дефицита.',
    consequences: [
      'Цены на металлы и комплектующие: +40%',
      'Удорожание производства электроники и аккумуляторов: +25%',
      'Рост цен на новые электромобили: +15%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      productionCostMultiplier: 1.18,
      carSalesMultiplier: 1.10,
      commodityCategoryPriceMod: [
        { category: 'Металлы', multiplier: 1.40 },
        { category: 'Комплектующие', multiplier: 1.35 },
      ],
    },
    newsHeadline: 'Редкоземельный кризис: котировки металлов для аккумуляторов взлетели до небес',
    newsBody: 'Производители электроники формируют экстренные резервы лития и кобальта.',
    suggestedAction: 'Спекулируйте металлами на сырьевой бирже.',
  },
  {
    id: 'evt_cloud_datacenter_boom',
    title: 'Бум строительства ИИ-датацентров',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🖥️',
    description: 'Глобальные IT-гиганты массово строят гигантские серверные кластеры. Спрос на серверы и охлаждение зашкаливает.',
    consequences: [
      'Спрос на компьютеры и комплектующие: +45%',
      'Цены на серверное оборудование: +35%',
      'Рост акций технологического сектора: +15%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      stockMarketSentiment: 0.10,
      commodityCategoryPriceMod: [
        { category: 'Компьютеры', multiplier: 1.45 },
        { category: 'Комплектующие', multiplier: 1.40 },
        { category: 'Электроника', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Датацентровый бум: серверное оборудование раскуплено на год вперед',
    newsBody: 'IT-корпорации скупают вычислительные мощности любыми партиями по повышенным ценам.',
    suggestedAction: 'Поставляйте компьютерное оборудование крупным корпоративным заказчикам.',
  },
  {
    id: 'evt_credit_crunch_tightening',
    title: 'Кредитное сжатие и ужесточение банковского скоринга',
    category: 'monetary_policy',
    severity: 'major',
    icon: '🔒',
    description: 'В связи с ростом невозвратов банки резко ужесточили требования к заемщикам и сократили лимиты овердрафтов.',
    consequences: [
      'Банковские кредиты стали труднодоступны',
      'Процентные надбавки по займам: +2.5%',
      'Снижение ликвидности на рынке',
    ],
    durationDaysMin: 14,
    durationDaysMax: 24,
    modifiers: {
      bankLoanRateModifier: 0.025,
      consumerConfidenceDelta: -12,
      realEstateDemandMultiplier: 0.90,
    },
    newsHeadline: 'Банки закручивают гайки: коммерческое кредитование упало на 30%',
    newsBody: 'Предприятия без собственного кэша испытывают трудности с пополнением оборотных средств.',
    suggestedAction: 'Опирайтесь на самофинансирование за счет чистой прибыли действующих бизнесов.',
  },
  {
    id: 'evt_liquidity_injection_qe',
    title: 'Программа количественного смягчения (QE)',
    category: 'monetary_policy',
    severity: 'boom',
    icon: '💵',
    description: 'Центробанк запустил программу выкупа активов и влил сотни миллиардов ликвидности в банковскую систему.',
    consequences: [
      'Взлет фондового рынка: +12%',
      'Снижение стоимости заимствований: -1.5%',
      'Рост цен на недвижимость и автомобили: +10%',
      'Умеренное ускорение инфляции: +1.0%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 30,
    modifiers: {
      stockMarketSentiment: 0.12,
      interestRateDelta: -1.5,
      inflationDelta: 1.0,
      realEstateDemandMultiplier: 1.10,
      carSalesMultiplier: 1.10,
    },
    newsHeadline: 'Печатный станок включен: центробанки заливают рынки дешевой ликвидностью',
    newsBody: 'Фондовые индексы и сырьевые активы растут на фоне огромного притока свежего капитала.',
    suggestedAction: 'Инвестируйте свободную ликвидность в растущие акции и твердые активы.',
  },
  {
    id: 'evt_corporate_m_and_a_wave',
    title: 'Волна мега-слияний и поглощений (M&A)',
    category: 'macroeconomics',
    severity: 'moderate',
    icon: '🤝',
    description: 'Корпорации активно объединяют активы для создания отраслевых монополий и оптимизации логистических цепочек.',
    consequences: [
      'Рост капитализации холдингов: +15%',
      'Премии за выкуп акций у конкурентов',
      'Оживление инвестиционного банкинга',
    ],
    durationDaysMin: 15,
    durationDaysMax: 26,
    modifiers: {
      stockMarketSentiment: 0.07,
      economicGrowthDelta: 0.9,
    },
    newsHeadline: 'Сезон слияний: сумма корпоративных M&A сделок побила пятилетний рекорд',
    newsBody: 'Крупные холдинги активно скупают доли в перспективных конкурентах и фабриках.',
    suggestedAction: 'Приобретайте доли акций в ведущих AI-корпорациях в разделе Рейтинга.',
  },
  {
    id: 'evt_supply_chain_reshoring',
    title: 'Национализация и перенос производств (Reshoring)',
    category: 'logistics_supply',
    severity: 'moderate',
    icon: '🏭',
    description: 'Компании массово переносят сборочные фабрики из-за рубежа ближе к рынкам сбыта для снижения рисков.',
    consequences: [
      'Рост спроса на производственные цеха и заводы: +25%',
      'Снижение зависимости от морских тарифов: -15%',
      'Рост внутренних заказов',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      factoryOutputMultiplier: 1.15,
      transportCostPercentChange: -0.10,
      realEstateDemandMultiplier: 1.12,
    },
    newsHeadline: 'Возвращение заводов домой: бум строительства локальных промышленных парков',
    newsBody: 'Отечественные фабрики загружены заказами на месяцы вперед.',
    suggestedAction: 'Стройте новые фабрики и заводы для выполнения внутренних контрактов.',
  },
  {
    id: 'evt_autonomous_logistics_era',
    title: 'Запуск автономных грузоперевозок и робо-складов',
    category: 'logistics_supply',
    severity: 'boom',
    icon: '🚚',
    description: 'Массовое внедрение беспилотных фур и складских роботов-манипуляторов кардинально удешевило логистику.',
    consequences: [
      'Снижение стоимости перевозки грузов: -25%',
      'Снижение затрат на содержание складов: -30%',
      'Увеличение скорости доставки в 2 раза',
    ],
    durationDaysMin: 20,
    durationDaysMax: 36,
    modifiers: {
      transportCostPercentChange: -0.25,
      productionCostMultiplier: 0.88,
      retailSalesMultiplier: 1.10,
    },
    newsHeadline: 'Эра роботов в логистике: беспилотные фуры вышли на основные магистрали',
    newsBody: 'Затраты на перемещение тонн груза между городами упали на четверть.',
    suggestedAction: 'Расширяйте сеть складов и запускайте автоматические маршруты снабжения.',
  },
  {
    id: 'evt_fintech_instant_payments',
    title: 'Внедрение мгновенных трансграничных финтех-расчетов',
    category: 'industry_tech',
    severity: 'moderate',
    icon: '💳',
    description: 'Запуск новой архитектуры межбанковских расчетов сократил комиссии за переводы до сотых долей процента.',
    consequences: [
      'Снижение транзакционных издержек бизнеса: -5%',
      'Ускорение оборота капитала',
      'Рост розничной онлайн-торговли: +15%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 28,
    modifiers: {
      retailSalesMultiplier: 1.12,
      stockMarketSentiment: 0.05,
    },
    newsHeadline: 'Финтех-революция: мгновенные расчеты без банковских комиссий стали реальностью',
    newsBody: 'Коммерческие предприятия экономят миллиарды на эквайринге и конвертациях.',
    suggestedAction: 'Увеличивайте обороты через розничные торговые сети.',
  },
  {
    id: 'evt_luxury_supercar_frenzy',
    title: 'Культ суперкаров и коллекционных авто',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '🏎️',
    description: 'Мировой автоспорт и выставки суперкаров вызвали небывалый интерес к эксклюзивным и спортивным автомобилям.',
    consequences: [
      'Продажи спорткаров и люкс-авто: +50%',
      'Маржинальность автосалонов: +30%',
      'Спрос на тюнинг и премиальные запчасти',
    ],
    durationDaysMin: 14,
    durationDaysMax: 25,
    modifiers: {
      carSalesMultiplier: 1.50,
      commodityCategoryPriceMod: [
        { category: 'Автозапчасти', multiplier: 1.30 },
        { category: 'Масла', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Ажиотаж на авторынке: премиальные спорткары раскупаются по предзаказам',
    newsBody: 'Автосалоны премиум-класса показывают рекордные финансовые результаты.',
    suggestedAction: 'Наполняйте автосалоны спортивными и премиальными марками автомобилей.',
  },
  {
    id: 'evt_extreme_cold_winter',
    title: 'Аномально холодная зима: энергетический пик',
    category: 'energy_commodities',
    severity: 'major',
    icon: '❄️',
    description: 'Рекордные морозы привели к колоссальному расходу топлива, газа и электроэнергии для отопления.',
    consequences: [
      'Цены на нефть и топливо: +25%',
      'Расходы на отопление и содержание складов/фабрик: +20%',
      'Взлет спроса на теплую одежду и обувь: +40%',
    ],
    durationDaysMin: 12,
    durationDaysMax: 20,
    modifiers: {
      oilPricePercentChange: 0.25,
      productionCostMultiplier: 1.15,
      commodityCategoryPriceMod: [
        { category: 'Одежда', multiplier: 1.35 },
        { category: 'Обувь', multiplier: 1.30 },
        { category: 'Нефть', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Генерал Мороз: энергетические системы работают на пределе возможностей',
    newsBody: 'Магазины теплой одежды и обуви фиксируют взрывной спрос, в то время как счета за отопление заводов выросли.',
    suggestedAction: 'Торгуйте теплой одеждой и обувью в магазинах.',
  },
  {
    id: 'evt_organic_eco_movement',
    title: 'Глобальный тренд на здоровое и эко-питание',
    category: 'retail_consumer',
    severity: 'moderate',
    icon: '🥗',
    description: 'Потребители массово переходят на фермерские органические продукты, экологичную косметику и напитки без сахара.',
    consequences: [
      'Спрос на премиум-продукты питания: +35%',
      'Наценка продуктовых супермаркетов: +20%',
      'Снижение спроса на дешевые заменители',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Продукты', multiplier: 1.25 },
        { category: 'Напитки', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Эко-революция на полках: продажи органических продуктов бьют рекорды',
    newsBody: 'Супермаркеты расширяют линейки здорового питания с повышенной рентабельностью.',
    suggestedAction: 'Поставляйте премиальные фермерские продукты в ваши супермаркеты.',
  },
  {
    id: 'evt_space_commercialization',
    title: 'Коммерциализация космоса и орбитальной логистики',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🛰️',
    description: 'Спутниковые группировки нового поколения обеспечили сверхточную навигацию и связь для транспорта в любой точке планеты.',
    consequences: [
      'Эффективность автопарка: +15%',
      'Снижение потерь при доставке: -20%',
      'Рост акций технологического сектора: +12%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 35,
    modifiers: {
      transportCostPercentChange: -0.12,
      stockMarketSentiment: 0.08,
      factoryOutputMultiplier: 1.10,
    },
    newsHeadline: 'Спутниковая логистика: глобальное покрытие связью удешевило мониторинг грузов',
    newsBody: 'Компании получили полный контроль над цепочками поставок в реальном времени.',
    suggestedAction: 'Развивайте межрегиональные логистические цепочки.',
  },
  {
    id: 'evt_drone_delivery_legalization',
    title: 'Легализация и запуск грузовых дронов в городах',
    category: 'logistics_supply',
    severity: 'boom',
    icon: '🛸',
    description: 'Авиационные регуляторы открыли низковысотные воздушные коридоры для автономных дронов доставки.',
    consequences: [
      'Скорость доставки розничных товаров: +80%',
      'Рост выручки интернет-магазинов и ритейла: +20%',
      'Спрос на специализированные датчики и компоненты',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      retailSalesMultiplier: 1.20,
      commodityCategoryPriceMod: [
        { category: 'Комплектующие', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Небо открыто: грузовые дроны начали массовую доставку заказов покупателям',
    newsBody: 'Покупатели получают товары в течение 30 минут после клика в приложении.',
    suggestedAction: 'Увеличивайте товарные запасы в розничных магазинах.',
  },
  {
    id: 'evt_coffee_bean_frost',
    title: 'Заморозки на высокогорных плантациях кофе и какао',
    category: 'energy_commodities',
    severity: 'major',
    icon: '☕',
    description: 'Аномальные заморозки в Южной Америке уничтожили треть урожая арабики и какао-бобов.',
    consequences: [
      'Цены на кофе, какао и напитки: +45%',
      'Рост среднего чека в кофейнях и ресторанах: +25%',
      'Оптовые спекуляции на продовольственной бирже',
    ],
    durationDaysMin: 15,
    durationDaysMax: 26,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Напитки', multiplier: 1.45 },
        { category: 'Продукты', multiplier: 1.15 },
      ],
    },
    newsHeadline: 'Кофейный шок: биржевые фьючерсы на арабику подскочили на 45%',
    newsBody: 'Кофейни и сети быстрого питания вынуждены повышать отпускные цены в меню.',
    suggestedAction: 'Продавайте складские запасы напитков по максимальной рыночной цене.',
  },
  {
    id: 'evt_fashion_week_craze',
    title: 'Неделя Высокой Моды и бум дизайнерских коллекций',
    category: 'retail_consumer',
    severity: 'moderate',
    icon: '👠',
    description: 'Главные мировые подиумы задали новые тренды. Модные дома фиксируют шквал заказов на одежду и обувь.',
    consequences: [
      'Продажи в магазинах одежды и обуви: +40%',
      'Наценка на модные коллекции: +30%',
      'Спрос на премиальные ткани и кожу',
    ],
    durationDaysMin: 12,
    durationDaysMax: 20,
    modifiers: {
      retailSalesMultiplier: 1.25,
      commodityCategoryPriceMod: [
        { category: 'Одежда', multiplier: 1.35 },
        { category: 'Обувь', multiplier: 1.30 },
        { category: 'Хлопок', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Модный бум: магазины одежды штурмуют ценители трендовых коллекций',
    newsBody: 'Бутики премиальной одежды сообщают о полной распродаже свежих поступлений.',
    suggestedAction: 'Заполните магазины одежды и обуви топовыми позициями.',
  },
  {
    id: 'evt_smart_cities_megaproject',
    title: 'Мегапроект «Умный Мегаполис»: датчики и автоматика',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🏙️',
    description: 'Масштабная цифровизация городской инфраструктуры: установка миллионов IoT-датчиков, умных счетчиков и камер.',
    consequences: [
      'Спрос на микрочипы и электронику: +40%',
      'Госзаказы для приборостроительных заводов: +30%',
      'Ускорение промышленного роста: +1.4%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      economicGrowthDelta: 1.4,
      commodityCategoryPriceMod: [
        { category: 'Электроника', multiplier: 1.35 },
        { category: 'Комплектующие', multiplier: 1.30 },
        { category: 'Инструменты', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Города будущего: госзакупки электроники и IoT-систем бьют рекорды',
    newsBody: 'Производители контроллеров и микросхем загружены контрактными заказами.',
    suggestedAction: 'Производите электронику и компьютеры на заводских линиях.',
  },
  {
    id: 'evt_freight_rate_plunge',
    title: 'Переизбыток торгового флота: обвал стоимости фрахта',
    category: 'logistics_supply',
    severity: 'moderate',
    icon: '⚓',
    description: 'Ввод в строй сотен новых сухогрузов и контейнеровозов привел к переизбытку тоннажа. Тарифы на перевозки рухнули.',
    consequences: [
      'Стоимость транспортировки: -22%',
      'Удешевление импорта сырья: -12%',
      'Рост маржинальности внешней торговли',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      transportCostPercentChange: -0.22,
      productionCostMultiplier: 0.92,
    },
    newsHeadline: 'Фрахт подешевел на 22%: грузоотправители экономят миллиарды на доставке',
    newsBody: 'Снижение логистических расходов стимулирует трансграничный товарный обмен.',
    suggestedAction: 'Используйте дешевый транспорт для оптовых спекуляций между городами.',
  },
  {
    id: 'evt_commercial_solar_subsidies',
    title: 'Субсидии на установку солнечных панелей на складах',
    category: 'energy_commodities',
    severity: 'boom',
    icon: '☀️',
    description: 'Государство компенсирует до 50% затрат на монтаж солнечных батарей и накопителей на крышах складов и фабрик.',
    consequences: [
      'Снижение коммунальных расходов складов и заводов: -25%',
      'Рост стоимости энергоэффективных объектов недвижимости: +15%',
      'Спрос на кремниевые элементы и комплектующие',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      productionCostMultiplier: 0.88,
      realEstateDemandMultiplier: 1.12,
      commodityCategoryPriceMod: [
        { category: 'Комплектующие', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Солнечные крыши: бизнес массово переходит на собственную генерацию',
    newsBody: 'Складские комплексы с солнечными панелями снижают эксплуатационные расходы на четверть.',
    suggestedAction: 'Стройте современные склады и модернизируйте фабрики.',
  },
  {
    id: 'evt_apparel_cotton_supercycle',
    title: 'Хлопковый суперцикл: дефицит натуральных тканей',
    category: 'energy_commodities',
    severity: 'major',
    icon: '🧶',
    description: 'Наводнения в хлопководческих регионах сократили мировой сбор хлопка на 25%. Пряжа и ткани подорожали.',
    consequences: [
      'Хлопок и сырье для текстиля: +35%',
      'Цены на одежду и текстиль: +20%',
      'Рост маржи текстильных фабрик',
    ],
    durationDaysMin: 15,
    durationDaysMax: 26,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Хлопок', multiplier: 1.40 },
        { category: 'Одежда', multiplier: 1.25 },
      ],
    },
    newsHeadline: 'Дефицит хлопка: цены на натуральные ткани достигли пика за 10 лет',
    newsBody: 'Швейные фабрики и магазины одежды пересматривают розничные ценники.',
    suggestedAction: 'Торгуйте хлопком и готовой одеждой на товарной бирже.',
  },
  {
    id: 'evt_commercial_real_estate_boom',
    title: 'Бум офисных небоскребов и коворкинг-хабов',
    category: 'real_estate',
    severity: 'boom',
    icon: '🏙️',
    description: 'Массовый возврат сотрудников в офисы и открытие новых штаб-квартир вызвали дефицит офисов класса A+.',
    consequences: [
      'Арендные ставки бизнес-центров: +30%',
      'Рыночная стоимость офисной недвижимости: +22%',
      'Заполняемость арендаторами: 98%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 30,
    modifiers: {
      realEstateDemandMultiplier: 1.30,
      economicGrowthDelta: 1.1,
    },
    newsHeadline: 'Офисный ренессанс: ставки аренды в бизнес-центрах выросли на 30%',
    newsBody: 'Корпорации соревнуются за лучшие представительские офисы в центре мегаполиса.',
    suggestedAction: 'Приобретайте бизнес-центры и офисные здания в портфель недвижимости.',
  },
  {
    id: 'evt_used_car_price_surge',
    title: 'Взлет цен на вторичном авторынке',
    category: 'retail_consumer',
    severity: 'major',
    icon: '🚘',
    description: 'Ограничение поставок новых машин стимулировало ажиотажный спрос на автомобили с пробегом.',
    consequences: [
      'Маржа перепродажи автомобилей: +35%',
      'Спрос на автосервисы и запчасти: +25%',
      'Быстрая оборачиваемость автосалонов',
    ],
    durationDaysMin: 14,
    durationDaysMax: 25,
    modifiers: {
      carSalesMultiplier: 1.35,
      commodityCategoryPriceMod: [
        { category: 'Автозапчасти', multiplier: 1.25 },
        { category: 'Шины', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Автомобильный бум: подержанные машины продаются с рекордной наценкой',
    newsBody: 'Автосалоны фиксируют максимальную маржу за последние несколько кварталов.',
    suggestedAction: 'Активно закупайте и перепродавайте автомобили в автосалонах.',
  },
  {
    id: 'evt_robotics_factory_upgrade',
    title: 'Субсидии на покупку промышленных роботов-манипуляторов',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🦾',
    description: 'Национальная технологическая инициатива компенсирует затраты предприятий на внедрение роботизированных сборочных линий.',
    consequences: [
      'Производственная мощность фабрик: +30%',
      'Снижение брака и производственных расходов: -18%',
      'Рост акций технологических компаний: +15%',
    ],
    durationDaysMin: 20,
    durationDaysMax: 35,
    modifiers: {
      factoryOutputMultiplier: 1.30,
      productionCostMultiplier: 0.82,
      stockMarketSentiment: 0.09,
    },
    newsHeadline: 'Роботизация цехов: заводы увеличили выпуск готовой продукции на 30%',
    newsBody: 'Автоматизация конвейеров позволяет фабрикам работать в непрерывном трехсменном режиме.',
    suggestedAction: 'Модернизируйте производственные фабрики новейшим оборудованием.',
  },
  {
    id: 'evt_high_speed_railway_opening',
    title: 'Запуск скоростной грузовой железнодорожной магистрали',
    category: 'logistics_supply',
    severity: 'boom',
    icon: '🚅',
    description: 'Открыта новая скоростная ветка между промышленными кластерами и крупнейшими узлами распределения.',
    consequences: [
      'Снижение стоимости перевозки оптовых партий: -20%',
      'Ускорение грузооборота между складами: +50%',
      'Увеличение пропускной способности логистики',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      transportCostPercentChange: -0.20,
      retailSalesMultiplier: 1.08,
      economicGrowthDelta: 0.9,
    },
    newsHeadline: 'Магистраль открыта: скоростные поезда доставляют оптовые грузы за часы',
    newsBody: 'Оптовые поставщики существенно сократили расходы на переброску товаров.',
    suggestedAction: 'Задействуйте межрегиональные оптовые торговые маршруты.',
  },
  {
    id: 'evt_smart_home_mass_adoption',
    title: 'Бум систем «Умный Дом» и голосовых ассистентов',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '🏠',
    description: 'Потребители массово оборудуют квартиры смарт-замками, роботами-пылесосами, климат-контролем и умными дисплеями.',
    consequences: [
      'Продажи бытовой техники и электроники: +40%',
      'Маржа магазинов бытовой техники: +25%',
      'Спрос на домашние гаджеты и смарт-решения',
    ],
    durationDaysMin: 14,
    durationDaysMax: 26,
    modifiers: {
      retailSalesMultiplier: 1.25,
      commodityCategoryPriceMod: [
        { category: 'Бытовая техника', multiplier: 1.35 },
        { category: 'Электроника', multiplier: 1.25 },
        { category: 'Смартфоны', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Умный дом в каждую квартиру: продажи смарт-электроники выросли на 40%',
    newsBody: 'Магазины электроники и бытовой техники рапортуют об отличных финансовых показателях.',
    suggestedAction: 'Поставляйте бытовую технику и электронику в магазины.',
  },
  {
    id: 'evt_pet_care_industry_boom',
    title: 'Взрывной рост индустрии товаров для домашних питомцев',
    category: 'retail_consumer',
    severity: 'moderate',
    icon: '🐾',
    description: 'Владельцы домашних животных тратят рекордные суммы на премиальные корма, аксессуары, косметику и одежду для питомцев.',
    consequences: [
      'Выручка зоомагазинов и ритейла: +35%',
      'Спрос на специализированное сырье и упаковку',
      'Высокая лояльность покупателей',
    ],
    durationDaysMin: 15,
    durationDaysMax: 28,
    modifiers: {
      retailSalesMultiplier: 1.15,
      commodityCategoryPriceMod: [
        { category: 'Продукты', multiplier: 1.15 },
        { category: 'Пластик', multiplier: 1.12 },
      ],
    },
    newsHeadline: 'Культ заботы о питомцах: рынок зоотоваров обгоняет традиционный ритейл',
    newsBody: 'Покупатели готовы платить повышенную цену за премиальное качество.',
    suggestedAction: 'Открывайте новые розничные торговые точки.',
  },
  {
    id: 'evt_cement_concrete_deficit',
    title: 'Дефицит цемента и товарного бетона',
    category: 'energy_commodities',
    severity: 'major',
    icon: '🧱',
    description: 'Массовое строительство мегапроектов вызвало нехватку портландцемента и строительных смесей.',
    consequences: [
      'Цены на стройматериалы: +35%',
      'Удорожание возведения новых зданий: +18%',
      'Рост маржи производителей сухих смесей: +40%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 28,
    modifiers: {
      productionCostMultiplier: 1.10,
      commodityCategoryPriceMod: [
        { category: 'Стройматериалы', multiplier: 1.35 },
        { category: 'Инструменты', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Строительный дефицит: заводы цемента работают с перегрузкой 120%',
    newsBody: 'Оптовые партии стройматериалов выкупаются со складов прямо с колес.',
    suggestedAction: 'Торгуйте стройматериалами на оптовом рынке.',
  },
  {
    id: 'evt_luxury_watch_speculation',
    title: 'Спекулятивный бум на коллекционные швейцарские часы',
    category: 'retail_consumer',
    severity: 'boom',
    icon: '⌚',
    description: 'Инвесторы рассматривают люксовые часы как защитный актив от инфляции. Цены на вторичном рынке бьют исторические максимумы.',
    consequences: [
      'Маржа премиальных бутиков: +50%',
      'Спрос на ювелирные изделия и металлы: +30%',
      'Рост чека в люкс-сегменте',
    ],
    durationDaysMin: 14,
    durationDaysMax: 24,
    modifiers: {
      retailSalesMultiplier: 1.18,
      commodityCategoryPriceMod: [
        { category: 'Металлы', multiplier: 1.25 },
        { category: 'Одежда', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Время — деньги: инвестиционные часы показывают доходность выше акций',
    newsBody: 'Бутики элитных аксессуаров фиксируют рекордные продажи.',
    suggestedAction: 'Приобретайте премиальные активы и расширяйте сеть люкс-бутиков.',
  },
  {
    id: 'evt_sovereign_wealth_fund_investments',
    title: 'Суверенный фонд вливает триллион в национальную индустрию',
    category: 'macroeconomics',
    severity: 'boom',
    icon: '🏛️',
    description: 'Крупнейший суверенный фонд национального благосостояния объявил о прямых инвестициях в производственные холдинги и логистику.',
    consequences: [
      'Рост капитализации промышленных предприятий: +20%',
      'Ускорение роста ВВП: +2.2%',
      'Повышение потребительского доверия: +18 пунктов',
      'Оживление кредитного рынка',
    ],
    durationDaysMin: 22,
    durationDaysMax: 36,
    modifiers: {
      economicGrowthDelta: 2.2,
      consumerConfidenceDelta: 18,
      stockMarketSentiment: 0.10,
      productionCostMultiplier: 0.94,
    },
    newsHeadline: 'Триллионный импульс: суверенный фонд инвестирует в реальный сектор экономики',
    newsBody: 'Промышленные холдинги получают масштабные заказы и долгосрочное проектное финансирование.',
    suggestedAction: 'Расширяйте бизнес-империю и инвестируйте в производство.',
  },
  {
    id: 'evt_synthetic_materials_breakthrough',
    title: 'Изобретение сверхлегких композитных полимеров',
    category: 'industry_tech',
    severity: 'boom',
    icon: '🧪',
    description: 'Ученые представили новый композитный пластик прочнее стали и втрое легче алюминия.',
    consequences: [
      'Удешевление производства автомобилей и техники: -20%',
      'Спрос на полимерное сырье: +35%',
      'Взлет акций инновационных корпораций: +16%',
    ],
    durationDaysMin: 18,
    durationDaysMax: 32,
    modifiers: {
      factoryOutputMultiplier: 1.20,
      productionCostMultiplier: 0.85,
      carSalesMultiplier: 1.15,
      commodityCategoryPriceMod: [
        { category: 'Пластик', multiplier: 1.35 },
        { category: 'Автозапчасти', multiplier: 0.85 },
      ],
    },
    newsHeadline: 'Материалы нового века: композиты заменяют металл в автомобилях и гаджетах',
    newsBody: 'Автопром и машиностроение переходят на новые легкие материалы.',
    suggestedAction: 'Производите пластик и автозапчасти на фабриках.',
  },
  {
    id: 'evt_commercial_cargo_fleet_renewal',
    title: 'Госпрограмма льготного лизинга грузовиков и фур',
    category: 'logistics_supply',
    severity: 'moderate',
    icon: '🚛',
    description: 'Транспортные компании получили возможность обновлять грузовой автопарк под 2% годовых с нулевым первым взносом.',
    consequences: [
      'Снижение эксплуатационных расходов автопарка: -20%',
      'Снижение стоимости перевозки грузов: -15%',
      'Рост продаж коммерческого транспорта: +35%',
    ],
    durationDaysMin: 16,
    durationDaysMax: 30,
    modifiers: {
      transportCostPercentChange: -0.15,
      carSalesMultiplier: 1.20,
    },
    newsHeadline: 'Льготный лизинг: перевозчики массово обновляют магистральные тягачи',
    newsBody: 'Новые экономичные грузовики снижают себестоимость каждого километра пути.',
    suggestedAction: 'Пополняйте корпоративный автопарк современными грузовиками.',
  },
  {
    id: 'evt_global_datacenter_cooling_deficit',
    title: 'Дефицит промышленных систем охлаждения и чиллеров',
    category: 'industry_tech',
    severity: 'moderate',
    icon: '❄️',
    description: 'Бум серверов вызвал острый дефицит мощных вентиляционных установок и фреона.',
    consequences: [
      'Цены на климатическую и бытовую технику: +25%',
      'Спрос на комплектующие и инструменты: +20%',
      'Рост маржинальности промышленных поставщиков',
    ],
    durationDaysMin: 14,
    durationDaysMax: 24,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Бытовая техника', multiplier: 1.25 },
        { category: 'Инструменты', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Охлаждение на вес золота: производители чиллеров не справляются со спросом',
    newsBody: 'Датацентры и фабрики переплачивают за срочные поставки систем охлаждения.',
    suggestedAction: 'Торгуйте бытовой техникой и промышленными компонентами.',
  },
  {
    id: 'evt_ecommerce_package_surge',
    title: 'Взрывной бум картонной упаковки и тары',
    category: 'logistics_supply',
    severity: 'moderate',
    icon: '📦',
    description: 'Миллионы ежедневных онлайн-заказов вызвали нехватку гофрокартона и упаковочной пленки.',
    consequences: [
      'Цены на древесину и пластик: +20%',
      'Рост складских расходов на упаковку: +10%',
      'Сверхприбыли целлюлозно-бумажных комбинатов',
    ],
    durationDaysMin: 15,
    durationDaysMax: 26,
    modifiers: {
      commodityCategoryPriceMod: [
        { category: 'Древесина', multiplier: 1.25 },
        { category: 'Пластик', multiplier: 1.20 },
      ],
    },
    newsHeadline: 'Упаковочный бум: гофрокартон стал самым востребованным сырьем в ритейле',
    newsBody: 'Маркетплейсы скупают любые партии коробок и скотча.',
    suggestedAction: 'Поставляйте древесину и полимеры производителям упаковки.',
  },
  {
    id: 'evt_restaurant_gastronomy_wave',
    title: 'Гастрономический бум и расцвет ресторанных сетей',
    category: 'retail_consumer',
    severity: 'moderate',
    icon: '🍽️',
    description: 'Рекордная посещаемость ресторанов, фудмоллов и кофеен на фоне роста доходов населения.',
    consequences: [
      'Выручка заведений общепита: +35%',
      'Спрос на премиальные продукты и напитки: +30%',
      'Рост арендных ставок для ресторанных локаций: +15%',
    ],
    durationDaysMin: 14,
    durationDaysMax: 26,
    modifiers: {
      retailSalesMultiplier: 1.22,
      commodityCategoryPriceMod: [
        { category: 'Продукты', multiplier: 1.25 },
        { category: 'Напитки', multiplier: 1.30 },
      ],
    },
    newsHeadline: 'Ресторанный аншлаг: столики бронируются за недели вперед',
    newsBody: 'Индустрия гостеприимства переживает один из лучших периодов в истории.',
    suggestedAction: 'Снабжайте рестораны и торговые точки напитками и продуктами.',
  },
];

